### PR TITLE
Remove stray punctuation from secure-erase message

### PR DESCRIPTION
**Pull request by jwilk**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/fe65ccf95af52867c52538d8ec4aeed7655a1ab4

Oops, good catch! 4y old and nobody noticed.

**Comment by jwilk** [comment]
I saw it on screen. (The repository was on a VFAT filesystem.)

**Comment by ThomasWaldmann** [comment]
Could you do 2 more PRs, for 1.2-maint and 1.1-maint branches?

**Comment by jwilk** [comment]
> Could you do 2 more PRs

Don't count on me for that. Sorry!

**Comment by ThomasWaldmann** [comment]
@jwilk ok, no problem, we'll care for it.

**Comment by ThomasWaldmann** [comment]
done.

**Pull request merged**
