### PR TITLE
Add Open Collective to FUNDING.yml

### PR DESCRIPTION
**Pull request by pktiuk**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Hi, thanks for the PR!

Why did you add it there? We already have it on https://www.borgbackup.org/support/fund.html (which is linked from github also) and we can manage all funding sources there, independently of what github supports.

**Comment by pktiuk** [comment]
Hi, 

This just adds an icon of Open Collective the main page of your repo. 
I created this PR for purely esthetical reasons. ( [example repo with these badges](https://github.com/ActivityWatch/activitywatch/) )

**Comment by ThomasWaldmann** [comment]
@pktiuk right, it looks prettier.

Can you check whether we can add our other funding services there also?

So, there would be some duplication between gh and website, but otoh, we do not change that often.

**Comment by pktiuk** [comment]
@ThomasWaldmann   
Done. Liberapay is also one of the official GitHub donation platform: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
