### PR TITLE
Don't perform full Travis build on docs-only changes #2531

### PR DESCRIPTION
**Pull request by narendravardi**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@narendravardi thanks for the PR!

Just one problem: it cancelled THIS PR although it is **not** a docs-only-change.

**Comment by narendravardi** [comment]
@ThomasWaldmann I tested this functionality on two cases and then only requested PR.
1) doc-only changes.
2) Changes to doc-only files and script files. 
Both worked as expected.

I will check why this change cancelled the build and will get back to you.

Thanks for your time.

**Comment by narendravardi** [comment]
@ThomasWaldmann, While making changes I introduced two more commit :| 
Sorry about that. I do not know much about fix-up commits. Will read about it and merge these commits into one.

**Comment by narendravardi** [comment]
@ThomasWaldmann, please close this pull request. I would like to test it on my cloned repo. When ever I push, the changes are immediately being reflected here. After thorough testing, I will raise another PR. Thanks for your time again :)

**Comment by ThomasWaldmann** [comment]
ok, thanks for developing this, will be very useful once it works reliably.

maybe try to avoid outside requests, like curl/wget, if possible.

**Pull request closed without merging**
