### PR TITLE
Reformat commands list

### LINKED ISSUE #591: borg output without args unpretty
```
$ ./borg-linux64 
usage: borg-linux64 [-h] [-V]
                    
                    {serve,init,check,change-passphrase,create,extract,rename,delete,list,mount,info,break-lock,prune,upgrade,help,debug-dump-archive-items,debug-get-obj,debug-put-obj,debug-delete-obj}
                    ...

Borg - Deduplicated Backups

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show version number and exit

Available commands:
  {serve,init,check,change-passphrase,create,extract,rename,delete,list,mount,info,break-lock,prune,upgrade,help,debug-dump-archive-items,debug-get-obj,debug-put-obj,debug-delete-obj}
```

The duplicate list of subcommands is somehow rather redundant.

### PR DESCRIPTION
**Pull request by trassl**
This fixes #591

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
ah, good. :) how does `borg -h` look like now?

**Comment by trassl** [comment]
This is the help output:

```
usage: borg [-h] [-V]  ...

Borg - Deduplicated Backups

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show version number and exit

Available commands:
  
    serve               start repository server process
    init                initialize empty repository
    check               verify repository
    change-passphrase   change repository passphrase
    migrate-to-repokey  migrate passphrase-mode repostory to repokey
    create              create backup
    extract             extract archive contents
    rename              rename archive
    delete              delete archive
    list                list archive or repository contents
    mount               mount repository
    info                show archive information
    break-lock          break repository and cache locks
    prune               prune archives
    upgrade             upgrade repository format
    debug-dump-archive-items
                        dump archive items (metadata) (debug)
    debug-get-obj       get object from repository (debug)
    debug-put-obj       put object to repository (debug)
    debug-delete-obj    delete object from repository
```

**Comment by ThomasWaldmann** [comment]
Ah, much better! :)

Could we say "subcommand" or "COMMAND" instead of "..." at the top?

And above the list "Available subcommands" or "... COMMANDs"?

Also, please fix typo "repostory".

**Comment by trassl** [comment]
Fixed typo.

Added `<command>` metavar. Renamed 'Available commands' to 'required arguments' (you'll see why).

Help output:

```
usage: borg [-h] [-V] <command> ...

Borg - Deduplicated Backups

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show version number and exit

required arguments:
  <command>
    serve               start repository server process
    init                initialize empty repository
    check               verify repository
    change-passphrase   change repository passphrase
    migrate-to-repokey  migrate passphrase-mode repository to repokey
    create              create backup
    extract             extract archive contents
    rename              rename archive
    delete              delete archive
    list                list archive or repository contents
    mount               mount repository
    info                show archive information
    break-lock          break repository and cache locks
    prune               prune archives
    upgrade             upgrade repository format
    debug-dump-archive-items
                        dump archive items (metadata) (debug)
    debug-get-obj       get object from repository (debug)
    debug-put-obj       put object to repository (debug)
    debug-delete-obj    delete object from repository (debug)
```

**Comment by ThomasWaldmann** [comment]
thanks!

**Pull request merged**
