### PR TITLE
blake2b key modes: use B2B as MAC; longer keys.

### LINKED ISSUE #1896: blake2b as MAC layer for authenticated encryption.
way faster than hmac-sha256, one of borg's biggest cpu hogs.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/39600312-blake2b-as-mac-layer-for-authenticated-encryption)

### PR DESCRIPTION
**Pull request by enkore**
Fixes #1896

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3.6/library/hashlib-blake2.html#creating-hash-objects

rather have an api like that or at least param lengths doable with that?
then we could get rid of our own blake2b code again once we require python 3.6.

**Comment by enkore** [comment]
Using the Py3.6 or OpenSSL functions would only require a thin wrapper (like hmac_sha256).

**Comment by ThomasWaldmann** [comment]
I was just wondering about key length.

You assemble 64B random + 64B zeros. Python API only takes up to 64B (not 128B).
But I've looked into the python implementation, it seems to do same internally.

Seems you have also checked that hashes are same with that py36-blake2.py script.

**Comment by enkore** [comment]
Correct, the keyed API only takes up to 64B keys for the reasons mentioned in the comment. Note that due to the different parameter blocks between unkeyed and keyed hashes it wouldn't result in the same hash, you'll have to use the unkeyed API and process key and data as indicated. This is also what gives us the option to use OpenSSL.

**Pull request merged**
