### PR TITLE
OpenBSD only - statically link OpenSSL (#6474)

### PR DESCRIPTION
**Pull request by bket**
Avoid conflicting with shared libcrypto from the base OS pulled in via dependencies.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@bket it is best to run `black .`  in the workdir before committing - black will then fix all the formatting details for you.

**Comment by ThomasWaldmann** [comment]
BTW, i was just working on releasing 2.0.0b2, but maybe we should get this in before b2, so it can get some testing on openbsd.

**Comment by bket** [comment]
> @bket it is best to run `black .` in the workdir before committing - black will then fix all the formatting details for you.

Done, force pushed the fix

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
