### PR TITLE
borg with-lock REPO CMD ARGS

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Guess this is ready now for merging. After review, I'll collapse the commits.

manual usage:
```
(borg-env)tw@tux:~/w/borg$ borg with-lock repo ls -d repo/lock.exclusive
repo/lock.exclusive
```

### CODE REVIEW

**Comment by edgewood** [comment]
Consider using nargs=argparse.REMAINDER to avoid the requirement for quotes and use of shlex.split.
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.

**Comment by ThomasWaldmann** [comment]
@edgewood done, PR updated.

**Comment by edgewood** [comment]
Help text still says "The command needs to be given as a single argument..."

**Comment by ThomasWaldmann** [comment]
Oops, forgot "git add", likely.

**Comment by ThomasWaldmann** [comment]
It seems that the remote repo only creates an exclusive lock when a transaction is started and releases it when the repo is closed. We need to issue a put or delete to start a transaction.

So, shall we add another "well known" and reserved id (like 1, manifest_id is 0) that we can use for a small put?

We could also use get() to fetch some arbitrary id's contents (if any), then put() it back (and delete() it in case it did not exist before).

**Comment by ThomasWaldmann** [comment]
Done. :)

**Pull request merged**
