### PR TITLE
Refactor: move a test to ArchiverTestCase

### LINKED ISSUE #6168: test methods in wrong test class
check for 1.1-maint and master branch:

it seems that there are some test methods in `RemoteArchiverTestCase` that should be rather in the `ArchiverTestCase` class (which is inherited by `RemoteArchiverTestCase`).

idea:
- most tests should be in the base class `ArchiverTestCase`
- the remote tests class should contain tests that only make sense for remote repos
- the remote tests class might contain some test overrides for tests that do not work remotely, but would normally be inherited from the base class
-

### PR DESCRIPTION
**Pull request by hexagonrecursion**
Fixes #6168

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
test_strip_components_doesnt_leak <- i think that one is also at the wrong place (run the tests after moving it).

**Comment by ThomasWaldmann** [comment]
could you rename the strip test a little, so that there is remote_repo in the test name.

if one does not fully read the test (like me), one would assume that a strip-related test also applies to local repos, but in this case, the condition checked only applies to remote repos.

**Comment by hexagonrecursion** [comment]
Done

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
