### PR TITLE
Add Snappy compression

### PR DESCRIPTION
**Pull request by meme**
To do:
- [ ] Remove `config.h` and define macros using the `setup_compression.py` script
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for the PR!

Usually there is some discussion before adding bigger features like this, do we have a ticket about this and did you read #1633?

**Comment by ThomasWaldmann** [comment]
BTW, there are some compile issues on travis-ci, see there.

**Comment by meme** [comment]
Took a look at the issue you mentioned and I do not believe that Snappy meets all the requirements. I'll keep working on this one but it doesn't belong in Borg.

**Comment by ThomasWaldmann** [comment]
Sorry about the work you invested. Just open an issue before starting major work next time.

Yesterday, I looked around and my impression was that snappy is somehow between zstd and lz4, but being quite close, so I didn't see a real advantage of adding it, considering we already have lz4 and zstd.

Having more code (bundled or as a dependency) always means more burden that needs to be rectified.

**Comment by meme** [comment]
No worries about the work! The codebase is well factored so not too much time was spent at all. I hope to make more contributions to Borg in the future and will make sure to scope them out in an issue beforehand.

---

If I may ask: could this PR be labelled with `hacktoberfest-accepted`? And perhaps you may want to mark the repository with a tag for `hacktoberfest` as the event is now opt-in (more details [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update)).

**Comment by ThomasWaldmann** [comment]
Done, thanks for the hints.

**Pull request closed without merging**
