### PR TITLE
[DOCS] #4587 – Sphinx warnings

### PR DESCRIPTION
**Pull request by fantasya-pbem**
I addressed three different warnings here:
1. checking consistency... WARNING: document isn't included in any toctree
    This is prevented with the :orphan: directive.
2. WARNING: Explicit markup ends without a blank line; unexpected unindent.
    I just added a blank line.
3. WARNING: duplicate label
    This was difficult. The reason for these warnings is that both ``usage/general.rst`` and ``man_intro.rst``included the same ``usage_general.rst.inc`` file which contains three labels. The solution is to prevent including the labels multiple times. This is done by duplicating the include file, without the labels in the duplicate. As this would duplicate a big bunch of text, I separated the different sections of usage_general.rst.inc and moved them into small include files in usage/general/*.rst.inc.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Needs a rebase onto a current master (also, collapse / squash / edit commit comments).

`git rebase -i master`

**Comment by fantasya-pbem** [comment]
Merged with latest master. I did not sqash it yet to help you review it.

**Comment by ThomasWaldmann** [comment]
Thanks!

**Comment by ThomasWaldmann** [comment]
Does 1.1-maint have the same issues?

**Pull request merged**
