### PR TITLE
fix fuse tests on OS X, fixes #1433

### LINKED ISSUE #1433: OS X: fuse test failure
```
# osxfuse 3.3.3 and 3.4.1
# borg 1.0-maint commit e5a3229fd24f75d60238cad4ea5f93f469d4da5d
#
(borg-env) This-MacBook-Pro:borg vagrant$ py.test -k fuse
___________________________________________________ ArchiverTestCase.test_fuse ____________________________________________________

self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_fuse>

    @unittest.skipUnless(has_llfuse, 'llfuse not installed')
    def test_fuse(self):
        self.cmd('init', self.repository_location)
        self.create_test_files()
        self.cmd('create', self.repository_location + '::archive', 'input')
        self.cmd('create', self.repository_location + '::archive2', 'input')
        mountpoint = os.path.join(self.tmpdir, 'mountpoint')
        # mount the whole repository, archive contents shall show up in archivename subdirs of mountpoint:
        with self.fuse_mount(self.repository_location, mountpoint):
>           self.assert_dirs_equal(self.input_path, os.path.join(mountpoint, 'archive', 'input'))

borg/testsuite/archiver.py:1008: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
borg/testsuite/__init__.py:56: in assert_dirs_equal
    self._assert_dirs_equal_cmp(diff)
borg/testsuite/__init__.py:59: in _assert_dirs_equal_cmp
    self.assert_equal(diff.left_only, [])
E   AssertionError: Lists differ: ['flagfile'] != []
E   
E   First list contains 1 additional elements.
E   First extra element 0:
E   'flagfile'
E   
E   - ['flagfile']
E   + []
```

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
NOATIME support needed checking and the flagfile was UF_NODUMP and thus not there in the backup archive.

Note: i have just duplicated the has_noatime function instead of refactoring it to be global,
to avoid merge conflicts in case we cherry-pick the test improvements from master.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
> Note: i have just duplicated the has_noatime function instead of refactoring it to be global, to avoid merge conflicts in case we cherry-pick the test improvements from master.

You copied a partially broken one, look at 868586d.

**Comment by PlasmaPower** [comment]
Although, if that one works here, and the other one is also broken on 1.0-maint, then I suppose it doesn't matter that much.

**Comment by ThomasWaldmann** [comment]
@PlasmaPower after some testing in master, i guess we will cherrypick the test improvements from master to 1.0-maint.

**Comment by PlasmaPower** [comment]
Sounds good.

**Pull request merged**
