### PR TITLE
Fix Fedora installation instructions

### PR DESCRIPTION
**Pull request by scoobadog**
Update installation instructions so that the following error won't occur:

gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
error: command 'gcc' failed with exit status 1

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@pguth @scoobadog iirc, the korora build worked without that. So, is that just needed for redhat and not korora?

**Comment by pguth** [comment]
We didn't need that step while testing back then, so I guess it's specific to redhats' distribution. But I don't know what the current state is, sorry.

**Comment by scoobadog** [comment]
@ThomasWaldmann @pguth I don't know about Korora, but it didn't seem to work with Fedora 23 without that package so maybe it's Red Hat specific. I'm going to test this with Korora 23 and see whether or not it needs it.

**Comment by scoobadog** [comment]
Korora 23 doesn't need the `redhat-rpm-config` package. Should I add a comment to that line to indicate this?

**Comment by enkore** [comment]
Yes, no need to install it when it's not needed :)

**Comment by ThomasWaldmann** [comment]
thanks for fixing!

**Pull request merged**
