### PR TITLE
OpenSSL 1.0 and 1.1 compatibility

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
for testing on openssl 1.1 one needs this so it does not try to install attic (which does not work with openssl 1.1):
```
echo "# nope" > requirements.d/attic.txt
```

about the code:
I took it from the crypto-aead PR - I had trouble there with reading back ctx.iv in aes-gcm mode and replaced it by just computing the next iv in our code.

### CODE REVIEW

**Comment by enkore** [comment]
EVP_CIPHER_CTX_new / free are in 1.0.2, just not documented in the manual. Add a comment saying so?

Looks good

**Comment by enkore** [comment]
pickaxed openssl source, these functions are from 2005 and were included since 0.9.x times, so in all 1.x included.

**Comment by ThomasWaldmann** [comment]
Yes, somehow missing in the man page, but it is there:
https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg can you test 1.0-maint branch on debian experimental test infrastructure (with openssl 1.1.0 and all architectures) before we make a 1.0.4 release from it?

**Comment by LocutusOfBorg** [comment]
it seems to be building fine, at least the openssl part
http://debomatic-amd64.debian.net/distribution#experimental/borgbackup/1.0.4/buildlog
but it seems failing somewhere else.

good news: 1.0.3 still builds in unstable
http://debomatic-amd64.debian.net/distribution#unstable/borgbackup/1.0.3-1/buildlog

so, I can exclude a toolchain issue.

1.0.4 (snapshot of 1.0-maint) fails for unstable and for experimental

http://debomatic-amd64.debian.net/distribution#experimental/borgbackup/1.0.4/buildlog
http://debomatic-amd64.debian.net/distribution#unstable/borgbackup/1.0.4/buildlog
```
LookupError: setuptools-scm was unable to detect version for '/<<PKGBUILDDIR>>'.
```
also a lot of errors:
```
E   ImportError: No module named 'borg._version'
```

**Comment by ThomasWaldmann** [comment]
this is because setuptools-scm automatically manages versioning for us.
it seems it does not like whatever you have in pkgbuilddir.
@RonnyPfannschmidt any idea?

**Comment by LocutusOfBorg** [comment]
it might be because I'm not using a release tarball, but a git snapshot, probably there are spurious files in the git repo?

**Comment by RonnyPfannschmidt** [comment]
well, unless the debian guys describe the mess they make of repos in some way, i can't fix the automation tools

**Comment by LocutusOfBorg** [comment]
we don't mess anything, just we use the release tarballs, not the git repo as starting point :)

to be clear, I don't think this is an issue whenever you release the tarball and I import it
(basically we strip every auto-generated stuff and regenerate them at build time)
you can see the repo here
https://anonscm.debian.org/cgit/collab-maint/borgbackup.git/tree/

**Comment by RonnyPfannschmidt** [comment]
so if you use setuptools_scm in such a way, use https://github.com/pypa/setuptools_scm#environment-variables because you put it in a scm it can't trust for the metadata, and the files generated are just a fallback for when there is no scm

**Pull request merged**
