### PR TITLE
Update prevalence of env vars to set config and cache paths

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
re-applied #4951 to current master.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/github/borgbackup/borg/builds/669698288

**Comment by ThomasWaldmann** [comment]
did a minor grammar fix, ready to merge after travis is finished.

**Comment by ThomasWaldmann** [comment]
Done! Thanks for the PR.

**Comment by finefoot** [comment]
:+1:

**Pull request merged**
