### PR TITLE
Add borg config command (1.1 backport)

### PR DESCRIPTION
**Pull request by milkey-mouse**
See #3312.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
py34 and flake8 tests are unhappy.

**Comment by ThomasWaldmann** [comment]
@SanskritFritz btw, this is going to get merged soon. also, there will be a new 1.1 release soon.

So, if you want to add the `borg config` to the completions, do it asap please.

**Comment by SanskritFritz** [comment]
@ThomasWaldmann 
I'm on it, OK. What is the rough deadline? There is no due date on the milestone.

**Comment by ThomasWaldmann** [comment]
hopefully tomorrow .. monday.

**Comment by SanskritFritz** [comment]
Bit tight... let's see what I can do.

**Comment by ThomasWaldmann** [comment]
@SanskritFritz it won't be a problem no matter what. borg config is a rather rarely used command.

**Comment by SanskritFritz** [comment]
@milkey-mouse 
https://github.com/milkey-mouse/borg/issues/1

**Comment by milkey-mouse** [comment]
@ThomasWaldmann the py34 test is failing because unpacking in function calls is [new in Python 3.5](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations). I forgot to change that for 1.1-maint

**Comment by ThomasWaldmann** [comment]
The python 3.6-dev is also failing with a strange error. I restarted it, let's see if it still happens.

**Comment by milkey-mouse** [comment]
looks like they passed this time...

**Pull request merged**
