### PR TITLE
remove endianness macro, fixes #6105

### LINKED ISSUE #6105: build issue (with potential fix) on bigendian architectures
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug, seems already resolved in master but present in 1.1 branch (at least no sign of `__BIG_ENDIAN__` in `setup.py` in master)

#### Your borg version (borg -V).
1.1.17

#### Operating system (distribution) and version.
SynoCommunity, Synology DSM-6 (linux)

#### Hardware / network configuration, and filesystems used. 
PPC qoriq arch

#### How much data is handled by borg?
n/a - build issue only on PPC due to endianess

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
n/a

## Describe the problem you're observing.
build log:
```
Collecting borgbackup==1.1.17
  Using cached borgbackup-1.1.17.tar.gz (3.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: borgbackup
  Building wheel for borgbackup (setup.py): started
  Building wheel for borgbackup (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/crossenv/cross/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-t50qub2n/borgbackup_de5df87e60224e6ca41dbf5168a72ac2/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-t50qub2n/borgbackup_de5df87e60224e6ca41dbf5168a72ac2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zr688xe_
       cwd: /tmp/pip-wheel-t50qub2n/borgbackup_de5df87e60224e6ca41dbf5168a72ac2/
  Complete output (125 lines):
  Detected and preferring liblz4 over bundled LZ4
  Detected and preferring libb2 over bundled BLAKE2
  Detected and preferring libzstd over bundled ZSTD
  /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/crossenv/build/lib/python3.10/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/__main__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/_version.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/archive.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/archiver.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/cache.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/constants.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/fuse.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/helpers.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/locking.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/logger.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/lrucache.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/nanorst.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/patterns.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/remote.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/repository.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/selftest.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/shellpattern.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/upgrader.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/version.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/xattr.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms
  copying src/borg/algorithms/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  copying src/borg/crypto/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  copying src/borg/crypto/file_integrity.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  copying src/borg/crypto/key.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  copying src/borg/crypto/keymanager.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  copying src/borg/crypto/nonces.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/crypto
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/platform
  copying src/borg/platform/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/platform
  copying src/borg/platform/base.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/platform
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/archive.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/archiver.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/benchmark.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/cache.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/checksums.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/chunker.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/compress.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/crypto.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/file_integrity.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/hashindex.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/helpers.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/item.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/key.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/locking.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/logger.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/lrucache.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/nanorst.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/nonces.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/patterns.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/platform.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/remote.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/repository.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/shellpattern.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/upgrader.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/version.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  copying src/borg/testsuite/xattr.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  creating build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms/msgpack
  copying src/borg/algorithms/msgpack/__init__.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms/msgpack
  copying src/borg/algorithms/msgpack/_version.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms/msgpack
  copying src/borg/algorithms/msgpack/exceptions.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms/msgpack
  copying src/borg/algorithms/msgpack/fallback.py -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/algorithms/msgpack
  running egg_info
  writing src/borgbackup.egg-info/PKG-INFO
  writing dependency_links to src/borgbackup.egg-info/dependency_links.txt
  writing entry points to src/borgbackup.egg-info/entry_points.txt
  writing requirements to src/borgbackup.egg-info/requires.txt
  writing top-level names to src/borgbackup.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  reading manifest file 'src/borgbackup.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.coafile'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.gitattributes'
  warning: no previously-included files found matching '.gitignore'
  warning: no previously-included files found matching '.mailmap'
  warning: no previously-included files found matching 'Vagrantfile'
  no previously-included directories found matching '.github'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file 'src/borgbackup.egg-info/SOURCES.txt'
  copying src/borg/paperkey.html -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg
  copying src/borg/testsuite/attic.tar.gz -> build/lib.powerpc-e500v2-linux-gnuspe-3.10/borg/testsuite
  running build_ext
  skipping 'src/borg/algorithms/msgpack/_packer.cpp' Cython extension (up-to-date)
  skipping 'src/borg/algorithms/msgpack/_unpacker.cpp' Cython extension (up-to-date)
  skipping 'src/borg/compress.c' Cython extension (up-to-date)
  skipping 'src/borg/crypto/low_level.c' Cython extension (up-to-date)
  skipping 'src/borg/hashindex.c' Cython extension (up-to-date)
  skipping 'src/borg/item.c' Cython extension (up-to-date)
  skipping 'src/borg/chunker.c' Cython extension (up-to-date)
  skipping 'src/borg/algorithms/checksums.c' Cython extension (up-to-date)
  skipping 'src/borg/platform/posix.c' Cython extension (up-to-date)
  skipping 'src/borg/platform/linux.c' Cython extension (up-to-date)
  skipping 'src/borg/platform/syncfilerange.c' Cython extension (up-to-date)
  building 'borg.algorithms.msgpack._packer' extension
  creating build/temp.powerpc-e500v2-linux-gnuspe-3.10
  creating build/temp.powerpc-e500v2-linux-gnuspe-3.10/src
  creating build/temp.powerpc-e500v2-linux-gnuspe-3.10/src/borg
  creating build/temp.powerpc-e500v2-linux-gnuspe-3.10/src/borg/algorithms
  creating build/temp.powerpc-e500v2-linux-gnuspe-3.10/src/borg/algorithms/msgpack
  /home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/bin/powerpc-e500v2-linux-gnuspe-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install//var/packages/borgbackup/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/lib -I /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install//var/packages/borgbackup/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/lib -I /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install//var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include/python3.10 -I/home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install//var/packages/borgbackup/target/include -fPIC -D__LITTLE_ENDIAN__=1 -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include -Isrc/borg/algorithms/xxh64/. -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/crossenv/cross/include -I/home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include/python3.10 -c src/borg/algorithms/msgpack/_packer.cpp -o build/temp.powerpc-e500v2-linux-gnuspe-3.10/src/borg/algorithms/msgpack/_packer.o
  In file included from /home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include/endian.h:36:0,
                   from /home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include/bits/waitstatus.h:64,
                   from /home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include/stdlib.h:42,
                   from /home/spksrc/borgbackup-udpate/spksrc/spk/borgbackup/work-qoriq-6.1/install/var/packages/borgbackup/target/include/python3.10/Python.h:34,
                   from src/borg/algorithms/msgpack/_packer.cpp:6:
  /home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/powerpc-e500v2-linux-gnuspe/sysroot/usr/include/bits/endian.h:26:4: error: #error Both BIG_ENDIAN and LITTLE_ENDIAN defined!
   #  error Both BIG_ENDIAN and LITTLE_ENDIAN defined!
      ^
  error: command '/home/spksrc/borgbackup-udpate/spksrc/toolchain/syno-qoriq-6.1/work/powerpc-e500v2-linux-gnuspe/bin/powerpc-e500v2-linux-gnuspe-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for borgbackup
  Running setup.py clean for borgbackup
Failed to build borgbackup
ERROR: Failed to build one or more wheels

```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Always, only fails on PPC.

#### <s>Include any warning/errors/backtraces from the system logs</s> Actual patch we use to circumvent this (a workaround upstream part of next release would be really great!)
https://github.com/SynoCommunity/spksrc/commit/72866f653fcff3f6862a417545a070f618c2d907#diff-7b228d5ca562f5bc3b0ebfbbe98d851ed882feab3721fbb04b57ad844256eb78
```
Disables pseudo logic made to enforce setting of macros which are actually already defined in corresponding headers.

--- setup.py
+++ setup.py
@@ -804,20 +804,16 @@ if not on_rtd:
                                                system_prefix=libb2_prefix, system=libb2_system,
                                                **crypto_ext_kwargs)

-    msgpack_endian = '__BIG_ENDIAN__' if (sys.byteorder == 'big') else '__LITTLE_ENDIAN__'
-    msgpack_macros = [(msgpack_endian, '1')]
     msgpack_packer_ext_kwargs = dict(
         sources=[msgpack_packer_source],
         include_dirs=include_dirs,
         library_dirs=library_dirs,
-        define_macros=msgpack_macros,
         language='c++',
     )
     msgpack_unpacker_ext_kwargs = dict(
         sources=[msgpack_unpacker_source],
         include_dirs=include_dirs,
         library_dirs=library_dirs,
-        define_macros=msgpack_macros,
         language='c++',
     )
```

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
thanks to everybody who helped with this, esp. @th0ma7 and @methane.

### CODE REVIEW

**Comment by klemensn** [comment]
This broke 1.1.18 on OpenBSD/sparc64, both 7.2-release and 7.2-CURRENT:

```
$ sysctl kern.version hw.byteorder
kern.version=OpenBSD 7.2-current (GENERIC.MP) #1541: Sun Nov 27 12:27:59 MST 2022
    deraadt@sparc64.openbsd.org:/usr/src/sys/arch/sparc64/compile/GENERIC.MP

hw.byteorder=4321
$ pkg_info -m | grep borg
borgbackup-1.1.18p1 deduplicating backup program
$ borg --version
1.1.18
```

Initialising a repository shows a message (unclear whether this is a warning, an error or perhaps an expected message):
```
$ borg init -e none ./test
Unknown integrity data version 0 in integrity.1
$ echo $?
0
```

Accessing it then fails:
```
$ borg list ./test
Unknown integrity data version 0 in integrity.1
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 4846, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 4778, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 164, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/local/lib/python3.10/site-packages/borg/helpers.py", line 389, in load
    raise ValueError('Invalid manifest version')
ValueError: Invalid manifest version

Platform: OpenBSD [redacted-hostname] 7.2 GENERIC.MP#1541 sparc64
Borg: 1.1.18  Python: CPython 3.10.8 msgpack: 0.5.6.+borg1
PID: 52736  CWD: /home/kn
sys.argv: ['/usr/local/bin/borg', 'list', './test']
SSH_ORIGINAL_COMMAND: None

```

Purging any local borg state (or trying a fresh OpenBSD installation) yields the same error:
```
$ rm -rf ./test ~/.cache/borg/ ~/.config/borg/
$ borg --debug init --encryption repokey ./test
using builtin fallback logging configuration
35 self tests completed in 0.95 seconds
Initializing repository at "test"
Encryption NOT enabled.
Use the "--encryption=repokey|keyfile" to enable encryption.
check_free_space: few segments, not requiring a full free segment
check_free_space: calculated working space for compact as 0 bytes
check_free_space: required bytes 169138, free bytes 2987718656
security: initializing unencrypted repository
security: saving state for c73159b5c1d40be48590ba5bacb3d1e80593fe8e2d8655776b0a7f6b1089e049 to /home/kn/.config/borg/security/c73159b5c1d40be48590ba5bacb3d1e80593fe8e2d8655776b0a7f6b1089e049
security: current location   /home/kn/test
security: key type           2
security: manifest timestamp 2022-12-02T17:57:32.805203
security: read previous location '/home/kn/test'
security: read manifest timestamp '2022-12-02T17:57:32.805203'
security: determined newest manifest timestamp as 2022-12-02T17:57:32.805203
security: repository checks ok, allowing access
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Unknown integrity data version 0 in integrity.1
Done.
security: saving state for c73159b5c1d40be48590ba5bacb3d1e80593fe8e2d8655776b0a7f6b1089e049 to /home/kn/.config/borg/security/c73159b5c1d40be48590ba5bacb3d1e80593fe8e2d8655776b0a7f6b1089e049
security: current location   /home/kn/test
security: key type           2
security: manifest timestamp 2022-12-02T17:57:32.805203
```

Trying to push into this repository via `borg create` over SSH would not show any error and just block endlessly.

1.2.2 is equally effected.

Reverting https://github.com/borgbackup/borg/pull/6149.patch on top of a pristine 1.1.18 build fixes it:
```
$ borg init -e none ./testrepo-1.1.18-pr6149_reverted
$ echo $?
0
$ borg list ./testrepo-1.1.18-pr6149_reverted
$ echo $?
0
```

**Comment by ThomasWaldmann** [comment]
@klemensn so that platform is big-endian?

**Comment by klemensn** [comment]
> @klemensn so that platform is big-endian?

Yes.
https://www.openbsd.org/sparc64.html
https://en.wikipedia.org/wiki/SPARC

**Comment by ThomasWaldmann** [comment]
about borg 1.1.x: it is pretty much out of maintenance, 1.1.18 was the last release.

about borg 1.2.x:

msgpack is not bundled any more (and thus not built as part of borg installation), but just listed as requirement, so pip will install it.

so, if you can reproduce the problem with a borg 1.2.x installation, that means that the msgpack python package is broken (like it is not being built correctly on sparc64) and a bug or better a PR should be filed there.

**Comment by ThomasWaldmann** [comment]
a general issue with BE platforms is the lack of testing infrastructure: I don't have any, so I can't test this.

ideally, there would be a vagrant box that could be used for testing, but I don't know of any.

**Comment by ThomasWaldmann** [comment]
@klemensn btw, my change here was only reflecting that change: https://github.com/msgpack/msgpack-python/pull/495/files

**Comment by ThomasWaldmann** [comment]
https://github.com/msgpack/msgpack-python/pull/513/files this is a more recent change, check it.

**Comment by klemensn** [comment]
> about borg 1.1.x: it is pretty much out of maintenance, 1.1.18 was the last release.

Good to know, thanks.

> about borg 1.2.x:
> 
> msgpack is not bundled any more (and thus not built as part of the borg build process), but just listed as requirement, so pip will install it.

I noticed that 1.1.x bundles msgpack while 1.2.x uses the system version, like the [OpenBSD port](https://github.com/openbsd/ports/blob/be89839edbfb6e0151652c7215bfe008ab87faf6/sysutils/borgbackup/1.2/Makefile#L6) does.

> so, if you can reproduce the problem with a borg 1.2.x installation, that means that the msgpack python package is broken (like it is not being built correctly on sparc64) and a bug or better a PR should be filed there.
> 
> https://github.com/msgpack/msgpack-python

The latest borgbackup-1.2.2p1 and borgbackup-1.1.18p1 packages on OpenBSD/sparc64 fail equally.

Just as an additional data point:  OpenBSD packages the latest [msgpack-python](https://github.com/openbsd/ports/blob/be89839edbfb6e0151652c7215bfe008ab87faf6/net/py-msgpack/Makefile#L3) as py3-msgpack-1.0.4p1v0 and its regression tests all pass:
https://gist.github.com/936496c1bea568a0f741ae9b3ec54d39

**Comment by ThomasWaldmann** [comment]
@klemensn can you uninstall the current msgpack you use with borg 1.2 and then:
```
pip install git+https://github.com/msgpack/msgpack-python.git@master
```
after that, install borg 1.2 and try it again (hopefully it take that msgpack and does not install a release over it)

**Comment by klemensn** [comment]
> @klemensn can you uninstall the current msgpack you use with borg 1.2 and then:
> 
> ```
> pip install git+https://github.com/msgpack/msgpack-python.git@master
> ```
> 
> after that, install borg 1.2 and try it again (hopefully it take that msgpack and does not install a release over it)

Thanks, I'll simply pull the upstream patches into the proper OpenBSD net/py-msgpack port/package and see if that fixes borg 1.2.2.

**Comment by klemensn** [comment]
> btw, borg checks the msgpack version and only accepts known-good versions (1.0.4 should be ok, but anything higher needs a change in borg also).

Yes, but cherry-picking such upstream commits into the port/package won't change its version (unless I crank more than what's known as `REVISION` (incremented for minor stuff like homepage/maintainer/etc. changes, then dropped again on new upstream versions).

**Comment by ThomasWaldmann** [comment]
ok, good. btw, if you like, make a PR against borg 1.1-maint with whatever fix you find.

likely there won't be another borg 1.1.x release, but at least the branch then has all the patches some other BE user might need.

**Comment by klemensn** [comment]
> ok, good. btw, if you like, make a PR against borg 1.1-maint with whatever fix you find.

Since reverting this PR fixes things on OpenBSD, I'm inclined to do just that for our port and call it a day. (after ensuring that other big-endian as well as little-endian architectures still work).

> likely there won't be another borg 1.1.x release, but at least the branch then has all the patches some other BE user might need.

I'll leave that to someone with enough time and energy to extract a proper fix out of this revert.

**Comment by ThomasWaldmann** [comment]
I don't think a revert of that changeset would be the right change for borg 1.1.x, considering that this changeset was done for a reason.

But rather the later change from msgpack master should be applied to the msgpack code we have bundled in borg 1.1.x:

https://patch-diff.githubusercontent.com/raw/msgpack/msgpack-python/pull/513.patch

**Comment by klemensn** [comment]
> I don't think a revert of that changeset would be the right change for borg 1.1.x, considering that this changeset was done for a reason.
> 
> But rather the later change from msgpack master should be applied to the msgpack code we have bundled in borg 1.1.x:
> 
> https://patch-diff.githubusercontent.com/raw/msgpack/msgpack-python/pull/513.patch

Right, that should also work.

**Comment by ThomasWaldmann** [comment]
Fixed by #7181 in 1.1-maint.

The fix for borg 1.2 and 2.0 will come automatically via a not-yet released msgpack-python 1.0.5.

**Pull request merged**
