### PR TITLE
Don't perform full Travis build on docs-only changes #2531

### PR DESCRIPTION
**Pull request by narendravardi**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
I restarted the 1 failing travis run (failure was unrelated to your changes).

After it completes, could you do some docs change to test your code?

**Comment by enkore** [comment]
Thank you!

**Comment by ThomasWaldmann** [comment]
Very useful change, saves time for us, saves load for travis. Thanks!

**Comment by narendravardi** [comment]
@enkore @ThomasWaldmann Thanks a lot!!! :)

Learnt a lot while losing this issue :)

**Comment by narendravardi** [comment]
@enkore just wondering how you were able to add commits to PR raised by me?

**Comment by enkore** [comment]
There is a check box in the right side bar on each PR:

> [x] Allow edits from maintainers.

It allows maintainers to push to your PR's branch.

**Comment by narendravardi** [comment]
@enkore yeah get it now. Thanks!

**Pull request merged**
