### PR TITLE
Rewrite zsh completion.

### PR DESCRIPTION
**Pull request by oxiedi**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
this needs to be reviewed by somebody who has experience with zsh completion.

@fantasya-pbem @SanskritFritz can you review it?

**Comment by SanskritFritz** [comment]
I have tested this and I must say I'm very impressed. This stuff is really awesome, please merge it. I've been struggling with the zsh completions for a while, now we'll have a complete solution.
Thanks @oxiedi !

**Comment by oxiedi** [comment]
@SanskritFritz thanks for testing. @ThomasWaldmann should I send a PR against `1.1-maint`?

**Comment by ThomasWaldmann** [comment]
@SanskritFritz can you also review the code? like looking at the code?

**Comment by SanskritFritz** [comment]
> @SanskritFritz can you also review the code? like looking at the code?
Sorry for not mentioning it, but I first looked at the code and only then tested it. To my best knowledge, there is no writing to anything related to borg, nor to any file, there are only read-only operations. The code is well structured, a bit complex for my level, but I would say by skimming trough it and grep'ing for any potentially dangerous borg commands that is is safe.

**Comment by ThomasWaldmann** [comment]
OK, so for the changelog, I need something better than "better zsh completion".

What specifically is better now? Can you change the commit comment?

**Comment by ThomasWaldmann** [comment]
@oxiedi commit looks better now, merging!

a PR against 1.1-maint would be welcome (assuming it applies to the code we have there and the change was tested well enough so it can go into next release).

**Comment by oxiedi** [comment]
Thanks! I thought you'd squash the commits.

**Comment by ThomasWaldmann** [comment]
Guess we still need a backport to 1.1-maint here?

**Comment by oxiedi** [comment]
Haven't we already done it in #5270?

**Comment by ThomasWaldmann** [comment]
Ah, right. So I just forgot to removed the tag back then. Did it right now.

Thanks for clarifying!

**Comment by SanskritFritz** [comment]
It was I who actually forgot to backport the fish changes.

**Comment by ThomasWaldmann** [comment]
@SanskritFritz what PR do you mean?

**Comment by SanskritFritz** [comment]
> @SanskritFritz what PR do you mean?

#5256

**Pull request merged**
