### PR TITLE
Backport: Add paragraph regarding cache security assumptions #4900

### PR DESCRIPTION
**Pull request by finefoot**
Backport, see #4900

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
thanks!

**Comment by finefoot** [comment]
@ThomasWaldmann 

I don't understand why the most recent commit for this pull request https://github.com/borgbackup/borg/pull/4930/commits/16b953b8ae5286343b4057f7c3ef45f755ea0f65 passed all tests and when you merged into 1.1-maint, that merge commit https://github.com/borgbackup/borg/commit/9f50c947d9d1aa61822592e4293044d974e9bd3d has a failed test. :thinking: 

I had a quick look at the most recent commits and https://github.com/borgbackup/borg/pull/4903 seems to have been merged into 1.1-maint with failed checks? Was that intentional? I'm not sure if that's even the reason, though. :man_shrugging:

**Comment by ThomasWaldmann** [comment]
```
flake8 runtests: commands[0] | flake8 src scripts conftest.py
src/borg/archiver.py:756:17: W503 line break before binary operator
src/borg/archiver.py:757:5: E129 visually indented line with same indent as next logical line
```

seems like this somehow crept in, but it is not due to your PR.

**Comment by ThomasWaldmann** [comment]
my fault, will fix...

**Comment by finefoot** [comment]
Yes, I understood so far. :) My questions were more like:

- How was it possible to merge #4903 with failed checks? I thought, failed tests would block merging.
- The flake8-erroneous code from #4903 was already part of this pull request #4930. So why didn't the tests for this pull request fail? Only after you merged this pull request, that commit showed failed tests.

**Comment by ThomasWaldmann** [comment]
They don't block and that's good. travis often fails even if the code is ok.

The flake8 tests are skipped for docs-only changes, that's why.

**Comment by finefoot** [comment]
:+1: Thanks for the explanations.

**Pull request merged**
