### PR TITLE
#5903 - Test/improve pull backup docs

### PR DESCRIPTION
**Pull request by fantasya-pbem**
Backport from master.

This is not improving the warnings etc. yet - just a fix for the broken menu indentation in 1.1-maint, which has been fixed already in master.

I will add more improvements in master branch, and finally backport them later.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Is this some specific PR you are backporting, can you point to it?

**Comment by fantasya-pbem** [comment]
No, I just merged master into 1.1-maint after I found that someone already fixed the headers in master.
It seems that the socat section has not been backported yet. In master the commit mentions #5150, but this issue does not exist (anymore?).

**Comment by ThomasWaldmann** [comment]
This is pretty much a backport of PR #5150 (no problem for me klicking on this, it exists), please mention that in this PR text or commit comment.

**Comment by ThomasWaldmann** [comment]
Alternatively, point to that:

document the socat pull mode described in https://github.com/borgbackup/borg/issues/900#issuecomment-499656737.

**Comment by fantasya-pbem** [comment]
Done, ok?

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
