### PR TITLE
add include patterns to --exclude lists

### PR DESCRIPTION
**Pull request by leo-b**
This PR adds include patterns as proposed in #1406.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
If we wanted to keep backwards compatibility we could add this as a new option, `--filter-from`. Not sure how important that is though.

**Comment by ThomasWaldmann** [comment]
btw, flake8 checker is unhappy.

**Comment by leo-b** [comment]
Sorry, forgot the last whitespace fixing commit. :-)

**Comment by enkore** [comment]
Superseded by #1971

**Pull request closed without merging**
