### PR TITLE
[WIP] Optimize argparse args to give consistent messages

### PR DESCRIPTION
**Pull request by qua-bla**
This PR makes error messages for missing arguments more consistent across borg commands. Also the help file gets a bit more instructive.

**Old Behavior**

    borg upgrade
    usage: borg upgrade [-h] [-v] [--debug] [--lock-wait N] [--show-rc]
                        [--no-files-cache] [--umask M] [--remote-path PATH] [-p]
                        [-n] [-i]
                        [REPOSITORY]
    borg upgrade: error: argument REPOSITORY: Invalid location format: ""

**New Behavior**

    borg upgrade
    usage: borg upgrade [-h] [-v] [--debug] [--lock-wait N] [--show-rc]
                        [--no-files-cache] [--umask M] [--remote-path PATH] [-p]
                        [-n] [-i]
                        REPOSITORY
    borg upgrade: error: the following arguments are required: REPOSITORY

----

    borg upgrade ""
    usage: borg upgrade [-h] [-v] [--debug] [--lock-wait N] [--show-rc]
                        [--no-files-cache] [--umask M] [--remote-path PATH] [-p]
                        [-n] [-i]
                        REPOSITORY
    borg upgrade: error: argument REPOSITORY: Invalid location format: ""

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Did you consider this scenario?

```
export BORG_REPO=/some/path
borg list
```
That should work and list the archives in the repo at /some/path.

**Comment by qua-bla** [comment]
Was not aware of that feature. Suggestion

1. I create another PR that adds test cases that let this PR fail.
2. If you are happy with the vague direction of #315 I will write a proposal that fixes configs, env vars and this PR altogether.

**Comment by ThomasWaldmann** [comment]
Yes, a test for this would be fine. I don't see how this is related to #315, so please keep it separate.

**Comment by ThomasWaldmann** [comment]
So, if I understood correctly, this PR shall not be applied nor get updated, but rather replaced by that scenario-testing PR. Thus I am closing this one now.

**Pull request closed without merging**
