### PR TITLE
Timestamps with timezones

### LINKED ISSUE #2368: add timezone to datetime display format
As for now, dates and times in all places, especially in `borg info` and `borg list` are in the local timezone. But borg can be used remote, and some service/scripts may be around borg, and there is json api in the next version, so it will be good to see time in the full format with the Z sign and timezone, at least as on option to the current behavior.

### LINKED ISSUE #2376: JSON: Use a more standard, timezone-aware format date time format
Cf. #2368

Can be implemented similar to the output-type dependent file-size formatting.

### LINKED ISSUE #4724: {utcnow} output isn't correct
Severity: Minor

#### Your borg version (borg -V).
borg 1.1.10

#### Operating system (distribution) and version.
Debian Stretch (9) + backports

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
ARCH={hostname}-{utcnow}Z
borg create --verbose --exclude-caches --show-rc --filter AME --stats --checkpoint-interval 600 --compression auto,zlib,6 --exclude-from /usr/local/sbin/BORG_EXCLUSIONS.list ::$ARCH 
```

## Describe the problem you're observing.
Using {utcnow} alone doesn't print the final 'Z' char => {utcnow}Z
which from the ISO-8601 standard is abnormal.

## Wish
The regular ISO-8601 UTC string would also be better as a default: YYYYMMDDTHHMMSSZ because it is more compact.

Jean-Yves

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
fixes #2376
fixes #4724 (no Z for UTC, but +00:00)
fixes #2368

ideas:
- the aware datetime object of the local time with the local timezone carries the most information
- local time is what users expect to see / use
- in an international context, the tz part might be interesting. also it makes the specific point in time very clear.
- we can always compute utc from the aware tz
- some not user facing places like the manifest timestamp or the transaction log can be with utc timestamps
- keep now and utcnow placeholder as is, users who like the tzoffset part can just do custom formatting with %z
- python/C wart: strftime %z generates +HHMM, (from)isoformat uses +HH:MM
- pruning happens in local timezone currently

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
```
% borg create 'arch-now-{now}' src
% borg create 'arch-now-fmt-{now:%Y-%m-%d-%H:%M:%S%z}' src
% borg create 'arch-utcnow-{utcnow}' src                  
% borg create 'arch-utcnow-fmt-{utcnow:%Y-%m-%d-%H:%M:%S%z}' src
% borg create 'arch-ts-now-fmt-{now:%Y-%m-%d-%H:%M:%S%z}' src --timestamp=2022-12-31-23:59:59.123456+09:30

% borg rlist                                                                                              
arch-now-2022-08-12T21:18:48         Fri, 2022-08-12 21:18:48 +0200 [027e0be35169b67d4691e6db0c085088459e322343e9fce4cf3ac33f95db6ebc]
arch-now-fmt-2022-08-12-21:19:37+0200 Fri, 2022-08-12 21:19:37 +0200 [02a13fe9556101085d917ff79d1d475c05a31e57c696345cda62a3298a1bc0a5]
arch-utcnow-2022-08-12T19:19:49      Fri, 2022-08-12 21:19:49 +0200 [d8ccdc90f3149dccdfd1cac224a87327d2afa843ca3776dbfb368b4d6d3cc37c]
arch-utcnow-fmt-2022-08-12-19:20:04+0000 Fri, 2022-08-12 21:20:04 +0200 [287a8c2dbd8c7cf5719d384587f5781c9ca3404f653a9296dd580bee4f0d4561]
arch-ts-now-fmt-2022-08-12-21:21:31+0200 Sat, 2022-12-31 23:59:59 +0930 [8ed41d1be8f9ec2e503916a2c6ce6d431a0ca8dbbae7eed7c4006114c3880648]

% borg rlist --json
{
    "archives": [
        {
            "archive": "arch-now-2022-08-12T21:18:48",
            "barchive": "arch-now-2022-08-12T21:18:48",
            "id": "027e0be35169b67d4691e6db0c085088459e322343e9fce4cf3ac33f95db6ebc",
            "name": "arch-now-2022-08-12T21:18:48",
            "start": "2022-08-12T21:18:48.588072+02:00",
            "time": "2022-08-12T21:18:48.588072+02:00"
        },
        {
            "archive": "arch-now-fmt-2022-08-12-21:19:37+0200",
            "barchive": "arch-now-fmt-2022-08-12-21:19:37+0200",
            "id": "02a13fe9556101085d917ff79d1d475c05a31e57c696345cda62a3298a1bc0a5",
            "name": "arch-now-fmt-2022-08-12-21:19:37+0200",
            "start": "2022-08-12T21:19:37.878526+02:00",
            "time": "2022-08-12T21:19:37.878526+02:00"
        },
        {
            "archive": "arch-utcnow-2022-08-12T19:19:49",
            "barchive": "arch-utcnow-2022-08-12T19:19:49",
            "id": "d8ccdc90f3149dccdfd1cac224a87327d2afa843ca3776dbfb368b4d6d3cc37c",
            "name": "arch-utcnow-2022-08-12T19:19:49",
            "start": "2022-08-12T21:19:49.467781+02:00",
            "time": "2022-08-12T21:19:49.467781+02:00"
        },
        {
            "archive": "arch-utcnow-fmt-2022-08-12-19:20:04+0000",
            "barchive": "arch-utcnow-fmt-2022-08-12-19:20:04+0000",
            "id": "287a8c2dbd8c7cf5719d384587f5781c9ca3404f653a9296dd580bee4f0d4561",
            "name": "arch-utcnow-fmt-2022-08-12-19:20:04+0000",
            "start": "2022-08-12T21:20:04.848551+02:00",
            "time": "2022-08-12T21:20:04.848551+02:00"
        },
        {
            "archive": "arch-ts-now-fmt-2022-08-12-21:21:31+0200",
            "barchive": "arch-ts-now-fmt-2022-08-12-21:21:31+0200",
            "id": "8ed41d1be8f9ec2e503916a2c6ce6d431a0ca8dbbae7eed7c4006114c3880648",
            "name": "arch-ts-now-fmt-2022-08-12-21:21:31+0200",
            "start": "2022-12-31T23:59:59.123456+09:30",
            "time": "2022-12-31T23:59:59.123456+09:30"
        }
    ],
    "encryption": {
        "mode": "none"
    },
    "repository": {
        "id": "beaab953aa66719f4501814f6554ee3daf6e2387471c834704eb709a95893c0b",
        "last_modified": "2022-08-12T19:21:31.975669+00:00",
        "location": "/tmp/repo200ts"
    }
}

% borg info --json 
{
    "archives": [
        {
            "chunker_params": [
                "buzhash",
                19,
                23,
                21,
                4095
            ],
            "command_line": [
                "/Users/tw/w/borg-env/bin/borg",
                "create",
                "arch-now-{now}",
                "src"
            ],
            "comment": "",
            "duration": 0.074928,
            "end": "2022-08-12T21:18:48.663000+02:00",
            "hostname": "mba2020",
            "id": "027e0be35169b67d4691e6db0c085088459e322343e9fce4cf3ac33f95db6ebc",
            "name": "arch-now-2022-08-12T21:18:48",
            "start": "2022-08-12T21:18:48.588072+02:00",
            "stats": {
                "deduplicated_size": 519,
                "nfiles": 303,
                "original_size": 13795516
            },
            "username": "tw"
        },
        {
            "chunker_params": [
                "buzhash",
                19,
                23,
                21,
                4095
            ],
            "command_line": [
                "/Users/tw/w/borg-env/bin/borg",
                "create",
                "arch-now-fmt-{now:%Y-%m-%d-%H:%M:%S%z}",
                "src"
            ],
            "comment": "",
            "duration": 0.016056,
            "end": "2022-08-12T21:19:37.894582+02:00",
            "hostname": "mba2020",
            "id": "02a13fe9556101085d917ff79d1d475c05a31e57c696345cda62a3298a1bc0a5",
            "name": "arch-now-fmt-2022-08-12-21:19:37+0200",
            "start": "2022-08-12T21:19:37.878526+02:00",
            "stats": {
                "deduplicated_size": 554,
                "nfiles": 303,
                "original_size": 13795516
            },
            "username": "tw"
        },
        {
            "chunker_params": [
                "buzhash",
                19,
                23,
                21,
                4095
            ],
            "command_line": [
                "/Users/tw/w/borg-env/bin/borg",
                "create",
                "arch-utcnow-{utcnow}",
                "src"
            ],
            "comment": "",
            "duration": 0.016139,
            "end": "2022-08-12T21:19:49.483920+02:00",
            "hostname": "mba2020",
            "id": "d8ccdc90f3149dccdfd1cac224a87327d2afa843ca3776dbfb368b4d6d3cc37c",
            "name": "arch-utcnow-2022-08-12T19:19:49",
            "start": "2022-08-12T21:19:49.467781+02:00",
            "stats": {
                "deduplicated_size": 528,
                "nfiles": 303,
                "original_size": 13795516
            },
            "username": "tw"
        },
        {
            "chunker_params": [
                "buzhash",
                19,
                23,
                21,
                4095
            ],
            "command_line": [
                "/Users/tw/w/borg-env/bin/borg",
                "create",
                "arch-utcnow-fmt-{utcnow:%Y-%m-%d-%H:%M:%S%z}",
                "src"
            ],
            "comment": "",
            "duration": 0.016133,
            "end": "2022-08-12T21:20:04.864684+02:00",
            "hostname": "mba2020",
            "id": "287a8c2dbd8c7cf5719d384587f5781c9ca3404f653a9296dd580bee4f0d4561",
            "name": "arch-utcnow-fmt-2022-08-12-19:20:04+0000",
            "start": "2022-08-12T21:20:04.848551+02:00",
            "stats": {
                "deduplicated_size": 563,
                "nfiles": 303,
                "original_size": 13795516
            },
            "username": "tw"
        },
        {
            "chunker_params": [
                "buzhash",
                19,
                23,
                21,
                4095
            ],
            "command_line": [
                "/Users/tw/w/borg-env/bin/borg",
                "create",
                "arch-ts-now-fmt-{now:%Y-%m-%d-%H:%M:%S%z}",
                "src",
                "--timestamp=2022-12-31-23:59:59.123456+09:30"
            ],
            "comment": "",
            "duration": 0.016045,
            "end": "2022-12-31T23:59:59.139501+09:30",
            "hostname": "mba2020",
            "id": "8ed41d1be8f9ec2e503916a2c6ce6d431a0ca8dbbae7eed7c4006114c3880648",
            "name": "arch-ts-now-fmt-2022-08-12-21:21:31+0200",
            "start": "2022-12-31T23:59:59.123456+09:30",
            "stats": {
                "deduplicated_size": 606,
                "nfiles": 303,
                "original_size": 13795516
            },
            "username": "tw"
        }
    ],
    "cache": {
        "path": "/Users/tw/.cache/borg/beaab953aa66719f4501814f6554ee3daf6e2387471c834704eb709a95893c0b",
        "stats": {
            "total_chunks": 1530,
            "total_size": 68977580,
            "total_unique_chunks": 309,
            "unique_size": 13859839
        }
    },
    "encryption": {
        "mode": "none"
    },
    "repository": {
        "id": "beaab953aa66719f4501814f6554ee3daf6e2387471c834704eb709a95893c0b",
        "last_modified": "2022-08-12T19:21:31.975669+00:00",
        "location": "/tmp/repo200ts"
    }
}
```

**Comment by ThomasWaldmann** [comment]
@sophie-h @m3nu have a look ^^^

**Comment by ThomasWaldmann** [comment]
fixed with_timestamp now, but the placeholder replacement is still broken for the archive name when `--timestamp` is given.

**Comment by m3nu** [comment]
In Vorta, we show local time. Local to the source machine (could be in another TZ, like UTC for many servers).

So this commit will still show local time, but have UTC or time zone data, if needed. I think that's a good improvement.

**Comment by ThomasWaldmann** [comment]
@m3nu i have removed most transformations:
- stored archive timestamps are localtime with timezone (of the machine creating the backup)
- when listing / json dumping stuff, it just shows 1:1 whatever is stored

makes the code simpler and avoids information loss (like when transforming a local time to utc, the original tz info is lost).

**Comment by ThomasWaldmann** [comment]
Hmm, guess we could make the code even a bit simpler by changing the default tz for `--timestamp` (if no timezone offset `(+|-)HH:MM` is given) from utc to local timezone.

**Comment by sophie-h** [comment]
> Hmm, guess we could make the code even a bit simpler by changing the default tz for `--timestamp` (if no timezone offset `(+|-)HH:MM` is given) from utc to local timezone.

:+1: Passing it as UTC by default sounds somewhat unintuitive anyways :)

**Pull request merged**
