### PR TITLE
repo commands renamed r* -> repo-*

### LINKED ISSUE #8292: borg2 commands: use repo-*, not r*
https://github.com/borgbackup/borg/discussions/7647 as discussed / voted there (voting is / will be open until this ticket is close, so in case you missed it, you can still vote there).

Current state of repo-level commands:
```
borg rcreate
borg rlist
borg rinfo
borg rdelete
...
```

Change to:
```
borg repocreate
borg repolist
borg repoinfo
borg repodelete
...
```

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Fixes #8292.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
While working on this, I thought we maybe should rename some other commands also.

## disambiguation / split

The initial reason to have `*` and `repo-*` commands was to split and disambiguate them, e.g. `delete` deletes archive(s), while `repo-delete` deletes a repository. This makes the argparser and docs a lot easier, if 2 rather different commands are not mixed into 1 (as it was in borg 1.x).

## scope
But the command name could also describe on what scope the command works on. Full repo vs. archive(s).

## compact

Thus `compact` maybe should be rather `repo-compact` (same as we already have `repo-compress` although there was no disambiguation needed for that).

## check

This is currently a mixed-scope command, there is the --repository-only part doing the full repo low-level check and the --archives-only higher level check. By default it runs both of them.

## prune

Difficult. Potentially works on the full repo, but rules rather apply on the archive level.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt @witten @m3nu @sophie-h ^

**Comment by RonnyPfannschmidt** [comment]
I'd not give prune/check prefixes for now

The repo only/Archive only versions could be turned into separate prefixed commands 

Prune is kind of a repo wide operation that's specifically targeting the full list of archives

**Comment by ThomasWaldmann** [comment]
Still need feedback on `borg compact` vs. `borg repo-compact`.

That works on full repo scope, but it's doing the garbage collection by looking at all archives.

**Comment by ThomasWaldmann** [comment]
Will merge this soon to avoid conflicts. Can work on compact in another PR...

**Comment by m3nu** [comment]
> Still need feedback on `borg compact` vs. `borg repo-compact`.

When in doubt and since this operates on both, I'd keep the old version of `borg compact`.

**Comment by witten** [comment]
I second keeping `borg compact` as-is, unless you're planning on splitting it into two separate subcommands, one for repos and one for archives.

**Comment by ThomasWaldmann** [comment]
@witten there is nothing to compact "in archives".

It just needs to analyze the archives to know what chunks are in use, so it can delete those which aren't used. It also computes some stats as a side effect (-v).

**Pull request merged**
