### PR TITLE
Use HTTPS everywhere (mechanical edit using util from https-everywhere)

### PR DESCRIPTION
**Pull request by ypid**
Ref: https://github.com/EFForg/https-everywhere/tree/master/utils/rewriter

```Shell
~/src/EFForg/https-everywhere/utils/rewriter/rewriter.js .
```

A few changes were reset/fixed manually before the commit.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for the PR!

There are 2 issues (at least):
- tests failing, see github CI post.
- at least one link is obviously wrong, so it seems you need to verify them again.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/5576/checks?check_run_id=1585818838#step:9:2960 still failing.h

**Comment by ypid** [comment]
I had to get familiar with GitHub actions first. Fixed. Seems the only failing test is "codecov/project — 82.97% (-0.03%)". I think it counts the one newline I added ;-) Can you ignore this?

"CI / pytest (ubuntu-20.04, 3.7, py37-fuse2)" and "CI / pytest (ubuntu-20.04, 3.6, py36-fuse2)" seem flaky. I already rerun one and one or the other failed.

**Comment by ThomasWaldmann** [comment]
thanks! do you want to backport this to 1.1-maint branch?

**Pull request merged**
