### PR TITLE
hashindex_compact: fix eval order (check idx before use), fixes #5899

### LINKED ISSUE #5899: Segfault with borg 1.1.16 on Alpine Linux
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.16

#### Operating system (distribution) and version.
Alpine Linux "edge" (rolling release)

#### Hardware / network configuration, and filesystems used.

* Borgbackup metadata (cache and configuration) is in a btrfs partition on the host machine
* Data to back up (LXC/LXD container metadata and filesystems) is ext4 on Ceph RBD block devices 

#### How much data is handled by borg?
Original data: ~ 500GB (filesystems and metadata of ~20 containers)
After deduplication: ~10GB per backup run in 20 archives (1 archive per container)
Total (all archives): ~3TB

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I use borgbackup to take daily backups of LXC/LXD containers on a dedicated container host. Each backup run calls 
```
borg create "$ARCHIVE_URL::$CONTAINER-{now:%Y-%m-%dT%H:%M:%S}" . --stats
```
in the toplevel directory of a snapshot of the container file system (snapshots are created outside of borgbackup using Ceph tools). `$ARCHIVE_URL` is the SSH URL of an archive on a remote borgbackup server, and `$CONTAINER` is the container ID.

The first call to `borg create` in this backup run fails with a segfault on about every second run (see below for the backtrace). 

The subsequent calls to back up different containers in the same run have had no errors so far. 

The segfault is not specific to one container: If I change the order of the containers for backup I get the same error for a different container - but always for the first `borg create` call of a backup run.

#### Include any warning/errors/backtraces from the system logs

The crash occurs always in the same line in python code:

```
Fatal Python error: Segmentation fault

Current thread 0x00007fe4c6126b48 (most recent call first):
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 740 in write_archive_index
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 736 in fetch_and_build_idx
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 824 in create_master_idx
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 870 in sync
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 474 in __init__
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 379 in local
  File "/usr/lib/python3.9/site-packages/borg/cache.py", line 387 in __new__
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 586 in do_create
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 177 in wrapper
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4622 in run
  File "/usr/lib/python3.9/site-packages/borg/archiver.py", line 4690 in main
  File "/usr/bin/borg", line 33 in <module>
Segmentation fault
```
Line 740 in /usr/lib/python3.9/site-packages/borg/cache.py is simply
```
compact_chunks_archive_saved_space += chunk_idx.compact()
```
where `chunk_idx` is an instance of `ChunkIndex`, which is implemeted in C as far as I can see. 
So I suspect a bug in  `chunk_idx.compact()`

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
also: fix "off by one" comment

thanks to https://github.com/tomaszduda23 for debugging and finding this.

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Do you still want the ports? 😏

**Comment by ThomasWaldmann** [comment]
@KN4CK3R they are already done, see closed PRs.

**Comment by KN4CK3R** [comment]
Ah, I was waiting for this PR to get closed. 👍

**Comment by ThomasWaldmann** [comment]
Well, "merged" means "done". "Closed" (for a PR) would mean "rejected with unmerged changes".

**Pull request merged**
