### PR TITLE
Backports (7)

### LINKED ISSUE #2799: do 1.0-maint backports (7)
https://github.com/borgbackup/borg/issues?utf8=%E2%9C%93&q=label%3Abackport%2F1.0-maint%20

do 3 simple/small or 1 bigger/complex backport from there.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/46895018-do-1-0-maint-backports-7)

### PR DESCRIPTION
**Pull request by milkey-mouse**
First time doing backports, hopefully I did them right 🤞

Fixes #2799

### CODE REVIEW

**Comment by milkey-mouse** [comment]
- #2794
- #2790
- #2758

**Comment by enkore** [comment]
Looks good. I think you can drop 35a1e7f, since it isn't used.

**Comment by milkey-mouse** [comment]
OK, I deleted that commit

**Comment by ThomasWaldmann** [comment]
thanks!

**Pull request merged**
