### PR TITLE
Backport:  safe_unlink (was: truncate_and_unlink)

### PR DESCRIPTION
**Pull request by hexagonrecursion**
This is a backport of #6301 and #6311

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
- [ ] TODO: backport d38e1de918dffd9e1f85093bc89946f4644e4cc9

**Comment by ThomasWaldmann** [comment]
can you please do a `git rebase -i` and collapse your test commits into one?

**Comment by hexagonrecursion** [comment]
> can you please do a `git rebase -i` and collapse your test commits into one?

Like this?

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
