### PR TITLE
fix bullet-list links

### PR DESCRIPTION
**Pull request by abebeos**
Add refs

(note: your information "no need for this" within https://github.com/borgbackup/borg/pull/7423#discussion_r1132297255 was wrong)

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
No, my comment was not wrong. I did not want you to add a lot of links to special cases (like ubuntu), but just link to the main section headline (for all OSes) - and for that one the neeeded label was already present.

Afterwards, you then added a directory of OSes below that headline (which I didn't like much, but found acceptable still as it is just at one close-by place vs. 2 distant places of your previous approach). So you either have to remove that or check whether it works by magic via the headlines.

**Comment by abebeos** [comment]
> No, my comment was not wrong. I did not want you to add a lot of links to special cases (like ubuntu), but just link to the main section headline (for all OSes) - and for that one the neeeded label was already present.

Your comment was wrong, additionally you ignored my clarifying question.

Next time, when you comment, focus on the item you comment. If your comment is in a greater context/scope, you need to mention it. Reviewing is not a guess-work.

> So you either have to remove that or check whether it works by magic via the headlines or add the labels as you did here.

I checked already with the generated site, it does NOT work "by magic".

(this change is necessary, the current merged version has non-links)

**Comment by abebeos** [comment]
> and for that one the neeeded label was already present.

It was not.

**Comment by abebeos** [comment]
> or add the labels as you did here.

As you do not like redundancy and duplication (similar to me) : 

Possible Follow-up:

You can add a new documentation issue that would focus to remove the many `.. _my-manual-anchor:` from the doc sources (the effort is beyond one middle doc bounty - possibly 2 or 3 or even more), something like:

### Automate headline anchor/ref creation

* ensure that every headlines generates as `:ref:` target
* remove redundant `.. _my-manual-anchor:`
* verify the generated anchors, resolve duplicates
* do some tests with the resulting docs

**Comment by ThomasWaldmann** [comment]
OK, it seems like sphinx is magically generating HTML anchors for each headline, but not reST targets (yet)?

Maybe we do not yet have that enabled, check this:

https://stackoverflow.com/questions/18632781/how-to-make-an-internal-link-to-a-heading-in-sphinx-restructuredtext-without-cre

An alternative solution would be to just remove that "directory of OSes" you added. Then you do not need all that manual linking. Each OS has an own headline that is pretty simple to discover without the directory you have added.

**Comment by abebeos** [comment]
> Each OS has an own headline

It has not, and I'll not check any more documents you point me to.

You're becoming rude.

The PRs are functional and finished. You can't expect that this continues endlessly in context of a $30 bounty, just because you can't accept that duplication/redundancy is sometimes a necessity.

I mean you have duplication within docs, doesn't this freak you out?

As said here https://github.com/borgbackup/borg/pull/7431#issuecomment-1464943085, file a new issue to get rid of all the link redundancy already existing in your doc sources (independent of my links).

Just unbelievable all this.

**Comment by abebeos** [comment]
(please note that I'll not further comment on this. Enough is enough, get over your strangeness, or apply it at least consistently over your existent code-base, with the result that you'll go nuts from all the redundancy/duplication)

**Comment by ThomasWaldmann** [comment]
bye!

**Comment by abebeos** [comment]
> bye!

Bye you delusional thief.

**Comment by abebeos** [comment]
> > bye!
> 
> Bye you delusional thief.

Correction: NOT a thief. See https://github.com/borgbackup/borg/issues/7398#issuecomment-1465124740

**Comment by abebeos** [comment]
> Each OS has an own headline that is pretty simple to discover without the directory you have added.

Clarification: You talked about manual discovery.

I talked about the simplified discovery via headline anchors.

Simplified, as things need to be for a good UX.

**Pull request closed without merging**
