### PR TITLE
Automate asciinema screencasts

### LINKED ISSUE #2909: asciinema screencasts
we have new asciinema screencasts in #2835, but I am not totally happy with them.

there is just too much whooshing, blinking and attribute usage going on.
stuff comes onto screen at very different paces. a bit slow (typed live), then whoosh a lot of fast input (not typed live, but just recalled).
this is something that will affect / irritate quite some viewers of these.

also, due to the same root causes, there is lots of stuff in the json that makes it hard to edit (e.g. to fix small typos or other minor stuff), like ansi colour/attribute sequences, temporary stuff (that was neither typed nor output by borg), ...

so I propose these rules for the next iteration of asciinema screencasts:
- in general:

  - no fancy shell tricks
  - no fancy shell styling
  - no shell extensions (or powerful shells that have lots of stuff built-in)
  - just plain sh / bash

- no stuff pre-entered in the shell history that just gets recalled by some key combination
- everything except trivial and short shell completion (e.g. of a path) must be typed "live", char by char
- no or only minimal colour / attribute usage in output, acceptable would be:

  - one full-line color for comment lines
  - a coloured prompt for input lines or one full-line colour for input
  - one full-line colour for all output
  - all colours must have good contrast to background (e.g. no dark grey on black)
  - no intra-line syntax highlighting

- no underlined stuff (e.g. no automatically underlined directory names)
- no cursor up to recall anything except the last 1 or 2 commands
- no edits of recalled stuff except very few characters
- no typing in of something and then erasing all of it again with backspace
- nothing showing up temporarily below the line where input happens while input happens (e.g. no shell input completion offering some options)
- enter your sudo password before you start the recording, so it won't ask while recording

### PR DESCRIPTION
**Pull request by hexagonrecursion**
Fix #2909

Manually generating asciinema screencasts is:
1. Tedious
2. Time consuming
2. Inconsistent
3. Error prone
4. Has to be done from scratch every time you want to change something

This is my attempt to automate the process

TODO:
* [x] automate the advanced usage screencast
* [x] automate the installation screencast
* [x] dynamically echo the current borg version
* [ ] ~add color (if you want it)~
* [x] add a more convincing emulation of data-to-backup
* [x] fake a remote system via /etc/hosts
* [x] figure out how to fake a remote system. I think docker-compose might help me here
    This is needed to run the following command from the basic usage example:
    ```
    borg init --encryption=repokey borgdemo@remoteserver.example:./demo
    ```
    I have figured it out: map remoteserver.example to localhost in /etc/hosts

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
I have found a good way to implement this - isolate the example form the host by using a docker container. This way I get a disposable system I can freely ~butcher~ modify as needed to make the examples work.

**Comment by ThomasWaldmann** [comment]
Hmm, I usually don't use docker. Just ssh to localhost to simulate a "remote" repo?

**Comment by hexagonrecursion** [comment]
> I usually don't use docker

I have been in this boat too, but now I am quite comfortable with it and the power is worth the learning curve.

**Comment by ThomasWaldmann** [comment]
I use VMs and vagrant (for borg mainly for automated platform testing).

**Comment by hexagonrecursion** [comment]
I guess I'll have to learn vagrant then.

**Comment by hexagonrecursion** [comment]
@ThomasWaldmann I have found some time to work on this. Reimplemented installation and basic usage via Vagrant. Take a look.

**Comment by ThomasWaldmann** [comment]
Thanks! Will do, but likely after 1.2.0 release.

**Comment by hexagonrecursion** [comment]
This should be ready now.

**Comment by ThomasWaldmann** [comment]
Found / fixed some typos (squashed the fixes into the changeset where they were introduced).

**Comment by ThomasWaldmann** [comment]
Next thing I will try is to adapt this for borg2 (we definitely need new screencasts there as a lot of stuff changed).

If I succeed, shall I just push the stuff to your branch? Guess you'ld need to open a new PR then against the borg2 branch.

**Comment by rugk** [comment]
Great thing and great idea to automate that! BTW, are the (new) screencasts already live? As https://www.borgbackup.org/demo.html still shows the old ones…

**Comment by ThomasWaldmann** [comment]
@rugk https://github.com/borgbackup/borgbackup.github.io/tree/source/_assets there is the old stuff still.

guess one could have a look first at old vs. new and then, if all is ok, update the files there. PRs welcome.

**Pull request merged**
