### PR TITLE
Disable unneeded SSH features in authorized_keys example for security.

### PR DESCRIPTION
**Pull request by rot13**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
looks ok, did you test it?

**Comment by rot13** [comment]
Yes, that's what I use personally.

I also noticed another example in docs/deployment.rst, which has "no-port-forwarding,no-X11-forwarding,no-pty" but is missing "no-agent-forwarding,no-user-rc".

The "borg serve" command is not supposed to make SSH connections to other servers, so agent forwarding seems useless.

Disabling ~/.ssh/rc execution is a bit paranoid, since an attacker who is able to modify this file to run commands will usually be able to modify ~/.ssh/authorized_keys too, but this feature seems to be rarely used so disabling it shouldn't be a problem. It may still protect the user in some rare circumstances. There may be, for example, a limit of how many bytes the attacker can control, thus limiting file names to shorter ones.

**Comment by ThomasWaldmann** [comment]
ok. would you fix the other place also?

**Comment by rot13** [comment]
I think that's all, grepping for 'command=' finds no more instances. The Ansible config change is untested. I see no reason why it wouldn't work though.

**Pull request merged**
