### PR TITLE
Add hashtable stress test (backport to 1.2-maint)

### PR DESCRIPTION
**Pull request by snsmac**
#7324

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@snsmac thanks for the backport - did you run the test with BORG_TESTS_SLOW enabled?

**Comment by snsmac** [comment]
> @snsmac thanks for the backport - did you run the test with BORG_TESTS_SLOW enabled?

I will do that now

**Comment by snsmac** [comment]
@ThomasWaldmann 
The test fails for me:
```
(venv) xxx@xxx:~/src/borg$ BORG_TESTS_SLOW=1 pytest -v src/borg/testsuite/hashindex_stress.py  
========================================================================================================= test session starts ==========================================================================================================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0 -- /home/xxx/src/borg/venv/bin/python
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Tests enabled: BSD flags, root, symlinks, hardlinks, atime/mtime, modes
Tests disabled: fuse2, fuse3
rootdir: /home/xxx/src/borg, configfile: setup.cfg
plugins: xdist-3.2.0, cov-4.0.0, benchmark-4.0.0
collected 1 item                                                                                                                                                                                                                       

src/borg/testsuite/hashindex_stress.py::test_hashindex_stress FAILED                                                                                                                                                             [100%]

=============================================================================================================== FAILURES ===============================================================================================================
________________________________________________________________________________________________________ test_hashindex_stress _________________________________________________________________________________________________________

    @pytest.mark.skipif("BORG_TESTS_SLOW" not in os.environ, reason="slow tests not enabled, use BORG_TESTS_SLOW=1")
    def test_hashindex_stress():
        """checks if the hashtable behaves as expected
    
        This can be used in _hashindex.c before running this test to provoke more collisions (don't forget to compile):
        #define HASH_MAX_LOAD .99
        #define HASH_MAX_EFF_LOAD .999
        """
        ENTRIES = 10000
        LOOPS = 1000
        idx = NSIndex()
        kv = {}
        for i in range(LOOPS):
            # put some entries
            for j in range(ENTRIES):
                k = random.randbytes(32)
                v = random.randint(0, NSIndex.MAX_VALUE - 1)
                idx[k] = (v, v, v)
                kv[k] = v
            # check and delete a random amount of entries
            delete_keys = random.sample(list(kv), k=random.randint(0, len(kv)))
            for k in delete_keys:
                v = kv.pop(k)
>               assert idx.pop(k) == (v, v, v)
E               assert (2697915084, 2697915084) == (2697915084, ...4, 2697915084)
E                 Right contains one more item: 2697915084
E                 Full diff:
E                 - (2697915084, 2697915084, 2697915084)
E                 ?              ------------
E                 + (2697915084, 2697915084)

src/borg/testsuite/hashindex_stress.py:32: AssertionError
======================================================================================================= short test summary info ========================================================================================================
FAILED src/borg/testsuite/hashindex_stress.py::test_hashindex_stress - assert (2697915084, 2697915084) == (2697915084, ...4, 2697915084)
========================================================================================================== 1 failed in 0.06s ==```

**Comment by ThomasWaldmann** [comment]
The `NSINdex` (repo index) in borg < 2 has only 2-tuples as values (not 3-tuples as in borg 2).

**Comment by snsmac** [comment]
I updated the test and it passes now

**Pull request merged**
