### PR TITLE
borg info REPO

### LINKED ISSUE #1326: Implement `borg info REPOSITORY`
I would love a way to get statistics for a repository without having to run an action such as `prune` (my current method.

```
user@host:~$ borg info /path/to/repo
------------------------------------------------------------------------------
Number of archives: 12
Number of files: 129
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Repository:                159.66 GB             84.00 GB             81.53 GB

                       Unique chunks         Total chunks
Chunk index:                  207204               242000
------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
fixes #1326 

there is currently a bit overlap:

borg info archive: archive info +  archive stats + repo stats
borg info repo: repo stats only

So, remove repo stats from "borg info ARCHIVE"?

### CODE REVIEW

**Comment by enkore** [comment]
I didn't test, but would expect that now the header from `borg create --stats` would be missing.

> So, remove repo stats from "borg info ARCHIVE"?

I'd rather just leave them there. I find them handy.

**Comment by ThomasWaldmann** [comment]
the header from borg create --stats refers to the archive, not the repository.

**Comment by enkore** [comment]
I mean the `Original size      Compressed size    Deduplicated size` header, since `Statistics` is also used for the --stats output

**Comment by enkore** [comment]
collapse + merge?

**Comment by UndeadKernel** [comment]
I cannot see these changes in the latest Borg release (1.0.8).
Are these not supposed to be in this last release?

**Comment by enkore** [comment]
No, this goes into the 1.1 series.

Stuff for the 1.0 series needs to be merged into 1.0-maint.

**Pull request merged**
