### PR TITLE
misc backports to 1.1-maint

### PR DESCRIPTION
**Pull request by step21**
Backported from master

### CODE REVIEW

**Comment by step21** [comment]
So ... originally this was just the 'convert to str' commit but then I added the other commits to my branch... should i remove those and make clean commits to the unchanged branch?

**Comment by ThomasWaldmann** [comment]
we can merge them all at once.
it's not a problem to have multiple backports in one PR.
just have clean commits with good comments.

**Comment by step21** [comment]
Ok, great. I try to make clean commits with good comments.

**Comment by ThomasWaldmann** [comment]
thanks!

**Pull request merged**
