### PR TITLE
Installation: Mention GNU Guix package.

### PR DESCRIPTION
**Pull request by lfam**
* docs/installation.rst: Add GNU Guix package to list of distribution packages.

### CODE REVIEW

**Comment by infectormp** [comment]
GNU Guix is a package manager, but this section in docs for os distribution. Maybe need make section **Using GNU Guix**?

**Comment by lfam** [comment]
@infectormp The package is for the GNU Guix package manager, which can be used on any GNU / Linux distro. But, you can also use it on the operating system GNU GuixSD, which includes Guix.

Besides, Homebrew is already in that list, and Homebrew isn't an operating system at all.

**Comment by infectormp** [comment]
@lfam Homebrew strictly for OSX, so it normal have it in OS distribution section.

**Comment by infectormp** [comment]
But this only my opinion.

**Comment by enkore** [comment]
The section is "Installation => Distribution Package". "OS" does not appear, and the title doesn't imply it.

**Pull request merged**
