### PR TITLE
Vagrantfile: use FUSE for macOS 3.4.1

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Note: "FUSE for OS X" was renamed to "FUSE for macOS".

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
```
# osxfuse 3.4.1
(borg-env) This-MacBook-Pro:borg vagrant$ py.test -k fuse
___________________________________________________ ArchiverTestCase.test_fuse ____________________________________________________

self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_fuse>

    @unittest.skipUnless(has_llfuse, 'llfuse not installed')
    def test_fuse(self):
        self.cmd('init', self.repository_location)
        self.create_test_files()
        self.cmd('create', self.repository_location + '::archive', 'input')
        self.cmd('create', self.repository_location + '::archive2', 'input')
        mountpoint = os.path.join(self.tmpdir, 'mountpoint')
        # mount the whole repository, archive contents shall show up in archivename subdirs of mountpoint:
        with self.fuse_mount(self.repository_location, mountpoint):
>           self.assert_dirs_equal(self.input_path, os.path.join(mountpoint, 'archive', 'input'))

borg/testsuite/archiver.py:1008: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
borg/testsuite/__init__.py:56: in assert_dirs_equal
    self._assert_dirs_equal_cmp(diff)
borg/testsuite/__init__.py:59: in _assert_dirs_equal_cmp
    self.assert_equal(diff.left_only, [])
E   AssertionError: Lists differ: ['flagfile'] != []
E   
E   First list contains 1 additional elements.
E   First extra element 0:
E   'flagfile'
E   
E   - ['flagfile']
E   + []
```

**Comment by ThomasWaldmann** [comment]
Hmm, same traceback for osxfuse 3.3.3, so this breakage is unrelated to the upgrade.
Note: I rebooted after up / downgrade of OSXfuse.

**Comment by enkore** [comment]
If more tests fail it may imply that UF_NODUMP handling isn't working for [reasons]?

**Comment by ThomasWaldmann** [comment]
@enkore the tests are fixed by #1436.

**Pull request merged**
