### PR TITLE
Add --lock-rc option that sets a discrete code for locking errors 

### PR DESCRIPTION
**Pull request by intelfx**
Add a new common option such that if `--lock-rc N` is passed, then borg will return `N` instead of `EXIT_FAILURE` if the error condition was due to failure to acquire a lock.

This option can come handy if one is writing a Borg frontend, to distinguish hard errors from cases when the remote repository is simply busy (and as such the error probably does not warrant the user's attention).

---

I'm also interested in this feature (or any equivalent, if a different approach would be suggested by the maintainer) being backported to Borg 1.2. I have a patch that applies on top of `1.2-maint`.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Good idea, but I think we should (for compatibility reasons) apply this to 1.2-maint **only**.

For master / borg2, we can just re-define the error codes (see the ticket that is open about that) and not have this cli option.

**Comment by ThomasWaldmann** [comment]
BTW, ignore the mypy failure, I just fixed that.

**Comment by intelfx** [comment]
OK, but #6756 looks like an unknown amount of work with nobody eager to take it on :-) Should I prepare a PR that just picks _some_ exit code, or do you suggest waiting until a decision is made in #6756?

**Comment by ThomasWaldmann** [comment]
Well, guess waiting could take rather long...

OTOH, having a variable or incompatible rc (in 1.2 compared to borg2) does not seem acceptable either.

So guess somebody(tm) needs to at least finish the planning for the **error** codes (which are easier compared to the warning stuff, because there is only 1 error, but there can be multiple warnings).

**Comment by ThomasWaldmann** [comment]
Guess, as of now, this should not be applied at all (neither to master nor to 1.2-maint).

1.4 is intended to supersede 1.2 in the near future and I recently implemented a completely revamped exit code system for errors and warnings (includes locking errors). 1.4.0a1 is ready for alpha-testing this.

1.4-maint was forked from 1.2.7, so besides that bigger change, it should be quite similar as 1.2.

Thanks for the PR nevertheless, this and quite some other tickets talking about more specific exit codes motivated me to implement that on a global scope.

**Comment by intelfx** [comment]
@ThomasWaldmann thanks for working on this! indeed, I would not have had the bandwidth to do it on the global scale anyway, so yeah, thanks for doing it the right way :)

**Pull request closed without merging**
