### PR TITLE
1.2.0a2: Fix some issues found by the testsuite

### PR DESCRIPTION
**Pull request by bket**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@bket thanks for testing the alpha and for the patches. the fd-param related look good, but the getxattr issue needs to get fixed inside `is_enabled` (by first doing a listxattr and only if it is non-empty doing a getxattr. if it is empty, it also means xattrs are not enabled).

**Comment by ThomasWaldmann** [comment]
I fixed it.

Can you please:
- git rebase -i master, and
- drop c11d
- squash 2ff2 and 6b6d
- push -f again

**Comment by ThomasWaldmann** [comment]
for the openssl related stuff guess we better do a new PR.

**Comment by bket** [comment]
@ThomasWaldmann, done!

I think I saw a diff from you for addressing `is_enabled()` earlier today. Maybe I'm seeing ghosts, if this is the case do you want me to fix it?

**Comment by ThomasWaldmann** [comment]
> I think I saw a diff from you for addressing |is_enabled()| earlier 
> today. Maybe I'm seeing ghosts, if this is the case do you want me to 
> fix it?

It was in your github branch before you force-pushed to it. :D

No problem, still have it on my laptop. Will update your branch again 
later today.

**Comment by ThomasWaldmann** [comment]
@bket pull from your github branch to fetch my changes (before doing further changes, if any).

**Comment by ThomasWaldmann** [comment]
ok, travis looks good. @bket can you do a test run on openbsd?

**Comment by bket** [comment]
> ok, travis looks good. @bket can you do a test run on openbsd?

@ThomasWaldmann, done. Looks good on OpenBSD!

**Comment by ThomasWaldmann** [comment]
did another small code dedup, shouldn't break anything.

**Pull request merged**
