### PR TITLE
prune: kill all checkpoints except the latest

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
prune: only keep latest checkpoint if not superceded by a successful backup

### CODE REVIEW

**Comment by jdchristensen** [comment]
My only reason for suggesting a command line switch is that some people might backup multiple clients into one repo, and might run a prune command on the server once a week, for example, without a prefix.  But I think most people will arrange that the clients do their own pruning, so I don't feel very strongly about this.

**Comment by ThomasWaldmann** [comment]
@jdchristensen how can that work without prefix? e.g. if you tell it --keep-monthly 6 it will keep the 1 latest monthly archive for each month for 6 months. and if you backup client A and client B into same repo, you will only keep the monthly backup for one of them (and if you always backup first A, then B, it will always keep B and never A).

**Comment by jdchristensen** [comment]
I agree that it's not a likely use case.  The only thing I can imagine is someone using '--keep-within 2y' or something like that.

**Comment by ThomasWaldmann** [comment]
added docs and collapsed commits.

**Comment by enkore** [comment]
Looks good. Docs are nice and clear :)

**Pull request merged**
