### PR TITLE
fix temp filename collision for parallel running code

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
hmm, does that make sense?

or does it just hide issues that we should not have in the first place?

### CODE REVIEW

**Comment by enkore** [comment]
Each test should have it's own repo etc. in a collision-free tmp path. This change suggests this is not the case? (Since these are internal files of the repo)

**Comment by ThomasWaldmann** [comment]
that's what i meant in top post. i didn't review all tests, it was just a vague suspicion.

**Comment by ThomasWaldmann** [comment]
i am starting this travis build a few times just to see if the isadirectory issue appears.

**Comment by enkore** [comment]
My concern here is that we have no hypothesis why this fixes it / why this should fix it. That this fixes the problem either indicates that there is a bug in the underlying platform or that parallel test cases actually work in the same repository, which raises it's own set of questions (like, what happened to locking?!).

**Comment by ThomasWaldmann** [comment]
ok, guess we better don't apply.

**Pull request closed without merging**
