### PR TITLE
Correct shell syntax for installation using git

### LINKED ISSUE #6761: Shell syntax error in documentation (Installation -> Using git)
In https://borgbackup.readthedocs.io/en/stable/installation.html#using-git

```
virtualenv --python=${which python3} borg-env
```
should be
```
virtualenv --python=$(which python3) borg-env
```

### PR DESCRIPTION
**Pull request by targhs**
Fix #6761

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks! Can you do the backport to 1.2-maint also?

**Comment by targhs** [comment]
> 

By backport you mean make a PR to 1.2-maint?

**Comment by ThomasWaldmann** [comment]
Yes, exactly. That way, it will get into 1.2.2 and not just into next minor/major release (which can take quite a while).

**Comment by targhs** [comment]
Here you go.
https://github.com/borgbackup/borg/pull/6765

No issue was there. Shall i create one?

**Comment by ThomasWaldmann** [comment]
No, not necessary. I just merged it.

**Comment by targhs** [comment]
Thanks

**Pull request merged**
