### PR TITLE
make constants for files cache mode more clear

### PR DESCRIPTION
**Pull request by elho**
Traditionally, DEFAULT_FILES_CACHE_MODE_UI and DEFAULT_FILES_CACHE_MODE
were - as the naming scheme implies - the same setting, one being the UI
representation as given to the --files-cache command line option and the
other being the same default value in the internal representation.

It happended that the actual value used in borg create always comes from
DEFAULT_FILES_CACHE_MODE_UI (because that does have the --files-cache
option) whereas for all other commands (that do not use the files cache) it
comes from DEFAULT_FILES_CACHE_MODE.

PR #5777 then abused this fact to implement the optimisation to skip loading
of the files cache in those other commands by changing the value of
DEFAULT_FILES_CACHE_MODE to disabled.
This however also changes the meaning of that variable and thus redesignates
it to something not matching the original naming anymore.

Anyone not aware of this change and the intention behind it looking at the
code would have a hard time figuring this out and be easily mislead.

This does away with the confusion making the code more maintainable by
renaming DEFAULT_FILES_CACHE_MODE to FILES_CACHE_MODE_DISABLED, making the
new intention of that internal default clear.

Thank you for contributing code to Borg, your help is appreciated!

Please, before you submit a pull request, make sure it complies with the
guidelines given in our documentation:

https://borgbackup.readthedocs.io/en/latest/development.html#contributions

**Please remove all above text before submitting your pull request.**

### CODE REVIEW

**Comment by elho** [comment]
This is the "minimal" version, it may make sense to extend it by also renaming `DEFAULT_FILES_CACHE_MODE_UI` by sneaking a `CREATE` in there, e.g. `FILES_CACHE_MODE_UI_CREATE_DEFAULT` to make that one even more clear, too. Thoughts?

**Comment by ThomasWaldmann** [comment]
FILES_CACHE_MODE_UI_CREATE_DEFAULT - good idea, but as we currently **only** use it for create and also we do not know yet if / how it would be used elsewhere, i guess we can leave away the "CREATE" for now.

**Comment by ThomasWaldmann** [comment]
@elho are you finished with this or do you want to make changes?

**Comment by elho** [comment]
> @elho are you finished with this or do you want to make changes?

Oh, I took your previous comment as "leave DEFAULT_FILES_CACHE_MODE_UI alone", but I'll happily still bring it in line with the hierarchical scheme just leaving the CERATE part out...

**Review by ThomasWaldmann — APPROVED** [review]

**Pull request merged**
