### PR TITLE
Removal of |project_name|.

### PR DESCRIPTION
**Pull request by TBurchfield**
Removed |project_name| in documentation to make it more readable.  Replaced with "Borg".

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
PR looks strange, see https://github.com/borgbackup/borg/pull/3182/files.

**Comment by TBurchfield** [comment]
Sorry about that, must have made a mistake.  I'll add the correct commit when I get home.

**Comment by TBurchfield** [comment]
Fixed :heavy_check_mark:.

**Comment by ThomasWaldmann** [comment]
thanks for the fixes!

**Pull request merged**
