### PR TITLE
add locked requirements (master)

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
this need special care when backporting:

- try the locked requirements on github ci first (by placing them in development.txt)
- also, compare with the previous stuff, not all requirements from master might apply

**Comment by hexagonrecursion** [comment]
I'll backport this today

**Comment by ThomasWaldmann** [comment]
see also #6246.

**Comment by hexagonrecursion** [comment]
Backport is merged. Please remove the backport/1.1-maint label

**Pull request merged**
