### PR TITLE
"auto" compressor tests: don't assume a specific size (backport to 1.2-maint)

### PR DESCRIPTION
**Pull request by snsmac**
#7364 
#7372 

I'm not completely sure if it makes sense to backport 8916b5a7dac560b4a54953b53df9aa6bdcee5f38 as it is not directly related with the other commit

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Porting #7364 is still a bit early, as we do not have feedback yet about whether it improved the tests on S390.

**Comment by ThomasWaldmann** [comment]
Let's see whether the tests work with the locked requirements.

After that has finished, we'll try again without that commit.

**Comment by ThomasWaldmann** [comment]
OK, it worked with the locked requirements, we no can check without that change.

**Comment by snsmac** [comment]
On my computer it works without the change, so i updated the MR

**Comment by ThomasWaldmann** [comment]
Looks good, just waiting for feedback in #7363.

**Comment by ThomasWaldmann** [comment]
Looks good: https://github.com/borgbackup/borg/issues/7363#issuecomment-1455136193 (2nd patch == #7372)

**Comment by ThomasWaldmann** [comment]
OK, so now only master is left to fix in the same way.

**Pull request merged**
