### PR TITLE
[DOCS] #4587 – Make Sphinx warnings break docs build

### PR DESCRIPTION
**Pull request by fantasya-pbem**
Backport from master and some other fixes for Sphinx warnings.

### CODE REVIEW

**Comment by fantasya-pbem** [comment]
TravisCI Python 3.4 builds fail with:

Collecting Pygments>=2.5.1 (from readme-renderer>=21.0->twine==1.13.0->-r requirements.d/development.lock.txt (line 12))
ERROR: Could not find a version that satisfies the requirement Pygments>=2.5.1 (from readme-renderer>=21.0->twine==1.13.0->-r requirements.d/development.lock.txt (line 12)) (from versions: 0.5, 0.5.1, 0.6, 0.7, 0.7.1, 0.8, 0.8.1, 0.9, 0.10, 0.11, 0.11.1, 1.0, 1.1, 1.1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.4, 1.5, 1.6rc1, 1.6, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.3.0, 2.3.1)
ERROR: No matching distribution found for Pygments>=2.5.1 (from readme-renderer>=21.0->twine==1.13.0->-r requirements.d/development.lock.txt (line 12))

**Comment by ThomasWaldmann** [comment]
Maybe compare the package versions used here with the package versions used in the last successful 1.1-maint travis build. Guess something has changed that needs to be added to our development.lock.txt (which exists to avoid such problems).

**Comment by fantasya-pbem** [comment]
Found it: readme-renderer 25.0 was release on March 14. From the changelog:

* Support Python 3.7 and 3.8
* **Drop support for Python 3.4**
* Require Pygments>=2.5.1

What to do now? Shall I restrict readme-renderer to 24.0 in development.lock?

**Comment by fantasya-pbem** [comment]
Restricting readme-renderer to <=24.0 in both development.txt and development.lock.txt was the key.

**Comment by ThomasWaldmann** [comment]
restrict to < 25.

**Comment by ThomasWaldmann** [comment]
we could also lock to ALL stuff installed in a successful build.

**Comment by fantasya-pbem** [comment]
> we could also lock to ALL stuff installed in a successful build.

Hmm, I personally don't like that. In general (not specific to Borg or Python), I find it quite useful if builds break because of updated packages, so one has to go and look at the release notes, which results in a better overview how version constraints develop over time. But I may go wrong here for Borg as I have no Python experience.

**Comment by ThomasWaldmann** [comment]
I agree concerning borg's dependencies/requirements.

but for the testing environment/tools, we could also lock to something working for 1.1-maint and only have the latest/greatest stuff in master.

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
