### PR TITLE
borgversion placeholder 1.0-maint

### PR DESCRIPTION
**Pull request by leo-b**
PR for #1392 against 1.0-maint branch

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
lgtm - collapse / merge?

**Comment by enkore** [comment]
lgtm

**Comment by ThomasWaldmann** [comment]
@leo-b can you git rebase -i 1.0-maint and collapse some of the changesets?

**Comment by leo-b** [comment]
Squashed it together in one commit. Is this what you meant?

**Comment by ThomasWaldmann** [comment]
I didn't necessarily mean 1 commit, but esp. squash the reverted stuff. But leave it like it is now, it is fine.

**Pull request merged**
