### PR TITLE
Use --timestamp in placeholders if given (1.1 backport)

### PR DESCRIPTION
**Pull request by milkey-mouse**
See #5189, #5472.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
py35 tests failing.

**Comment by milkey-mouse** [comment]
Is there a good reason --timestamp is limited to UTC in the first place? Currently the timestamp, whether given directly or via a file, is a naive datetime. IMO the "best" way to solve this issue is to make them timezone aware.

**Comment by ThomasWaldmann** [comment]
I can't help with that, please find out in the code yourself.

I just want it to be consistent, so implement dealing with timezones in the same way as the code is doing it right now.

**Comment by milkey-mouse** [comment]
I was mostly thinking out loud. TL;DR it works correctly, such that {now} is different from {utcnow} with --timestamp (if you're not in UTC timezone).

**Comment by ThomasWaldmann** [comment]
Thanks for the PR. For remaining issues / ideas, please open a ticket.

**Pull request merged**
