### PR TITLE
xattrs / extended stat: improve exception handling (1.2-maint)

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
see #6988

### CODE REVIEW

**Comment by KN4CK3R** [comment]
Ready to port or still a draft?

**Comment by ThomasWaldmann** [comment]
I'm waiting for feedback from @Rudd-O .

**Comment by Rudd-O** [comment]
This is very kind of you.  Sept 1st I'm back in the city and ready to attempt to spin this on my backup clients.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/6988#issuecomment-1233151504 so, can i take the "thumbs up" there that it worked as designed?

if so, i'ld merge this into 1.2 (so it will get into 1.2.3 release) and we also would forward port this to master branch.

**Comment by Rudd-O** [comment]
You get an LGTM for me.  This code is useful.

**Comment by ThomasWaldmann** [comment]
Will merge this soon if nobody objects. After it is merged into 1.2-maint, a fwd port to master should be done.

**Pull request merged**
