### PR TITLE
get back pytest's pretty assertion failures, fixes #1938

### LINKED ISSUE #1938: py.test has lost the nice assertion failure display
when fixing #1930, I noticed that when the assertion fails, it just says "AssertionError", it does not display the values of the terms in the assertion expression.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
@ronny thanks, your hint helped. :)

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by ronny** [comment]
???

**Comment by ThomasWaldmann** [comment]
oh, sorry @ronny, I meant @RonnyPfannschmidt.

but in case you need a nice backup program, here you go, haha. B-)

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt Hmm, I read these pytest docs and they said these problems are caused by importing application modules from conftest.py. I only import "borg" there, so I thought giving that is appropriate...

So, "borg.testsuite" or what do you mean precisely?

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann from the details if the issue thought mostly the test helpers where affected

as for code under test - it tends to be a good idea to only rewrite test helpers, but leave normal application code be subject to normal python import (simply a measure to ensure the bytecode you test is the same under test and in production)

**Pull request merged**
