### PR TITLE
Complements the documentation for pattern files and exclude files, fixes #5336 [1.1]

### LINKED ISSUE #5336: The meaning of "statistical medium".
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

A request for clarification of a term in the documentation.

## Details

This appears at a few places in the documentation:
"HASH_MASK_BITS = 21 (**statistical medium** chunk size ~= 2^21 B = 2 MiB)"

At first I thought that by 'medi **_um_**' it meant 'medi **_an_**', but in another place it says
"producing chunks of 2^HASH_MASK_BITS Bytes on **_average_**",
and average usually means 'arithmetic mean'.

Can you say which measure of '[central tendency](https://en.wikipedia.org/wiki/Central_tendency)' is the intended/correct meaning of 'statistical medium'?

When I know which it means, will I be able to choose my chunker params any better? Not sure about that ... ;)

### PR DESCRIPTION
**Pull request by Gu1nness**
Backport #5436 to 1.1-maint

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
thanks!

**Comment by ThomasWaldmann** [comment]
crap, looks like a copy&paste error happened here for the commit comment and i did not notice and duplicated that to the PR title...

correct comment should be "Change documentation inaccuracy on chunk size."

**Comment by Gu1nness** [comment]
So should I open a new PR with the good commit message?

**Comment by ThomasWaldmann** [comment]
no, considering it is already merged, guess it is too late.
so we just keep it as is.

**Pull request merged**
