### PR TITLE
"list" argument appears deprecated, but still existed in an example

### PR DESCRIPTION
**Pull request by Orbixx**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
are you running github master branch code? --list should work there.

**Comment by Orbixx** [comment]
This is on 0.30.0 release

**Comment by ThomasWaldmann** [comment]
oh, now i see. --list is for "borg create" (not "extract").

**Comment by Orbixx** [comment]
Alternatively perhaps introduce --list to borg extract?

**Comment by ThomasWaldmann** [comment]
yeah, that's even better. we currently do not have --stats, but there is --show-rc, so if one would just want that, without the file list, one would need such a --list option. also good for consistency.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/609

**Comment by ThomasWaldmann** [comment]
I am closing this now as now borg extract really behaves like documented there. :)

Thanks for finding this inconsistency.

**Pull request closed without merging**
