### PR TITLE
enable using libxxhash (1.1-maint only)

### LINKED ISSUE #5400: libxxhash for 1.1-maint
http://paste.debian.net/1166236/

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
similar to the code we already have in master branch.

thanks to @LocutusOfBorg !

fixes #5400.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg i did some testing on misc. OSes and dists and think this is ready to merge. What do you think?

**Comment by ThomasWaldmann** [comment]
https://buildd.debian.org/status/package.php?p=borgbackup&suite=sid looks good, merging...

**Comment by LocutusOfBorg** [comment]
yay thanks a lot!!!

**Comment by LocutusOfBorg** [comment]
Also ppa for xenial, bionic, focal and groovy are good now
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup/+packages

**Pull request merged**
