### PR TITLE
Don't backup doors

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
this needs a test - also what exactly is a "door" - its kind of hard to google

**Comment by RonnyPfannschmidt** [comment]
oh, i found https://blogs.oracle.com/jonh/entry/who_s_at_the_door

so its a pic facility similar to sockets

**Comment by enkore** [comment]
We should probably also skip ports (S_ISPORT), they are "Solaris event ports". I guess testing these outside Solaris could prove ... difficult?

**Comment by pyhalov** [comment]
Yes, forgot about ports

**Comment by ThomasWaldmann** [comment]
Could you do a PR against 1.0-maint? So it'll get into 1.0.1.

Also, if that is a Solaris(and derivates)-only feature, maybe add "(Solaris)" to the comment lines you have.

**Comment by ThomasWaldmann** [comment]
superceded by #784 (1.0-maint changes will also get merged into master).

**Pull request closed without merging**
