### PR TITLE
add BORG_CONFIG_DIR env (#3083)

### LINKED ISSUE #3083: add BORG_CONFIG_DIR
from the mailing list:

> I've read them BORG_CACHE_DIR is OK but I see no way to relocate the ".config/borg" directory in its *entirety*!
>
> If I read the docs correctly, I can only relocate *parts* of ".config" with BORG_KEYS_DIR and BORG_SECURITY_DIR but there are other files besides these on the ".config/borg" directory.
>
> I'd really like a BORG_CONFIG_DIR variable to relocate the *whole* config dir. I want everything in ONE predictable place, especially stuff related to backups which is a really critical process in my PoV.

### PR DESCRIPTION
**Pull request by narendravardi**
Fixes #3083

For more details info, see PR: https://github.com/borgbackup/borg/pull/3206

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/src/borg/testsuite/helpers.py#L450

can you add a test for the new stuff there?

**Comment by ThomasWaldmann** [comment]
about the travis flake8 fail: strange, but doesn't seem to be related to your changes.

**Comment by narendravardi** [comment]
@ThomasWaldmann, I have testcase. Please check

**Comment by narendravardi** [comment]
@ThomasWaldmann thanks! :)

**Comment by ThomasWaldmann** [comment]
hmm, just noticed that docs for this are missing. do you want to make another PR?

**Comment by narendravardi** [comment]
Sure. I will check and get back to you.

**Comment by narendravardi** [comment]
@ThomasWaldmann, Is this the only file which I have to change?

https://github.com/narendravardi/borg/blob/a5c6a50ebece4df460af28c11c37b114dcf26c60/docs/usage_general.rst.inc

**Comment by ThomasWaldmann** [comment]
https://github.com/narendravardi/borg/blob/a5c6a50ebece4df460af28c11c37b114dcf26c60/docs/usage_general.rst.inc#L188 yes, there.

**Pull request merged**
