### PR TITLE
Merge 1.0 maint

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by enkore** [comment]
Strange, there are commits here that were already merged in #1520?

**Comment by ThomasWaldmann** [comment]
huh?

**Comment by enkore** [comment]
Well this has `internals.rst: fix typos`, `use trusty for testing, to have a recent FUSE`, `travis: test fuse-enabled borg`, `re-enable fuse tests for RemoteArchiver` and `add debug-info usage help file`, all of which were previously merged in #1520.

**Comment by ThomasWaldmann** [comment]
Maybe github caching issue?

**Comment by enkore** [comment]
I guess. In gitk it doesn't look like they're duplicated, so the git history is correct and Github must be confused somehow.

**Pull request merged**
