### PR TITLE
In api decorator, pass wait argument to RemoteRepository.call; fixes …

### PR DESCRIPTION
**Pull request by jdchristensen**
…#2185

Some more independent timing tests would be good, in case there are other independent regressions.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Did 2 measurements, both looked similar to this one:
```
$ git checkout 1.1.0b2
$ . speedtest.sh 

borg 1.1.0b2
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:02.87

$ git checkout test-fix-remote-jdc
$ . speedtest.sh 

borg 1.1.0b4.dev115+ng6d8a538
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:02.90
```
So, looks like @jdchristensen fixed the speed issue. \o/

@textshell can you review the PR please?

**Comment by textshell** [comment]
Nice find jdchristensen.

Sorry, i won’t be able to fully review this very quickly.
But ignoring the wait=False argument used for all put/delete from the cache (i.e. the main data path) is certainly a bug. This PR looks like it fixes that. And the speed measurements seem to agree.
From a quick grep and look this patch seems fine. But as usual with the RPC code more eyes are definitively not an bad idea.

**Comment by textshell** [comment]
One additional thought. It would be nice to have a special mode for some of our tests that notices if the code ignores any of the named parameters. Just to avoid bugs like this in the future. But nothing that needs fixing in this PR.

**Comment by jdchristensen** [comment]
While we are looking at this, are there any other "meta" arguments that are meant for the local code not the remote code?  (That's what is really happening here.)  The patch is designed to make the list easy to extend, if needed, but it's also fragile in the sense that if an api call is added that has `wait` as a valid argument to the remote process, it will break.  If there are others, we could choose a naming scheme that keeps them separate.

**Comment by enkore** [comment]
@ThomasWaldmann 

> $ git checkout test-fix-remote-jdc

Trick 17:

```
$ cat .git/config
... stuff ...
[remote "origin"]
        url = http://github.com/borgbackup/borg
        fetch = +refs/heads/*:refs/remotes/origin/*
        fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
... more stuff ...
```

The second `fetch` line allows access to all PRs in the repository by eg. `git checkout pr/2194`.

**Comment by jdchristensen** [comment]
I added a couple of comments, but no code changes.  I'll squash them later.

**Comment by ThomasWaldmann** [comment]
@enkore nice trick. one first needs to do "git fetch origin" then, but after that it works. \o/

**Comment by jdchristensen** [comment]
I squashed the two commits into one, and think this is ready to merge. If we find that further arguments need the same treatment, it will be easy to extend what I wrote. People touching this code just need to be aware of this issue, and the comments in the new code point out the issue.

**Comment by enkore** [comment]
Thanks!

**Pull request merged**
