### PR TITLE
revert incorrect fix for put updating shadow_index, fixes #5661

### LINKED ISSUE #5661: consequences of borg put shadow_index bug?
see #5636 for the bugfix.

as this bug was present for a while in borg, let's think about its consequences here (and what we can / must do about it for existing repos).

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
A) the compaction code needs the shadow index only for this case:

segment A: PUT x, segment B: DEL x, with A < B  (DEL shadows the PUT).

B) for the following case, we have no shadowing DEL (or rather: it does not matter,
because there is a PUT right after the DEL) and x is in the repo index,
thus the shadow_index is not needed for the special case in the compaction code:

segment A: PUT x, segment B: DEL x PUT x

see also PR #5636.

reverts f079a83fed91c1221951303f758187987be0ac47
and clarifies the code by more comments.

we keep the code deduplication of 5f32b5666af961f5256221660a7356d467f66605
and just add a update_shadow_index param to make it not look like there was
something accidentally forgotten, which was the whole reason for the reverted
"fix".

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@timmc @enkore i basically reverted the "fix" (which was not really needed), hopefully this is correct now.

i kept the dedup refactor though and added some comments. please check.

**Review by timmc — COMMENTED** [review]
So the shadow index is only for entries that get shadowed by a DEL or PUT _not_ in the same segment? If so, this looks good to me.

**Comment by ThomasWaldmann** [comment]
Yes, only in that case the crash with bad write ordering issue described in the compact_segments code becomes a problem.

**Comment by ThomasWaldmann** [comment]
Update: this was wrong. :-(

See reopened #5661.

**Pull request merged**
