### PR TITLE
Forwardport pull request #5902

### PR DESCRIPTION
**Pull request by KN4CK3R**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Could you do the port in a way so that the original commit comments show in history?

Otherwise it is hard to generate a meaningful changelog, if there are only references to PR numbers.

**Comment by ThomasWaldmann** [comment]
@KN4CK3R did you see my feedback?

**Comment by KN4CK3R** [comment]
Sorry, missed your feedback.
The original commit message is still there or what do you mean?
grafik

**Comment by ThomasWaldmann** [comment]
Ah, it's in the long comment, which I did not see, just looked at the short (first line) commit comment.

Please don't backport the merge commits in future, but the commit that implements the change, so the comment is better visible.

**Pull request merged**
