### PR TITLE
Remove comma from install_requires

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
For some reasons this comma is making the Debian build fail
dpkg-buildpackage -S -sa
[snip]
dh clean --with python3,sphinxdoc --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:170: python3.4 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    install_requires=install_requires,
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 324, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 19, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 67, in get_version
    version = version_from_scm(root)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 29, in version_from_scm
    return ep.load()(root)
  File "/usr/lib/python3/dist-packages/setuptools_scm/git.py", line 34, in parse
    return meta(tag, distance=number, node=node, dirty=dirty)
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 85, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
and... resistance is futile :)

**Comment by ThomasWaldmann** [comment]
strange, the traceback does not look like it is caused by that comma. and python does not have issues with trailing commas in lists.

**Comment by RonnyPfannschmidt** [comment]
this looks like the classic mistake of taking a git tarball, git is completely unable to provide useful metadata in its own archives,

if you update setuptools_scm you should get a clear message - and please please use a sdist

**Comment by LocutusOfBorg** [comment]
true, seems to be caused when I try to rebuild the package without readding the metadata
BTW I use the latest setuptools_scm 1.8.0-1

**Comment by RonnyPfannschmidt** [comment]
what do you mean by readding metadata? does debian strip the egg info folders and PKG-INFO?

also how exactly does debian package setuptools_scm? they at least never consulted me on details, and given the debian rules they might have broken it to begin with

**Comment by LocutusOfBorg** [comment]
Hi, yes, I never consulted you because we didn't finish the packaging yet :)

As soon as we have something working I'll be happy to share it with you for review.

If you want to see something it is here
http://debomatic-amd64.debian.net/distribution#unstable/borgbackup/0.27.0-1/buildlog

and we are working here
http://anonscm.debian.org/cgit/collab-maint/borgbackup.git

@dannyedel is doing the job, but I'll finish the packaging in the next few days.

**Comment by RonnyPfannschmidt** [comment]
@LocutusOfBorg tracking the version in the git repo is bound to confuse setuptools_scm,
since suddenly there is a git repo that gives utterly wrong metadata

im also not quite sure why you track the actual project in git - all other distros im aware of track hashes and patches, not actual source trees

to suppoort distribution builds setuptoosl_scm could be extended to conisder certain environment variables

the correct way would be to set the version to either the pristine one, or if you have a patch-set, to `version+debian$patchlevel` following pep-440 wrt local versions

i feel this is a discussion to be had in setuptools_scm,
cause clearly debian packaging is designed to purposely break anything that trusts the scm as first source of truth

**Comment by LocutusOfBorg** [comment]
you are quite right, we discussed a lot how to properly package the tool, if following the git master and tags, or pristine-tarballs and we found a third way.
Using the pristine-tarball without loosing the upstream git history, allowing us to easily cherry-pick stuff whenever needed
https://wiki.debian.org/PackagingWithGit#Upstream_import_methods

But yes, this might have bad effects on setuptools_scm tool indeed.

I didn't discuss with you yet, because we are still trying to test the best way to package the tool, but help is appreciated :)

**Comment by RonnyPfannschmidt** [comment]
your very first step should be to figure whats needed in collaboration with setuptools_scm to prevent your packaging mechanism from breaking/confusing it, because else all packaging on top will be a bad hack

**Comment by anarcat** [comment]
@LocutusOfBorg i have messed up the master branch while you submitted this, can you rebase your patch?

```
git remote update
git rebase 7ae8346^ patch-1 --onto origin/master
```

thanks and sorry for the trouble

**Comment by ThomasWaldmann** [comment]
I am closing, rejecting this PR for now due to 2 reasons:
a) we messed up the gh repo and had to do a hard reset, so this PR is now messed up also (sorry)
b) the comma does not seem to be the cause for the setuptools_scm issue. I suggest this is investigated further and I'ld be happy to have another PR once the issue is clear.

**Comment by LocutusOfBorg** [comment]
no problem, there is no need to apply this patch :)

**Comment by LocutusOfBorg** [comment]
Hi, just FYI I think I'll go for debian/unstable in the next few days.

At the end we won't mix upstream git and tarballs anymore, we will follow the pristine tarballs approach with Debian packaging, so we can just use it and forget about everything else
you can see a buildhere
http://debomatic-amd64.debian.net/distribution#unstable/borgbackup/0.27.0-1/buildlog

**Comment by ThomasWaldmann** [comment]
Thanks for caring for debian packaging. :) If it is done, add a link to the ticket about dist packages.

**Comment by LocutusOfBorg** [comment]
I just uploaded on debian new queue the 0.27.0 packaging.

it will show up there https://ftp-master.debian.org/new.html in a few minutes/hours, and then opefully be accepted by ftp-masters
you can see the packages here
http://debomatic-amd64.debian.net/distribution#unstable/borgbackup/0.27.0-1/buildlog
and the packaging here
http://anonscm.debian.org/cgit/collab-maint/borgbackup.git
(with also a manpage, created with help2man IIRC)

**Comment by ThomasWaldmann** [comment]
ah, cool. :) so you could resolve the setuptools_scm / versioning issue?

**Comment by LocutusOfBorg** [comment]
actually we have the versioning files from the tarball inside our git
http://anonscm.debian.org/cgit/collab-maint/borgbackup.git/tree/borg

the problem was just that the clean step was deleting them, and with git-buildpackage they arent anymore instead of dpkg-buildpackage, I presume because the git directory is copied outside (it is like an out-of-source build).

**Comment by LocutusOfBorg** [comment]
dpkg-buildpackage command before the build runs a clean with
"pybuild --clean -i python{version} -p 3.4 --dir ."

this isn't run with git-buildpackage.

**Comment by anarcat** [comment]
so this can be closed?

the debian package discussion should be in #105, really... or at least
make sure you bump that issue when there are changes to the debian
package.

thanks!

-- 
The world is a dangerous place, not because of those who do evil,
but because of those who look on and do nothing.
                        - Albert Einstein

**Comment by LocutusOfBorg** [comment]
sure :+1:

**Comment by LocutusOfBorg** [comment]
@ThomasWaldmann to answer to your question
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792096#127

**Pull request closed without merging**
