### PR TITLE
Update resources.rst to rename atticmatic to borgmatic

### PR DESCRIPTION
**Pull request by witten**
atticmatic wrapper script has been renamed to borgmatic!

### CODE REVIEW

**Comment by enkore** [comment]
FYI the first link in this text on the newly linked site is 404:

> Got an issue or an idea for a feature enhancement? Check out the **borgmatic issue tracker**. In order to create a new issue or comment on an issue, you'll need to login first.

**Comment by witten** [comment]
Thanks, I've fixed the issue tracker link. I know I forget something!

**Comment by witten** [comment]
And thanks for the feedback on the code snippets. They're using a common coding color theme called [Solarized](http://ethanschoonover.com/solarized) that, ironically, is intended to be easy on the eyes. Maybe the dark code snippet background doesn't work well with the rest of the page having a white background?

**Comment by witten** [comment]
Switched to Solarized Light instead of Solarized Dark. Let me know if that helps, or if the contrast is still too low.

**Comment by ThomasWaldmann** [comment]
@witten does it make sense to update this in 1.0-maint branch? master == 1.1 in future.

**Comment by witten** [comment]
Yeah, that probably makes sense.

**Comment by ThomasWaldmann** [comment]
Note that 1.0-maint changes automatically get merged into master (but not vice versa).

**Comment by witten** [comment]
Makes sense. I suggested the same change on 1.0-maint here: https://github.com/borgbackup/borg/compare/1.0-maint...witten:patch-2

**Comment by ThomasWaldmann** [comment]
superceded by #1153

**Pull request closed without merging**
