### PR TITLE
cherry pick changes back from 1.0-maint (one-off)

### LINKED ISSUE #2150: paperkey.html - test failure on bsd
```
==> openbsd64:         with open(export_file, 'r') as fd:
==> openbsd64: >           export_contents = fd.read()
==> openbsd64: 
==> openbsd64: py34/lib/python3.4/site-packages/borg/testsuite/archiver.py:1284: 
==> openbsd64: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
==> openbsd64: 
==> openbsd64: self = <encodings.ascii.IncrementalDecoder object at 0x1f152dd20f0>
==> openbsd64: input = b'<!doctype html>\n<html moznomarginboxes mozdisallowselectionprint>\n<!--\n    Notes:\n        This may never cause e...false);\n    }\n\n    update();\n}\n\nwindow.addEventListener("load", loaded, false);\n\n</script>\n\n</body>\n</html>'
==> openbsd64: final = True
==> openbsd64: 
==> openbsd64:     def decode(self, input, final=False):
==> openbsd64: >       return codecs.ascii_decode(input, self.errors)[0]
==> openbsd64: E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 544: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by enkore**
git log --format="- [ ] %h %s" master..1.0-maint
- n 3a3dfcb Merge pull request #2149 from borgbackup/release-1.0.10
- x e5f7121 paperkey.html - decode as utf-8, fixes #2150
- x bb62603 add paperkey.html to pyinstaller spec
- n 33aeb22 docs/api: cleanup
- x e208d11 setup.py: build_api: sort file list for determinism
- n 6304556 ran build_usage
- n 1cf58fb ran build_api
- n 32acaff docs: changes: fix two rST warnings (already in master)
- x 0d20a0d key export: center QR code on the page
- x cf1f409 add test for export key --qr-html
- x e635f21 update CHANGES (1.0.10)
- n d188886 Merge pull request #1971 from leo-b/1.0-maint-patterns
- n c688b1b Merge pull request #2146 from bebehei/samefs-mountpoints-doc-maint
- x d3a2f36 clearify doc for same filesystems
- n 4f9dd98 Merge pull request #2135 from textshell/feature/paperkey-doc-qr
- x 257e55f Add qr html export mode to `key export` command
- x 52e84a6 quickstart.rst: Add link to paperkey template.
- x 57bc1ff paperkey.html: Add interactive html template for printing key backups.
- n 455a9c0 Merge pull request #2136 from textshell/update-authors
- x bd8be26 Add myself to AUTHORS
- n 5479ef4 Merge pull request #2115 from textshell/fix/manifest-timestamp
- n 2209b9c Merge pull request #2122 from ThomasWaldmann/pytest2x-compat
- n acc44a1 pytest: use [pytest] section in setup.cfg
- x 6b8cf0a Manifest: Make sure manifest timestamp is strictly monotonically increasing.
- x a908599 add two tests for the order of patterns and excludes
- x 2c10bf4 backport clean_lines() from master and use it instead of pattern_file_iter()
- x 58c3e0c flake8 beautifications
- x 7b668a1 - change argument parsing of pattern- and exclude-files:   patterns from such files are inserted in the order of appearance on the commandline now. - allow specifying root paths for borg create and borg extract only by root patterns ("R path") - adopt test cases and add some test cases for pattern argument parsing
- x ad421a7 cosmetic changes for TW
- x ead93b2 minor changes due to TWs review
- x 7d27991 fix parsing of root patterns on the commandline some other cosmetic changes suggested by encore
- x 67bd303 flake8, second attempt :-)
- x 3fdc631 flake8 beautifications
- x e4283f8 fix commandline arguments
- x fbee04c simplify example in helptext. add testdata.
- x 876b670 add two new options --pattern and --patterns-from as discussed in #1406

n = not applied, x = applied

This time around I cherry picked the changes because the merge was so messy again. Made resolving the conflicts much easier but I have some scepticism regarding tracking of what's in what branch. Might still be worth it. 

I squashed the --pattern related commits into one.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
apply that one? 32acaff docs: changes: fix two rST warnings

**Comment by ThomasWaldmann** [comment]
apply that one? 67bd303 flake8, second attempt :-)

**Comment by enkore** [comment]
32acaff is already in master (was already backwards-cherry-picked X-), I corrected 67bd303, it's actually in, just not through the commit.

**Comment by ThomasWaldmann** [comment]
just check the 2 you have marked as "not applied". I have reviewed the diff and it lgtm.

**Comment by ThomasWaldmann** [comment]
yes, we can require pytest3 for 1.1.

**Comment by ThomasWaldmann** [comment]
minor nitpick: call this "cherrypick from 1.0-maint" rather than "merge..."?

**Pull request merged**
