### PR TITLE
Updated zsh completions for borg 1.1.4

### PR DESCRIPTION
**Pull request by SanskritFritz**
Since @mrkmg seems to be absent nowadays, I took the courage and updated zsh completions to be on-par with bash/fish completions.

### CODE REVIEW

**Comment by mrkmg** [comment]
Sorry about that. Been out of the picture with a work project. Thank you taking the reins here.

**Comment by SanskritFritz** [comment]
@mrkmg Hey, welcome back 😄 
I hope you don't mind me intruding your area. Please check and test this version, it has been changed even since the version you merged into your repo.

**Comment by ThomasWaldmann** [comment]
@mrkmg can you review this?

**Comment by mrkmg** [comment]
LGTM.

**Pull request merged**
