### PR TITLE
Backport: fix new xattr tests for binary test runs

### PR DESCRIPTION
**Pull request by hexagonrecursion**
This is a backport of #6115

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
you checked that the 2 overridden methods are actually implemented / in use in 1.1?

**Comment by ThomasWaldmann** [comment]
I am asking because without the "borg.exe" binary, you can't reproduce the issue with the binary tests (nor see whether it is fixed with your change).

**Comment by hexagonrecursion** [comment]
```py3
$ sudo ln --symbolic ~/.venv/borg-1.1/bin/borg /bin/borg.exe
$ git checkout fe408960
$ fakeroot pipx run tox --develop -e py3 -- -k 'test_do_not_fail_when_percent_is_in'
py3 develop-inst-nodeps: /home/user/borg
py3 installed: attrs==21.4.0,bleach==4.1.0,-e git+https://github.com/borgbackup/borg.git@fe408960bdf30b9e3220b94fbc5207e5756877da#egg=borgbackup,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.10,colorama==0.4.4,coverage==6.2,cryptography==36.0.1,Cython==0.29.26,distlib==0.3.4,docutils==0.18.1,execnet==1.9.0,filelock==3.4.2,idna==3.3,importlib-metadata==4.10.1,iniconfig==1.1.1,jeepney==0.7.1,keyring==23.5.0,llfuse==1.4.1,packaging==21.3,pkginfo==1.8.2,platformdirs==2.4.1,pluggy==1.0.0,py==1.11.0,py-cpuinfo==8.0.0,pycparser==2.21,Pygments==2.11.2,pyparsing==3.0.6,pytest==6.2.5,pytest-benchmark==3.4.1,pytest-cov==3.0.0,pytest-forked==1.4.0,pytest-xdist==2.5.0,readme-renderer==32.0,requests==2.27.1,requests-toolbelt==0.9.1,rfc3986==2.0.0,SecretStorage==3.3.1,setuptools-scm==6.4.2,six==1.16.0,toml==0.10.2,tomli==2.0.0,tox==3.24.5,tqdm==4.62.3,twine==3.7.1,urllib3==1.26.8,virtualenv==20.13.0,webencodings==0.5.1,zipp==3.7.0
py3 run-test-pre: PYTHONHASHSEED='1614477403'
py3 run-test: commands[0] | py.test -n 4 -rs --cov=borg --cov-config=.coveragerc --benchmark-skip --pyargs -k test_do_not_fail_when_percent_is_in
====================================================== test session starts =======================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
cachedir: .tox/py3/.pytest_cache
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Tests enabled: fuse, symlinks, hardlinks, atime/mtime, modes
Tests disabled: BSD flags, root
rootdir: /home/user/borg, configfile: setup.cfg
plugins: xdist-2.5.0, benchmark-3.4.1, cov-3.0.0, forked-1.4.0
gw0 [6] / gw1 [6] / gw2 [6] / gw3 [6]
..FF..                                                                                                                     [100%]
============================================================ FAILURES ============================================================
_____________________________ ArchiverTestCaseBinary.test_do_not_fail_when_percent_is_in_xattr_name ______________________________
[gw3] linux -- Python 3.9.9 /home/user/borg/.tox/py3/bin/python

self = <borg.testsuite.archiver.ArchiverTestCaseBinary testMethod=test_do_not_fail_when_percent_is_in_xattr_name>

    @pytest.mark.skipif(not xattr.XATTR_FAKEROOT, reason='xattr not supported on this system or on this version of'
                                                         'fakeroot')
    def test_do_not_fail_when_percent_is_in_xattr_name(self):
        """https://github.com/borgbackup/borg/issues/6063"""
        def patched_setxattr_EACCES(*args, **kwargs):
            raise OSError(errno.EACCES, 'EACCES')
    
        self.create_regular_file('file')
        xattr.setxattr(b'input/file', b'user.attribute%p', b'value')
        self.cmd('init', self.repository_location, '-e' 'none')
        self.cmd('create', self.repository_location + '::test', 'input')
        with changedir('output'):
            with patch.object(xattr, 'setxattr', patched_setxattr_EACCES):
>               self.cmd('extract', self.repository_location + '::test', exit_code=EXIT_WARNING)

src/borg/testsuite/archiver.py:3125: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/borg/testsuite/archiver.py:294: in cmd
    self.assert_equal(ret, exit_code)
E   AssertionError: 0 != 1
------------------------------------------------------ Captured stdout call ------------------------------------------------------

______________________________ ArchiverTestCaseBinary.test_do_not_fail_when_percent_is_in_file_name ______________________________
[gw2] linux -- Python 3.9.9 /home/user/borg/.tox/py3/bin/python

self = <borg.testsuite.archiver.ArchiverTestCaseBinary testMethod=test_do_not_fail_when_percent_is_in_file_name>

    @pytest.mark.skipif(not xattr.XATTR_FAKEROOT, reason='xattr not supported on this system or on this version of'
                                                         'fakeroot')
    def test_do_not_fail_when_percent_is_in_file_name(self):
        """https://github.com/borgbackup/borg/issues/6063"""
        def patched_setxattr_EACCES(*args, **kwargs):
            raise OSError(errno.EACCES, 'EACCES')
    
        os.makedirs(os.path.join(self.input_path, 'dir%p'))
        xattr.setxattr(b'input/dir%p', b'user.attribute', b'value')
        self.cmd('init', self.repository_location, '-e' 'none')
        self.cmd('create', self.repository_location + '::test', 'input')
        with changedir('output'):
            with patch.object(xattr, 'setxattr', patched_setxattr_EACCES):
>               self.cmd('extract', self.repository_location + '::test', exit_code=EXIT_WARNING)

src/borg/testsuite/archiver.py:3141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/borg/testsuite/archiver.py:294: in cmd
    self.assert_equal(ret, exit_code)
E   AssertionError: 0 != 1
------------------------------------------------------ Captured stdout call ------------------------------------------------------


----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name                                        Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------------------------
src/borg/algorithms/__init__.py                 0      0      0      0   100%
src/borg/algorithms/msgpack/__init__.py        32     10     10      1    60%
src/borg/algorithms/msgpack/_version.py         1      0      0      0   100%
src/borg/algorithms/msgpack/exceptions.py      15      3     16      0    90%
src/borg/algorithms/msgpack/fallback.py       704    640    384      3     7%
src/borg/archive.py                          1349    877    580     61    32%
src/borg/archiver.py                         2115   1260    787     56    34%
src/borg/cache.py                             796    347    236     44    53%
src/borg/constants.py                          36      0      0      0   100%
src/borg/crypto/__init__.py                     0      0      0      0   100%
src/borg/crypto/file_integrity.py             147     24     42      5    84%
src/borg/crypto/key.py                        574    311    180     15    45%
src/borg/crypto/keymanager.py                 167    143     52      0    16%
src/borg/crypto/nonces.py                      56     39     18      0    26%
src/borg/helpers.py                          1399    585    569     85    53%
src/borg/locking.py                           269    105    110     14    59%
src/borg/logger.py                            119     44     40      7    60%
src/borg/lrucache.py                           42      8      8      1    78%
src/borg/nanorst.py                           158     70     66     12    54%
src/borg/patterns.py                          197     81     72      6    56%
src/borg/platform/__init__.py                  19      4      4      1    70%
src/borg/platform/base.py                     107     17     20      7    80%
src/borg/remote.py                            623    254    289     55    54%
src/borg/repository.py                       1039    433    398     71    54%
src/borg/selftest.py                           46      7     14      4    82%
src/borg/shellpattern.py                       36     17     22      2    47%
src/borg/upgrader.py                          174    133     60      0    21%
src/borg/version.py                            25     11      8      1    52%
src/borg/xattr.py                             205     82     68     12    55%
-----------------------------------------------------------------------------
TOTAL                                       10450   5505   4053    463    43%

================================================== 2 failed, 4 passed in 41.61s ==================================================
ERROR: InvocationError for command /home/user/borg/.tox/py3/bin/py.test -n 4 -rs --cov=borg --cov-config=.coveragerc --benchmark-skip --pyargs -k test_do_not_fail_when_percent_is_in (exited with code 1)
____________________________________________________________ summary _____________________________________________________________
ERROR:   py3: commands failed
```

**Comment by ThomasWaldmann** [comment]
ah, ok, so you reproduced it. great.

**Pull request merged**
