### PR TITLE
chunker: speed up remainder <= min_size case

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
please review thoroughly!

cases (before this change):

- A) remaining <= window_size

  - would do 2 chunker_fill calls (both line 253) and trigger eof with the 2nd call
  - no buzhashing
  - result is 1 len(remaining) chunk

- B) window_size < remaining <= min_size:

  - the chunker would do 1 chunker_fill call (line 253) that would read the entire remaining file (but not trigger eof yet)
  - would compute all possible remaining - window_size + 1 buzhashes, but without a chance for a cut,
    because there is also the n < min_size condition
  - would do another chunker_fill call (line 282), but not get more data, so loop ends
  - result is 1 len(remaining) chunk

- C) file > min_size:

  - normal chunking

cases (after this change):

- A) similar to above A), but up to remaining <= min_size,
  so it does not buzhash if there is no chance for a cut.

- B) see C) above

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Note: there is another optimization possible. as the cut won't happen before min_size, we do not need to buzhash anything that would trigger an earlier cut --> next commit.

**Comment by ThomasWaldmann** [comment]
Some practical test:
```
(borg-env)tw@tux:~/w/borg$ borg init -e none /extra/repo
(borg-env)tw@tux:~/w/borg$ sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
(borg-env)tw@tux:~/w/borg$ borg create --progress --info --stats --compression lz4 /extra/repo::master ~/w
------------------------------------------------------------------------------                                                                                                                                        
Archive name: master
Archive fingerprint: ba5544d316113c34737e45c701e32f809e1743f2d5b7810c20660e5446d13f15
Time (start): Sun, 2016-05-22 02:02:12
Time (end):   Sun, 2016-05-22 02:13:42
Duration: 11 minutes 29.61 seconds
Number of files: 539771
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               14.75 GB             10.09 GB              7.54 GB
All archives:               14.75 GB             10.09 GB              7.54 GB

                       Unique chunks         Total chunks
Chunk index:                  319929               538964
------------------------------------------------------------------------------

(borg-env)tw@tux:~/w/borg$ borg init -e none /extra/repo
(borg-env)tw@tux:~/w/borg$ sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
(borg-env)tw@tux:~/w/borg$ borg create --progress --info --stats --compression lz4 /extra/repo::nochunksmall ~/w
------------------------------------------------------------------------------                                                                                                                                        
Archive name: nochunksmall
Archive fingerprint: b277e0b9eaf7bd342a5c3fd1acb8d7c088eaf5b83f2bfa9efc679c4198bce5bb
Time (start): Sun, 2016-05-22 02:22:05
Time (end):   Sun, 2016-05-22 02:34:00
Duration: 11 minutes 55.48 seconds
Number of files: 539771
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               14.75 GB             10.09 GB              7.54 GB
All archives:               14.75 GB             10.09 GB              7.54 GB

                       Unique chunks         Total chunks
Chunk index:                  319926               538958
------------------------------------------------------------------------------
```
So, it got slower. WTF?

**Comment by rakajack** [comment]
I see a speedup both on a synthetic test from #1021 (425 MB/s vs 480 MB/s) and real repo.

Though in theory with current CHUNKER_PARAMS (19, 23, 21, 0xfff) speedup should be 25%?

**Comment by enkore** [comment]
There shouldn't be a difference for the synthetic test there, because that's chunking a ~2 GB file, not many small files.

... maybe a few benchmark test cases should be created first. That would make it easier to compare across machines (and compilers), and pytest-benchmark should take care of some details.

**Comment by ThomasWaldmann** [comment]
@enkore for big files, there is a little speedup because if there are N chunks cut, it does not buzhash ~ N * min_size bytes of data. ofc, for files < min_size, it makes a bigger difference as it does not buzhash at all.

**Comment by ThomasWaldmann** [comment]
@rakajack can you post your values for the real repo?

maybe there was just something on my machine influencing the test result (although i tried not to use it otherwise).

merge?

**Comment by rakajack** [comment]
There is a speedup on a repo with big files and no speedup on a repo with small files.


Big files:

borg create --progress --stats --verbose --compression lz4 ./repo::01 ./files_big
------------------------------------------------------------------------------                                               
Archive name: 01
Archive fingerprint: 27fbb902a79707c3dfc17f4c0f0847b655d7a1a758f37f548b2a6c5371ad8cd5
Time (start): Sun, 2016-05-22 22:56:16
Time (end):   Sun, 2016-05-22 22:57:34
Duration: 1 minutes 18.06 seconds
Number of files: 7
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                5.11 GB              4.89 GB              4.78 GB
All archives:                5.11 GB              4.89 GB              4.78 GB

                       Unique chunks         Total chunks
Chunk index:                    1929                 1984
------------------------------------------------------------------------------


borg create --progress --stats --verbose --compression lz4 ./repo::01 ./files_big
------------------------------------------------------------------------------                                               
Archive name: 01
Archive fingerprint: b154d8db361ab1e9701ead731be32110ea015e7d15ed2fde2d7e4773b853ffff
Time (start): Sun, 2016-05-22 22:58:04
Time (end):   Sun, 2016-05-22 22:59:07
Duration: 1 minutes 3.04 seconds
Number of files: 7
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                5.11 GB              4.89 GB              4.78 GB
All archives:                5.11 GB              4.89 GB              4.78 GB

                       Unique chunks         Total chunks
Chunk index:                    1929                 1984
------------------------------------------------------------------------------



Small files

borg create --progress --stats --verbose --compression lz4 ./repo::01 ./files
------------------------------------------------------------------------------                                               
Archive name: 01
Archive fingerprint: b3569cbc72586708bf026c407a44caa2b168ad65e016528c21e8ad89ec6de4b7
Time (start): Sun, 2016-05-22 22:49:55
Time (end):   Sun, 2016-05-22 22:50:55
Duration: 1 minutes 0.08 seconds
Number of files: 26458
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                3.81 GB              2.64 GB              2.45 GB
All archives:                3.81 GB              2.64 GB              2.45 GB

                       Unique chunks         Total chunks
Chunk index:                   14508                27758
------------------------------------------------------------------------------


borg create --progress --stats --verbose --compression lz4 ./repo::01 ./files
------------------------------------------------------------------------------                                               
Archive name: 01
Archive fingerprint: c38ef4a925759932c179f90526d96264df71a3e112b03c835bb57314673d995f
Time (start): Sun, 2016-05-22 22:53:09
Time (end):   Sun, 2016-05-22 22:54:10
Duration: 1 minutes 1.37 seconds
Number of files: 26458
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                3.81 GB              2.64 GB              2.45 GB
All archives:                3.81 GB              2.64 GB              2.45 GB

                       Unique chunks         Total chunks
Chunk index:                   14555                27805
------------------------------------------------------------------------------

**Comment by rakajack** [comment]
With the current patch if c->eof triggers when file size < min_size?

**Comment by ThomasWaldmann** [comment]
@rakajack not sure I understand your question. c->eof is set to True when a read() call returns 0 bytes. For small files, the first read call usually read the whole file, the 2nd read call returns 0 bytes.

**Pull request merged**
