### PR TITLE
add --json-lines option to diff command

### PR DESCRIPTION
**Pull request by rblenis**
fix issue #3765

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Please tell me when this is in sync with the already merged 1.1-maint PR #5710.

**Comment by ThomasWaldmann** [comment]
So, this is just a forward-port of the merged 1.1-maint changeset?

**Comment by rblenis** [comment]
yes. all the diff engine stuff moved to item.pyx, so comparing to 1.1.x is a pain. Also, just remembered - it looks like a number of the asserts in testsuite/archiver.py are changed to self.assert_in(), ...  (or are new tests). Looks like to give better failure messages.  Not all of the asserts in that file have been changed. Should I make use of the 'better' (newer) assert plumbing in the diff tests? And if so, should I add a task of perhaps cleaning up all the test code to use the new plumbing?

**Comment by rblenis** [comment]
Also, when I submit a PR, should I also include changes in the changelog, or is the changelog updated by whoever starts the release build?

**Comment by ThomasWaldmann** [comment]
- using `self.assert_xxx` methods is unittest style - this should be only used for specific tests that are run within borg's self-test. usually we use the more comfortable pytest style which is just `assert ...`.
- no need to update changes.rst, i do that when releasing. but doing good commit comments is helpful, so i can use them for the changelog.

**Comment by rblenis** [comment]
When are borg's self-tests run? Is there some documentation on this?  Should selftest(unittest) be mixed in the same file (or even same class) as pytest? - cause that's happening in testsuite/archiver.py, yet some comments in other files seem to indicate not to mix in the same file. Should unittest be organized in a different folder? A lot of questions - I need to investigate a little more.

**Comment by ThomasWaldmann** [comment]
For the self tests, there's a list and a count somewhere. They always run when borg starts.

**Comment by ThomasWaldmann** [comment]
So, is there anything left to do here?

**Comment by rblenis** [comment]
all done.

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
