### PR TITLE
incremental repo check

### LINKED ISSUE #1657: Incremental repository check
E.g. `borg check [--repository-only] --incremental`. Checks all data since last borg check --incremental invocation. Saves last checked segment into the repository config, continues from there when called again.

Guess this could be extended to archives as well by storing the last --incremental timestamp in the manifest.

bounty: https://www.bountysource.com/issues/38004309-incremental-repository-check

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
fixes #1657.

### CODE REVIEW

**Comment by textshell** [comment]
From a short look this looks good.

I'd prefer not to write to config for non critical operations. But that would complicate the code a lot. But if users are going to check a repo there might actually be some storage breakage which this could make even worse. (one way to do that would be to have an auxiliary file that is like config and that stores all keys outside of a manually maintained critical set)

**Comment by ThomasWaldmann** [comment]
True.

But otoh the only really critical thing in the config is the key (in repokey modes) and we advise to have a key backup.

Also, the config is not directly overwritten, but first written to a tmp name and then renamed over the previous config (plus some syncs).

**Comment by textshell** [comment]
Yes they are both true. But i think i explicitly ruled out using config for nounce because i wanted to avoid having frequently changing information in config.

And yes, that key is primarily what we want to protect. And maybe the structure so borg still recognizes the directory are repo.

**Comment by ThomasWaldmann** [comment]
I'm merging this as is now and will open a ticket about separating config into 2.

**Comment by ThomasWaldmann** [comment]
see #4428.

**Pull request merged**
