### PR TITLE
sdist: remove *.so/*.dll

### LINKED ISSUE #2066: binaries in pypi package
Just noticed that when there are binaries (*.so) below src/borg, they will end up in the pypi package when running `python setup.py sdist`.

Is that new? Are we expected to exclude them in MANIFEST.in?

### PR DESCRIPTION
**Pull request by enkore**
Fixes #2066

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
i already fixed it in my local release branch, please don't merge to avoid conflicts.

**Comment by enkore** [comment]
Ok

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/2070/commits/d67cc229f660731b2e90046b75e4e2ed34cd60c8#r96144402 < see there

**Comment by ThomasWaldmann** [comment]
@enkore can you fix it for / rebase it on 1.0-maint?

**Comment by ThomasWaldmann** [comment]
see #2089.

**Pull request closed without merging**
