### PR TITLE
Added shell completions for borg help

### PR DESCRIPTION
**Pull request by SanskritFritz**
Hi, I just realised borg has a help command. So I created shell completions for bash / zsh / fish as usual.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
btw, borg recently got a `--rsh` option and for borg init a `--make-parent-dirs` (or so), see master and 1.1-maint and changes.rst there.

**Comment by SanskritFritz** [comment]
Thanks for the heads-up, I completely missed that. Will send a PR as soon as I'm ready with those changes.

**Comment by ThomasWaldmann** [comment]
OK, so just tell me when you think this PR is finished.

**Comment by ThomasWaldmann** [comment]
(and we'll also need a backport of this to 1.1-maint after it is finished)

**Comment by ThomasWaldmann** [comment]
btw, focus on 1.1 changes first, i want to release 1.1.9 ASAP / RSN.

**Comment by SanskritFritz** [comment]
OK, I'll ask some questions on the IRC. Will take some days though.
Do you want me to update this PR then?

**Comment by ThomasWaldmann** [comment]
If it is taking longer, then please split it into different PRs and finish first ones first and esp. 1.1-maint first.

**Comment by SanskritFritz** [comment]
OK, what's the deadline?

**Comment by ThomasWaldmann** [comment]
Sat/Sun, not later. I try to resolve the FUSE tickets and then I'll do a 1.1.9 release.

**Comment by SanskritFritz** [comment]
OK, I'll see what I can do.

**Comment by SanskritFritz** [comment]
I close this, because #4334 supersedes it.

**Pull request closed without merging**
