### PR TITLE
Support repositories in fish tab completion

### PR DESCRIPTION
**Pull request by SanskritFritz**
Now that soon we'll have awesome zsh completions, it is time to make fish completions more awesome.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
similar here: can we have a better commit comment?

i guess it can now complete archives by looking into the repo.
does it also complete repos if they are local dirs? but not if they are remote ssh:// repos, right?

**Comment by SanskritFritz** [comment]
Completing archives was already supported. This rewrite allows completion of local directories as repositories and offers ssh hosts as possible remote locations.
How do I change the commit comment?

**Comment by ThomasWaldmann** [comment]
I usually use something like `git rebase -i BASEBRANCH` to do all sorts of changes, including **r**ewording of commit comments.

**Comment by SanskritFritz** [comment]
I don't know if that is OK now, there are 3 commits now o_O
I can start it all over if you want to.

**Comment by ThomasWaldmann** [comment]
I've squashed the commits together, thanks!

**Comment by ThomasWaldmann** [comment]
Added a backport to 1.1-maint label here, as discussed in #5255. Be careful, this is stable branch,

**Comment by ThomasWaldmann** [comment]
guess this is one of the last pieces missing for 1.1.14.

**Comment by SanskritFritz** [comment]
Sorry I misunderstood you earlier, I thought you did the backport. Hang on, I'm on it, just a little later today.

**Comment by ThomasWaldmann** [comment]
Would be great if you could do it, I am not familiar with the completion stuff.

**Pull request merged**
