### PR TITLE
Vagrantfile: Fix set-up of cygwin and it's sshd.

### LINKED ISSUE #2609: vagrant: windows10 + cygwin broken
Our windows 10 cygwin testing machine is broken:
```
$ vagrant up windows10
Bringing machine 'windows10' up with 'virtualbox' provider...
...
==> windows10: Running provisioner: packages cygwin (shell)...
    windows10: Running: inline script
==> windows10: 
==> windows10: C:\cygwin>REM --- Change to use different CygWin platform and final install path 
==> windows10: 
==> windows10: C:\cygwin>set CYGSETUP=setup-x86_64.exe 
==> windows10: 
==> windows10: C:\cygwin>REM --- Install build version of CygWin in a subfolder 
==> windows10: 
==> windows10: C:\cygwin>set OURPATH=C:\cygwin 
==> windows10: 
==> windows10: C:\cygwin>set CYGBUILD="C:\cygwin\CygWin" 
==> windows10: 
==> windows10: C:\cygwin>set CYGMIRROR=ftp://mirrors.kernel.org/sourceware/cygwin/ 
==> windows10: 
==> windows10: C:\cygwin>set BASEPKGS=openssh,rsync 
==> windows10: 
==> windows10: C:\cygwin>set BUILDPKGS=python3,python3-setuptools,python-devel,binutils,gcc-g++,libopenssl,openssl-devel,git,make,liblz4-devel,liblz4_1,curl 
==> windows10: 
==> windows10: C:\cygwin>setup-x86_64.exe -q -B -o -n -R "C:\cygwin\CygWin" -L -D -s ftp://mirrors.kernel.org/sourceware/cygwin/ -P openssh,rsync,python3,python3-setuptools,python-devel,binutils,gcc-g++,libopenssl,openssl-devel,git,make,liblz4-devel,liblz4_1,curl 
==> windows10: Starting cygwin install, version 2.879
(lots of downloads)
...
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/noarch/release/base-cygwin/base-cygwin-3.8-1.tar.xz
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/cygrunsrv/cygrunsrv-1.62-1.tar.xz
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/cygutils/cygutils-1.4.15-2.tar.xz
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/cygwin/cygwin-2.8.0-1.tar.xz
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/cygwin/cygwin-devel/cygwin-devel-2.8.0-1.tar.xz
...
==> windows10: Extracting from file://C:\cygwin/ftp%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/openssh/openssh-7.5p1-1.tar.xz
...
(postinstall)
==> windows10: Ending cygwin install
==> windows10: 
==> windows10: C:\cygwin>cd /d C:\cygwin\CygWin\bin 
==> windows10: 
==> windows10: C:\cygwin\CygWin\bin>regtool set /HKLM/SYSTEM/CurrentControlSet/Services/OpenSSHd/ImagePath "C:\cygwin\CygWin\bin\cygrunsrv.exe" 
==> windows10: 
==> windows10: C:\cygwin\CygWin\bin>bash -c "ssh-host-config --no" 
==> windows10: /usr/share/csih/cygwin-service-installation-helper.sh: line 761: grep: command not found
==> windows10: /cygdrive/c/Program Files/OpenSSH/bin/ssh-host-config: line 53: cd: too many arguments
==> windows10: *** Info: Generating missing SSH host keys
==> windows10: ssh-keygen: generating new host keys: RSA 
==> windows10: DSA 
==> windows10: ECDSA 
==> windows10: ED25519 
==> windows10: *** Info: Creating default /etc/ssh_config file
==> windows10: *** Info: Creating default /etc/sshd_config file
==> windows10: 
==> windows10: *** Info: StrictModes is set to 'yes' by default.
==> windows10: *** Info: This is the recommended setting, but it requires that the POSIX
==> windows10: *** Info: permissions of the user's home directory, the user's .ssh
==> windows10: *** Info: directory, and the user's ssh key files are tight so that
==> windows10: *** Info: only the user has write permissions.
==> windows10: *** Info: On the other hand, StrictModes don't work well with default
==> windows10: *** Info: Windows permissions of a home directory mounted with the
==> windows10: *** Info: 'noacl' option, and they don't work at all if the home
==> windows10: *** Info: directory is on a FAT or FAT32 partition.
==> windows10: *** Query: Should StrictModes be used? (yes/no) no
==> windows10: 
==> windows10: *** Info: Privilege separation is set to 'sandbox' by default since
==> windows10: *** Info: OpenSSH 6.1.  This is unsupported by Cygwin and has to be set
==> windows10: *** Info: to 'yes' or 'no'.
==> windows10: *** Info: However, using privilege separation requires a non-privileged account
==> windows10: *** Info: called 'sshd'.
==> windows10: *** Info: For more info on privilege separation read /usr/share/doc/openssh/README.privsep.
==> windows10: *** Query: Should privilege separation be used? (yes/no) no
==> windows10: *** Info: Updating /etc/sshd_config file
==> windows10: /cygdrive/c/Program Files/OpenSSH/bin/ssh-host-config: line 92: cygpath: command not found
==> windows10: *** Query: Do you want to install sshd as a service?
==> windows10: *** Query: (Say "no" if it is already installed as a service) (yes/no) no
==> windows10: 
==> windows10: *** Info: Host configuration finished. Have fun!
==> windows10: 
==> windows10: SUCCESS: Specified value was saved.
==> windows10: Running provisioner: reload...
==> windows10: Attempting graceful shutdown of VM...
==> windows10: Checking if box 'Microsoft/EdgeOnWindows10' is up to date...
==> windows10: Clearing any previously set forwarded ports...
==> windows10: Fixed port collision for 22 => 2222. Now on port 2201.
==> windows10: Clearing any previously set network interfaces...
==> windows10: Preparing network interfaces based on configuration...
    windows10: Adapter 1: nat
==> windows10: Forwarding ports...
    windows10: 22 (guest) => 2201 (host) (adapter 1)
==> windows10: Running 'pre-boot' VM customizations...
==> windows10: Booting VM...
==> windows10: Waiting for machine to boot. This may take a few minutes...
    windows10: SSH address: 127.0.0.1:2201
    windows10: SSH username: IEUser
    windows10: SSH auth method: password
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### PR DESCRIPTION
**Pull request by htgoebel**
Fixes #2609.

### CODE REVIEW

**Comment by htgoebel** [comment]
Sorry, this is incomplete! Please wait some hours, I'll update the pull-request.

**Comment by ThomasWaldmann** [comment]
thanks @htgoebel!

**Comment by ThomasWaldmann** [comment]
@htgoebel btw, did you solve that locally?:

```
==> windows10: The machine you're rsyncing folders to is configured to use
==> windows10: password-based authentication. Vagrant can't script rsync to automatically
==> windows10: enter this password, so you'll likely be prompted for a password
==> windows10: shortly.
==> windows10: 
==> windows10: If you don't want to have to do this, please enable automatic
==> windows10: key insertion using `config.ssh.insert_key`.
==> windows10: Rsyncing folder: /home/tw/w/borg/ => /vagrant/borg/borg
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir '/vagrant/borg/borg'

Stdout from the command:



Stderr from the command:

mkdir: cannot create directory '/vagrant/borg/borg': No such file or directory
```

I don't get prompted for a password.

**Comment by ThomasWaldmann** [comment]
If I then do vagrant rsync and vagrant provision, it continues (and later prompts for a password).

**Comment by ThomasWaldmann** [comment]
Later, it fails when trying to build Cython due to a missing / not found Python.h.

**Comment by htgoebel** [comment]
@ThomasWaldmann For the PyInstaller machines I moved away from rsync. Vagrant 1.9.5 now supports synced folders on windows. See my current changes on https://github.com/pyinstaller/pyinstaller/pull/2415

> mkdir: cannot create directory '/vagrant/borg/borg': No such file or directory

Looks like an error in Vagrant, which ought to use `mkdir -p` – OTOH, MLS-OpenSSH's `mkdir` might be to crippled.

**Comment by ThomasWaldmann** [comment]
@htgoebel I'ld prefer the data exchange being only host -> vm, not vice versa. I don't fully trust the VMs.

**Pull request merged**
