### PR TITLE
Added Salt example to documentation

### PR DESCRIPTION
**Pull request by icefoxen**
It has more or less the same functionality as the Ansible example, though isn't a line-by-line translation.

It's also tested on a Debian system, but if you want I can rewrite it for Arch; the only real change will be the install lines.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Hopefully we do not need to extend that to N different deployment systems...

Opinions about merging this?

**Comment by edgewood** [comment]
Move both Ansible and Salt sections to a new deployment.rst in borgcommunity, and link them there?
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.


-------- Original Message --------

**Comment by enkore** [comment]
+1

**Comment by ThomasWaldmann** [comment]
I am merging this now, but reserve the right to move all different deployment tools howtos out from main docs later maybe. ;)

**Pull request merged**
