### PR TITLE
Documentation: Fix literate code markup

### PR DESCRIPTION
**Pull request by nomeata**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Good find, thanks!

But the stuff needs to get changed in the code. The stuff you see in .rst.inc files is taken from the builtin help of borg, so it has to be changed there (see archiver.py) and the .rst.inc files will automatically get it.

Also, the PR should be against 1.0-maint, so it gets fixed there and also later gets merged into master.

**Comment by nomeata** [comment]
Oh, you have generated files in the git repository? How nasty :-)

**Comment by nomeata** [comment]
I’ll open a new PR against 1.0-maint.

**Comment by ThomasWaldmann** [comment]
It was less nasty than generating them on readthedocs / via setup.py.

**Pull request closed without merging**
