### PR TITLE
add Key/EncryptedKey PropDict, see #1157

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by enkore** [comment]
Hmm, shouldn't the two PropDict classes be in borg.key, since they aren't and shouldn't be used globally?

**Comment by ThomasWaldmann** [comment]
@enkore yes, I'll move stuff around when I am finished with all the PropDicts. The docstring of them need more work, so I want to have them at same place now.

**Comment by enkore** [comment]
ok

**Pull request merged**
