### PR TITLE
xattr: dynamically grow result buffer until it fits, fixes #1462

### LINKED ISSUE #1462: Crash: listxattr failed
(Same issue as https://github.com/jborg/attic/issues/120 it seems, very similar traceback.)

Borg (1.0.6-2~ubuntu14.04.1~ppa1) failed just now. From xfs to xfs (on same file system), on Ubuntu 14.04 trusty. Of my five directories (each a separate archive, same repo) only one worked. Yesterday all five worked.
Example failure:
``` 
borg create -v --show-rc --stats -C lz4 /data/store/borg::Public-20160810 /data/Public
Enter passphrase for key /data/store/borg:
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1609, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1546, in run
    return args.func(args)
File "/usr/lib/python3/dist-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 247, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 219, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process     read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 275, in _process
     status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 683, in process_file
    item.update(self.stat_attrs(st, path))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 573, in stat_attrs
    xattrs = xattr.get_all(path, follow_symlinks=False)
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 31, in get_all
    for name in listxattr(path, follow_symlinks=follow_symlinks))
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 115, in listxattr
    raise Exception('listxattr failed')
Exception: listxattr failed

Platform: Linux brain2 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64
Linux: Ubuntu 14.04 trusty
Borg: 1.0.6  Python: CPython 3.4.3
PID: 21726  CWD: /home/administrator
sys.argv: ['/usr/bin/borg', 'create', '-v', '--show-rc', '--stats', '-C', 'lz4', '/data/store/borg::Public-20160810', '/data/Public']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
this also fixes the race condition seen in #1462 because there is only 1 call now.
either it succeeds, then we get the correct length as result and truncate the result value to that length.
or it fails with ERANGE, then we grow the buffer to double size and repeat.
or it fails with some other error, then we throw OSError.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Some of the changes could be taken to the lz4 buffer code.

**Comment by enkore** [comment]
Logic and tests look sound to me. An upper bound is imho not needed, since this is a system-returned value.

**Comment by ThomasWaldmann** [comment]
Running tests on freebsd64 for this right now...

Besides collapsing the fixups, anything else to do before merge?

**Comment by enkore** [comment]
lgtm. Changelog:

- Fixed a race condition in extended attributes querying that led to the entire file not being backed up (while logging the error, exit code = 1), #1469
- Fixed a race condition in extended attributes querying that led to a crash, #1462

**Comment by ThomasWaldmann** [comment]
changelog updated, merge after travis is happy...

**Pull request merged**
