### PR TITLE
rename local preload() function to not overwrite keyword argument of same name

### PR DESCRIPTION
**Pull request by elho**
The locally defined preload() function overwrites the preload boolean keyword
argument, always evaluating to true, so preloading is done, even when not
requested by the caller, causing a memory leak.
Also move its definition outside of the loop.

This issue was found by Antonio Larrosa in borg issue #5202.

### CODE REVIEW

**Comment by elho** [comment]
I built a borg 1.2 from this branch and then did some real world tests with it.
I initialized a new repo and created a backup of about 490 GB of data using ZSTD compression. The resulting repo has a deduplicated size of 231.23 GB in 602418 unique chunks.
I then recreated (using `--target`) the archive to a new one omitting 2 large files and a large directory containing various Debion ISO files.
I generated checksums of the original files using `xxh64sum` and of the original and recreated archives using `borg list --format '{linktarget}@{type}@{xxh64}  {path}{NL}' REPO::ARCHIVE | sed --quiet --expression='s/^@-@//p' and diffed those. Except for the files intentionally excluded in the recreate all files and checksums matched.
A `xxh64sum --quiet --check` on a `borg mount` of the recreated repository succeeded as well.

**Comment by elho** [comment]
I also built a borg 1.1.11 with this patch added (in addition to my compression fix and xxh64 list format ones) and did `borg list --format '{linktarget}@{type}@{xxh64} {path}{NL}' REPO::ARCHIVE | sed --quiet --expression='s/^@-@//p'` on this LZMA compressed archive sitting on gigabit ethernet connected server:

```
Number of files: 1568678
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                7.35 TB              6.85 TB             86.99 MB
All archives:              287.06 TB            257.60 TB              6.24 TB

                       Unique chunks         Total chunks
Chunk index:                 4532205            186711710
```
Using borg without this patch ended up being killed by the OOM-killer eventually (the system has 64 GB RAM & 128 GB swap).
`time -v` excerpt:
```
        User time (seconds): 37438.20
        System time (seconds): 2070.22
        Elapsed (wall clock) time (h:mm:ss or m:ss): 11:04:54
        Maximum resident set size (kbytes): 61200412
        Major (requiring I/O) page faults: 86752
        Minor (reclaiming a frame) page faults: 395355553
        Exit status: 2
```
Using borg with this patch is still running, but works fine so far, it output more lines than above one, but hardly uses any memory, according to `/proc/PID/status`:
```
VmPeak:   180880 kB
VmHWM:    155724 kB

```

**Comment by elho** [comment]
@ThomasWaldmann Given you added the backport/1.1-maint tag, I take it you want me to do another PR against maint-1.1 branch? :slightly_smiling_face:

**Comment by ThomasWaldmann** [comment]
@elho if you have time, that would be nice. if not, i can also do it.

we need it there for sure. :-)

**Comment by ThomasWaldmann** [comment]
also, i guess we have enough good stuff for a 1.1.12, so i'll do that release asap.

**Comment by elho** [comment]
> Using borg without this patch ended up being killed by the OOM-killer eventually (the system has 64 GB RAM & 128 GB swap).
> `time -v` excerpt:
> 
> ```
>         User time (seconds): 37438.20
>         System time (seconds): 2070.22
>         Elapsed (wall clock) time (h:mm:ss or m:ss): 11:04:54
>         Maximum resident set size (kbytes): 61200412
>         Major (requiring I/O) page faults: 86752
>         Minor (reclaiming a frame) page faults: 395355553
>         Exit status: 2
> ```
> 
> Using borg with this patch is still running, [...]

It completed successfully by now, here is the same `time -v` excerpt:
```
        User time (seconds): 194957.69
        System time (seconds): 9239.83
        Elapsed (wall clock) time (h:mm:ss or m:ss): 58:51:16
        Maximum resident set size (kbytes): 163580
        Major (requiring I/O) page faults: 673
        Minor (reclaiming a frame) page faults: 29660167
        Exit status: 0
```
So, as expected, a considerably reduced memory usage. :smiley:

**Pull request merged**
