### PR TITLE
Fix --progress option.

### PR DESCRIPTION
**Pull request by Gu1nness**
When called with --progress, the progress was always showing
0 B O 0 B C 0 B D 0 N.

This is fixed by this commit.

Fixes https://github.com/borgbackup/borg/issues/3431

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/3557/files#diff-48f2b9140a35ffd45a46ccfbe63931a6R487

have a look there ^ - this looks wrong now as you use the archive.stats instance all the time already.

maybe do a validity check of the numbers you see in --progress and --stats, whether they are as expected (just compare to borg 1.1).

**Comment by ThomasWaldmann** [comment]
still there?

**Comment by ThomasWaldmann** [comment]
can you rebase on master, so only your changes show up here?

**Comment by ThomasWaldmann** [comment]
@enkore besides the minor problem I have pointed out above, is this the right way to fix?

**Comment by Gu1nness** [comment]
Hi, sorry for the long delay.
I have just pushed a new and patched version.
The tricky thing was about bounded class method (`add_item`)
Hope this patch will be okay for you

**Comment by enkore** [comment]
I guess so

**Comment by ThomasWaldmann** [comment]
@Gu1nness thanks for the PR. it needed a small fix, see #3681.

**Comment by Gu1nness** [comment]
My bad, I had missed this one.
Sorry for the small error.

**Comment by ThomasWaldmann** [comment]
No problem. :)

**Pull request merged**
