### PR TITLE
Zstd update

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by jungle-boogie** [comment]
Nice work, thanks!

Looking forward to zstd with borgbackup.

**Comment by ThomasWaldmann** [comment]
@jungle-boogie we have zstd since borg 1.1.4, this is just updating to the newer zstd release which is a bit faster.

It only matters if the bundled zstd code is used. Linux maintainers likely disable this for the sake of better package maintenance via a separate zstd library package.

**Comment by jungle-boogie** [comment]
hi @ThomasWaldmann,

https://www.borgbackup.org

`Compression: LZ4, zlib, LZMA.`

Is zlib zstd?

**Comment by ThomasWaldmann** [comment]
No, zlib == .gz (and rather old).

zstd = fancy new compression stuff.

**Comment by ThomasWaldmann** [comment]
TODO: platform testing

**Pull request merged**
