### PR TITLE
Update link to security contact

### PR DESCRIPTION
**Pull request by musoke**
Information about security contact seems to have moved.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for fixing this!

**Comment by enkore** [comment]
Thanks for the patch, but it's actually not quite correct. Since master is currently not stable the link goes to nil, but as soon as there is a stable release from the master development branch the link becomes correct.

**Comment by ThomasWaldmann** [comment]
@enkore is right - @musoke can you do it like that?

**Comment by ThomasWaldmann** [comment]
@musoke still there?

**Comment by musoke** [comment]
@ThomasWaldmann - sorry, I shouldn't submit pull requests immediately before going AFK for a month.

@enkore, thanks for fixing it.

**Pull request merged**
