### PR TITLE
Shell completions reflect latest changes

### PR DESCRIPTION
**Pull request by SanskritFritz**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
lgtm (didn't test it though) - merge or are you still working on it?

**Comment by SanskritFritz** [comment]
Yup, you may merge it, I have tested them all, that is why I sent this PR.

**Comment by SanskritFritz** [comment]
I might work on it later some more, maybe I'll try to expand the config keys for ```borg config``` now that we have --list. But that is low priority.

**Comment by ThomasWaldmann** [comment]
thanks!

**Pull request merged**
