### PR TITLE
add notice about defective hardware to check documentation (#5753)

### PR DESCRIPTION
**Pull request by braewoods**
This is the back-port of #5855 for #5129.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
this needs to be done in archiver.py.

**Comment by braewoods** [comment]
This should cover that. It now includes both documentation patches.

**Comment by ThomasWaldmann** [comment]
something got mixed up now...

**Comment by braewoods** [comment]
Ugh. I'll try to fix it.

**Comment by braewoods** [comment]
That should do it.

**Pull request merged**
