### PR TITLE
Fixed borg info

### PR DESCRIPTION
**Pull request by joaocsf**
Issue #1914 fixed.
Ran all the tests, everything seems allright.
Probably the same problem in 1.0-maint.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
change looks good, thanks! but the PR should go against 1.0-maint branch IF the problem also exists in 1.0-maint. It will get merged automatically from there into master later.

**Comment by ThomasWaldmann** [comment]
also, please have a good commit comment.

**Comment by joaocsf** [comment]
I have tested the same fix in the 1.0-maint branch and it seems this version doesn't support repository information (only archives). If you specify the archive, it works as expected, even with the BORG_REPO set eg: `borg info ::archive`.

**Comment by ThomasWaldmann** [comment]
@joaocsf ah, right. ok, so master is fine.

**Comment by ThomasWaldmann** [comment]
Thanks for fixing this. Check #1915 also.

**Pull request merged**
