### PR TITLE
replace `LRUCache` internals with `OrderedDict`

### PR DESCRIPTION
**Pull request by Deric-W**
Hello,
while looking trough the code I noticed that `LRUCache` is using custom logic to keep track of ordering which handles the `list` operations not very efficiently.
Since `OrderedDict` is implemented in C it should provide a speedup and allow for a simpler implementation.

I tried to run the tests on my machine but `conftest.py` fails to parse the version made up by setuptools-scm.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Deric-W thanks for the PR. That issue with setuptools-scm is likely because you made a shallow copy of the git repo or a copy without the tags. Just pull the full history / the tags.

**Comment by ThomasWaldmann** [comment]
@Deric-W btw, did you check if you can use dict instead of OrderedDict? Since python 3.7, dicts remember order.

**Comment by ThomasWaldmann** [comment]
@Deric-W `black` is unhappy still, you should install `black` and run it on the source (see developer docs).

**Comment by Deric-W** [comment]
While the [documentation](https://docs.python.org/3/library/collections.html#ordereddict-objects) shows how to use a normal dict for this purpose it mentions that `OrderedDict` is more efficient in this case which a can confirm after testing the snippets with timeit.

**Review by ThomasWaldmann — CHANGES_REQUESTED** [review]
Code looks good, thanks!

The docstring is a bit confusing and its usage of "replacing" could be misunderstood to refer to the "replace" method.

**Review by ThomasWaldmann — APPROVED** [review]
LGTM!

**Pull request merged**
