### PR TITLE
PropDict: fail early if internal_dict is not a dict [1.1]

### PR DESCRIPTION
**Pull request by samuel-w**
Backport of https://github.com/borgbackup/borg/pull/5496
I may have broken the metadata.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
can you rebase on current master? iirc the caskroom stuff is fixed there.

**Comment by samuel-w** [comment]
It's fixed by https://github.com/borgbackup/borg/pull/5542.

**Comment by ThomasWaldmann** [comment]
done (sorry, confused branches).

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
