### PR TITLE
pass meta-data around, fixes #765

### LINKED ISSUE #765: pass around metadata
in borg, there is a flow of data through the different stages / layers, but metadata of files / of content is missing mostly. we could use a metadata dict and pass it around with the data, e.g. as a tuple (meta, data).

e.g. currently, the compression component is statically set up, you choose it via commandline param.
it could be that an entry in the meta dict determines the compression that will be used.
the entry could default to whatever commandline says, but it could also be changed dynamically (e.g. if the file reader knows it is .mp3 and can't be compressed, so it sets meta["compression"]='none' for that data).

e.g. it could be also used for sparse files, so hole=True/False can get passed around.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Chunk is a namedtuple of (meta, data), create chunks using mkchunk(data, **meta).

This does not yet have any visible functionality, meta is always empty dict right now.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
todo: collapse after review

**Comment by enkore** [comment]
I still think that it's kinda ugly to have mkchunk as such a thin wrapper /factory around a class constructor. Here's a patch that uses a namedtuple subclass to the same effect. Alternatively we could just rename mkchunk -> Chunk.

``
diff --git a/borg/archive.py b/borg/archive.py
index 67f45fc..c4b4a50 100644
--- a/borg/archive.py
+++ b/borg/archive.py
@@ -18,7 +18,7 @@ from io import BytesIO
 from . import xattr
 from .compress import Compressor, COMPR_BUFFER
 from .constants import *  # NOQA
-from .helpers import mkchunk, Error, uid2user, user2uid, gid2group, group2gid, \
+from .helpers import Chunk, Error, uid2user, user2uid, gid2group, group2gid, \
     parse_timestamp, to_localtime, format_time, format_timedelta, \
     Manifest, Statistics, decode_dict, make_path_safe, StableDict, int_to_bigint, bigint_to_int, \
     ProgressIndicatorPercent, ChunkIteratorFileWrapper, remove_surrogates, log_multi, \
@@ -87,7 +87,7 @@ class ChunkBuffer:
         if self.buffer.tell() == 0:
             return
         self.buffer.seek(0)
-        chunks = list(mkchunk(bytes(s)) for s in self.chunker.chunkify(self.buffer))
+        chunks = list(Chunk(bytes(s)) for s in self.chunker.chunkify(self.buffer))
         self.buffer.seek(0)
         self.buffer.truncate(0)
         # Leave the last partial chunk in the buffer unless flush is True
@@ -263,7 +263,7 @@ Number of files: {0.stats.nfiles}'''.format(
         metadata.update(additional_metadata or {})
         data = msgpack.packb(StableDict(metadata), unicode_errors='surrogateescape')
         self.id = self.key.id_hash(data)
-        self.cache.add_chunk(self.id, mkchunk(data), self.stats)
+        self.cache.add_chunk(self.id, Chunk(data), self.stats)
         self.manifest.archives[name] = {'id': self.id, 'time': metadata['time']}
         self.manifest.write()
         self.repository.commit()
@@ -450,7 +450,7 @@ Number of files: {0.stats.nfiles}'''.format(
         metadata[key] = value
         data = msgpack.packb(metadata, unicode_errors='surrogateescape')
         new_id = self.key.id_hash(data)
-        self.cache.add_chunk(new_id, mkchunk(data), self.stats)
+        self.cache.add_chunk(new_id, Chunk(data), self.stats)
         self.manifest.archives[self.name] = {'id': new_id, 'time': metadata[b'time']}
         self.cache.chunk_decref(self.id, self.stats)
         self.id = new_id
@@ -534,7 +534,7 @@ Number of files: {0.stats.nfiles}'''.format(
         fd = sys.stdin.buffer  # binary
         chunks = []
         for data in self.chunker.chunkify(fd):
-            chunks.append(cache.add_chunk(self.key.id_hash(data), mkchunk(data), self.stats))
+            chunks.append(cache.add_chunk(self.key.id_hash(data), Chunk(data), self.stats))
         self.stats.nfiles += 1
         t = int_to_bigint(int(time.time()) * 1000000000)
         item = {
@@ -591,7 +591,7 @@ Number of files: {0.stats.nfiles}'''.format(
             with os.fdopen(fh, 'rb') as fd:
                 chunks = []
                 for data in self.chunker.chunkify(fd, fh):
-                    chunks.append(cache.add_chunk(self.key.id_hash(data), mkchunk(data), self.stats))
+                    chunks.append(cache.add_chunk(self.key.id_hash(data), Chunk(data), self.stats))
                     if self.show_progress:
                         self.stats.show_progress(item=item, dt=0.2)
             cache.memorize_file(path_hash, st, [c.id for c in chunks])
@@ -797,7 +797,7 @@ class ArchiveChecker:
                     self.error_found = True
                     data = bytes(size)
                     chunk_id = self.key.id_hash(data)
-                    cdata = self.key.encrypt(mkchunk(data))
+                    cdata = self.key.encrypt(Chunk(data))
                     csize = len(cdata)
                     add_reference(chunk_id, size, csize, cdata)
                 else:
@@ -893,7 +893,7 @@ class ArchiveChecker:
                 archive[b'items'] = items_buffer.chunks
                 data = msgpack.packb(archive, unicode_errors='surrogateescape')
                 new_archive_id = self.key.id_hash(data)
-                cdata = self.key.encrypt(mkchunk(data))
+                cdata = self.key.encrypt(Chunk(data))
                 add_reference(new_archive_id, len(data), len(cdata), cdata)
                 info[b'id'] = new_archive_id
 
@@ -1082,7 +1082,7 @@ class ArchiveRecreater:
 
             def _chunk_iterator():
                 for data in target.chunker.chunkify(file):
-                    yield mkchunk(data)
+                    yield Chunk(data)
 
             chunk_iterator = _chunk_iterator()
         return chunk_iterator
diff --git a/borg/helpers.py b/borg/helpers.py
index c079af9..0cfbe32 100644
--- a/borg/helpers.py
+++ b/borg/helpers.py
@@ -38,11 +38,12 @@ import socket
 
 
 # meta dict, data bytes
-Chunk = namedtuple('Chunk', 'meta data')
+ChunkBase = namedtuple('ChunkBase', 'meta data')
 
 
-def mkchunk(data, **meta):
-    return Chunk(meta, data)
+class Chunk(ChunkBase):
+    def __new__(cls, data, **meta):
+        return super().__new__(cls, meta, data)
 
 
 class Error(Exception):
@@ -122,7 +123,7 @@ class Manifest:
             'config': self.config,
         }))
         self.id = self.key.id_hash(data)
-        self.repository.put(self.MANIFEST_ID, self.key.encrypt(mkchunk(data)))
+        self.repository.put(self.MANIFEST_ID, self.key.encrypt(Chunk(data)))
 
     def list_archive_infos(self, sort_by=None, reverse=False):
         # inexpensive Archive.list_archives replacement if we just need .name, .id, .ts
diff --git a/borg/key.py b/borg/key.py
index aa0e721..124376d 100644
--- a/borg/key.py
+++ b/borg/key.py
@@ -7,7 +7,7 @@ import textwrap
 from hmac import compare_digest
 from hashlib import sha256, pbkdf2_hmac
 
-from .helpers import mkchunk, IntegrityError, get_keys_dir, Error, yes
+from .helpers import Chunk, IntegrityError, get_keys_dir, Error, yes
 from .logger import create_logger
 logger = create_logger()
 
@@ -111,7 +111,7 @@ class PlaintextKey(KeyBase):
         data = self.compressor.decompress(memoryview(data)[1:])
         if id and sha256(data).digest() != id:
             raise IntegrityError('Chunk id verification failed')
-        return mkchunk(data)
+        return Chunk(data)
 
 
 class AESKeyBase(KeyBase):
@@ -157,7 +157,7 @@ class AESKeyBase(KeyBase):
             hmac_computed = hmac_sha256(self.id_key, data)
             if not compare_digest(hmac_computed, hmac_given):
                 raise IntegrityError('Chunk id verification failed')
-        return mkchunk(data)
+        return Chunk(data)
 
     def extract_nonce(self, payload):
         if not (payload[0] == self.TYPE or
diff --git a/borg/testsuite/archiver.py b/borg/testsuite/archiver.py
index 7c1691b..e9632ec 100644
--- a/borg/testsuite/archiver.py
+++ b/borg/testsuite/archiver.py
@@ -23,7 +23,7 @@ from ..archiver import Archiver
 from ..cache import Cache
 from ..constants import *  # NOQA
 from ..crypto import bytes_to_long, num_aes_blocks
-from ..helpers import mkchunk, Manifest, EXIT_SUCCESS, EXIT_WARNING, EXIT_ERROR
+from ..helpers import Chunk, Manifest, EXIT_SUCCESS, EXIT_WARNING, EXIT_ERROR
 from ..key import KeyfileKeyBase
 from ..remote import RemoteRepository, PathNotAllowed
 from ..repository import Repository
@@ -1677,8 +1677,8 @@ def test_get_args():
 
 def test_compare_chunk_contents():
     def ccc(a, b):
-        chunks_a = [mkchunk(data) for data in a]
-        chunks_b = [mkchunk(data) for data in b]
+        chunks_a = [Chunk(data) for data in a]
+        chunks_b = [Chunk(data) for data in b]
         compare1 = Archiver.compare_chunk_contents(iter(chunks_a), iter(chunks_b))
         compare2 = Archiver.compare_chunk_contents(iter(chunks_b), iter(chunks_a))
         assert compare1 == compare2
diff --git a/borg/testsuite/helpers.py b/borg/testsuite/helpers.py
index 7dec5ad..51d3448 100644
--- a/borg/testsuite/helpers.py
+++ b/borg/testsuite/helpers.py
@@ -13,7 +13,7 @@ import time
 from ..helpers import Location, format_file_size, format_timedelta, make_path_safe, \
     prune_within, prune_split, get_cache_dir, get_keys_dir, Statistics, is_slow_msgpack, \
     yes, TRUISH, FALSISH, DEFAULTISH, \
-    StableDict, int_to_bigint, bigint_to_int, parse_timestamp, CompressionSpec, ChunkerParams, mkchunk, \
+    StableDict, int_to_bigint, bigint_to_int, parse_timestamp, CompressionSpec, ChunkerParams, Chunk, \
     ProgressIndicatorPercent, ProgressIndicatorEndless, load_excludes, parse_pattern, \
     PatternMatcher, RegexPattern, PathPrefixPattern, FnmatchPattern, ShellPattern, partial_format, ChunkIteratorFileWrapper
 from . import BaseTestCase, environment_variable, FakeInputs
@@ -902,7 +902,7 @@ def test_partial_format():
 
 
 def test_chunk_file_wrapper():
-    cfw = ChunkIteratorFileWrapper(iter([mkchunk(b'abc'), mkchunk(b'def')]))
+    cfw = ChunkIteratorFileWrapper(iter([Chunk(b'abc'), Chunk(b'def')]))
     assert cfw.read(2) == b'ab'
     assert cfw.read(50) == b'cdef'
     assert cfw.exhausted
diff --git a/borg/testsuite/key.py b/borg/testsuite/key.py
index 737e3a2..34d2d9a 100644
--- a/borg/testsuite/key.py
+++ b/borg/testsuite/key.py
@@ -6,7 +6,7 @@ from binascii import hexlify, unhexlify
 
 from ..crypto import bytes_to_long, num_aes_blocks
 from ..key import PlaintextKey, PassphraseKey, KeyfileKey
-from ..helpers import Location, mkchunk
+from ..helpers import Location, Chunk
 from . import BaseTestCase
 
 
@@ -47,7 +47,7 @@ class KeyTestCase(BaseTestCase):
 
     def test_plaintext(self):
         key = PlaintextKey.create(None, None)
-        chunk = mkchunk(b'foo')
+        chunk = Chunk(b'foo')
         self.assert_equal(hexlify(key.id_hash(chunk.data)), b'2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae')
         self.assert_equal(chunk, key.decrypt(key.id_hash(chunk.data), key.encrypt(chunk)))
 
@@ -55,9 +55,9 @@ class KeyTestCase(BaseTestCase):
         os.environ['BORG_PASSPHRASE'] = 'test'
         key = KeyfileKey.create(self.MockRepository(), self.MockArgs())
         self.assert_equal(bytes_to_long(key.enc_cipher.iv, 8), 0)
-        manifest = key.encrypt(mkchunk(b'XXX'))
+        manifest = key.encrypt(Chunk(b'XXX'))
         self.assert_equal(key.extract_nonce(manifest), 0)
-        manifest2 = key.encrypt(mkchunk(b'XXX'))
+        manifest2 = key.encrypt(Chunk(b'XXX'))
         self.assert_not_equal(manifest, manifest2)
         self.assert_equal(key.decrypt(None, manifest), key.decrypt(None, manifest2))
         self.assert_equal(key.extract_nonce(manifest2), 1)
@@ -67,7 +67,7 @@ class KeyTestCase(BaseTestCase):
         # Key data sanity check
         self.assert_equal(len(set([key2.id_key, key2.enc_key, key2.enc_hmac_key])), 3)
         self.assert_equal(key2.chunk_seed == 0, False)
-        chunk = mkchunk(b'foo')
+        chunk = Chunk(b'foo')
         self.assert_equal(chunk, key2.decrypt(key.id_hash(chunk.data), key.encrypt(chunk)))
 
     def test_keyfile2(self):
@@ -85,9 +85,9 @@ class KeyTestCase(BaseTestCase):
         self.assert_equal(hexlify(key.enc_hmac_key), b'b885a05d329a086627412a6142aaeb9f6c54ab7950f996dd65587251f6bc0901')
         self.assert_equal(hexlify(key.enc_key), b'2ff3654c6daf7381dbbe718d2b20b4f1ea1e34caa6cc65f6bb3ac376b93fed2a')
         self.assert_equal(key.chunk_seed, -775740477)
-        manifest = key.encrypt(mkchunk(b'XXX'))
+        manifest = key.encrypt(Chunk(b'XXX'))
         self.assert_equal(key.extract_nonce(manifest), 0)
-        manifest2 = key.encrypt(mkchunk(b'XXX'))
+        manifest2 = key.encrypt(Chunk(b'XXX'))
         self.assert_not_equal(manifest, manifest2)
         self.assert_equal(key.decrypt(None, manifest), key.decrypt(None, manifest2))
         self.assert_equal(key.extract_nonce(manifest2), 1)
@@ -98,6 +98,6 @@ class KeyTestCase(BaseTestCase):
         self.assert_equal(key.enc_hmac_key, key2.enc_hmac_key)
         self.assert_equal(key.enc_key, key2.enc_key)
         self.assert_equal(key.chunk_seed, key2.chunk_seed)
-        chunk = mkchunk(b'foo')
+        chunk = Chunk(b'foo')
         self.assert_equal(hexlify(key.id_hash(chunk.data)), b'818217cf07d37efad3860766dcdf1d21e401650fed2d76ed1d797d3aae925990')
         self.assert_equal(chunk, key2.decrypt(key2.id_hash(chunk.data), key.encrypt(chunk)))
```

**Comment by ThomasWaldmann** [comment]
guess the Chunk function is cleaner. Having a class with a `__new__` that returns a superclass instance is a bit weird. It is a about as thin as mine wrapper anyway, so it would be just about the name - and that can be done simpler.

another thing would be if we expect more functionality, like methods or properties, then a class would make more sense, if we actually return instances of it.

**Comment by ThomasWaldmann** [comment]
btw, you could pull request against the branch in my repo.

**Pull request merged**
