### PR TITLE
Backport of #5048 Option to bypass locking to use sensible borg commands with read-only repositories

### PR DESCRIPTION
**Pull request by finefoot**
See #5048

### CODE REVIEW

**Comment by finefoot** [comment]
Let's see if the checks pass. Will squash afterwards.

**Comment by finefoot** [comment]
Checks are passing, too :+1: Now you've got some additional content for the 1.1.12 release. :wink: 

By the way, I was just having a look at the (master) docs to review the changes but they didn't automatically update, again https://borgbackup.readthedocs.io/en/master/usage/general.html Or does it just take that long?

**Comment by finefoot** [comment]
@ThomasWaldmann Checks are passing, too :+1: Now you've got some additional content for the 1.1.12 release. :wink: 

By the way, I was just having a look at the (master) docs to review the changes but they didn't automatically update, again https://borgbackup.readthedocs.io/en/master/usage/general.html Or does it just take that long?

**Comment by ThomasWaldmann** [comment]
Thanks!

**Comment by ThomasWaldmann** [comment]
Started the master docs build manually, now the new stuff shows up.

**Comment by finefoot** [comment]
Hmm, is https://github.com/borgbackup/borg/blob/master/docs/usage/common-options.rst.inc not automatically being built?

**Comment by ThomasWaldmann** [comment]
See #5107.

**Comment by finefoot** [comment]
Ah, found it https://borgbackup.readthedocs.io/en/master/development.html#releasing So it automatically gets generated but that script has to be executed manually.

**Comment by finefoot** [comment]
Ah, found it https://borgbackup.readthedocs.io/en/master/development.html#releasing So it gets generated automatically - but the script that generates it has to be executed manually. I was just wondering. ;)

**Pull request merged**
