### PR TITLE
Complete documentation on append-only remote repos (#5519)

### PR DESCRIPTION
**Pull request by braewoods**
This is a back-port attempt of #5519. It is intended to be part of issue #5838.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
**Specificities: Append-only repositories** <- that section is missing in your changeset - did you check if it is already there?

**Comment by braewoods** [comment]
It appears to be so. See the whole file here: https://github.com/braewoods/borg/blob/typos_dec/docs/deployment/hosting-repositories.rst

**Comment by braewoods** [comment]
Apparently the version already in the 1.1-maint branch already has that "Specificities: Append-only repositories" section header.

**Comment by ThomasWaldmann** [comment]
OK, thanks for checking!

**Pull request merged**
