### PR TITLE
Update link to cachedir spec

### PR DESCRIPTION
**Pull request by brakhane**
The old link is blocked by Yale firewall.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for your PR, but did you edit the automatically generated docs?

The commandline help is generated from `archiver.py` and only the manually written docs come from .rst files.

**Comment by brakhane** [comment]
> Thanks for your PR, but did you edit the automatically generated docs?

I just did run sed on all the files. :)

Interestingly, the archiver.py already has the correct link, but the manpages still have the incorrect link.

I've changed the PR to only include the rst files

**Comment by brakhane** [comment]
I've just noticed that the other changes came from changeset 19c269cdcf65dfae31ed0f13b5bdb46a389d9c7d.

**Comment by ThomasWaldmann** [comment]
the auto-generated doc files will be updated from `archiver.py` when i do a release.

**Comment by ThomasWaldmann** [comment]
https://github.com/step21/borg/commit/85fa5e67f38672021635b563711dd7db34792071
https://github.com/step21/borg/commit/0c99aee724cbfa4e10acfab37e0ca9e85065d90a

so, guess there is nothing left to do (except updating the autogenerated docs, which is part of the usual release procedure).

**Pull request closed without merging**
