### PR TITLE
[DOCS] #4587 – Make Sphinx warnings break docs build

### PR DESCRIPTION
**Pull request by fantasya-pbem**
Backport from master, see #5030

### CODE REVIEW

**Comment by fantasya-pbem** [comment]
Please wait, I made some mistakes.

**Comment by fantasya-pbem** [comment]
> Please wait, I made some mistakes.

Now it's clean.

**Comment by fantasya-pbem** [comment]
Is there a possibility to restart the Travis CI without pushing another commit?

**Comment by ThomasWaldmann** [comment]
Yes. The possibility to restart jobs is there again.

Somehow it was gone for a while, but as I did a fresh login now, I was offered it again.

**Comment by fantasya-pbem** [comment]
Don't have a clue why the Python 3.4 Travis CI fail here. It's just *.rst files that we change here, and other maint-1.1 build pass.

**Comment by ThomasWaldmann** [comment]
restarted 2x 3.4 linux and 1x 3.5 mac travis jobs.

**Comment by fantasya-pbem** [comment]
Failed again, bad. I will try again with more granular incremental changes.

**Pull request closed without merging**
