### PR TITLE
Clarify extract is relative to current directory

### PR DESCRIPTION
**Pull request by jcrben**
I'm still hoping that a destination switch can be added (requested long ago in https://github.com/jborg/attic/issues/195), but in the meantime this may help. I'm guessing this clobbers any existing files.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/development.html#contributions see the 2nd item there.

**Comment by jcrben** [comment]
```
choose the branch you base your changesets on wisely:
choose x.y-maint for stuff that should go into next x.y release (it usually gets merged into master branch later also)
choose master if that does not apply
```

This should be master right? Doesn't seem like a doc tweak like this would need to be held up until the next release.

**Comment by enkore** [comment]
Thomas probably meant to link this version (and yes, that change should probably be on 1.0-maint also ;D) http://borgbackup.readthedocs.io/en/latest/development.html#contributions

**Comment by jcrben** [comment]
OK, I switched it - let me know if I'm missing anything else...

**Comment by ThomasWaldmann** [comment]
thanks!

**Pull request merged**
