### PR TITLE
freebsd xattr namespace fixes

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
see commit comments.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
remove freebsd from might-be-broken list in exception handler.
at least in master branch, which tests on freebsd 12, it is not broken.

**Comment by ThomasWaldmann** [comment]
tagging this for a backport to 1.1-maint branch, as this is a bug fix.

it's a bit unpretty that this will change xattr storage format in 1.1.x, but the code is able to deal with the not-namespace-prefixed xattr keys of older backups also.

**Comment by asomers** [comment]
You may want to look at something like https://github.com/xattr/xattr for a more portable API.

**Comment by ThomasWaldmann** [comment]
@asomers i know it, see the ticket we have about it.

**Comment by ThomasWaldmann** [comment]
note: do not backport d79d505d89aac07d6daeefa0f5ffafc3bba75008 as long as 1.1-maint branch vagrant testing is based on freebsd 10.3.

**Pull request merged**
