### PR TITLE
docs: installation: Add instructions for Windows

### PR DESCRIPTION
**Pull request by RayyanAnsari**
Remove the old Windows README while we're at it.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Change looks good, but you didn't remove the Windows README (yet?).

**Comment by RayyanAnsari** [comment]
Forgot to `git add` it 😅

**Comment by RayyanAnsari** [comment]
Should be there now.

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
