### PR TITLE
borg benchmark cpu: display benchmarks of cpu bound stuff

### LINKED ISSUE #6233: implement borg benchmark cpu
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

# Describe the problem you're observing

https://borgbackup.readthedocs.io/en/master/usage/init.html says that `repokey-blake2` my be faster than `repokey` on some clients, but slower on others.

Instead of trying to give users hints on which mode might be faster we should show users how to compare the two modes on **their** hardware. Trusting advice given in the docs instead of doing your own experiments is a cargo cult (and we should discourage that!).

It looks like we already have [`borg benchmark crud`](https://borgbackup.readthedocs.io/en/master/usage/benchmark.html) that could be used for this purpose - someone just needs to figure out how and document that.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
fixes #6233.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
```
$ borg benchmark cpu

Non-cryptographic checksums / hashes ===========================
crc32        1GB        0.722s
xxh64        1GB        0.122s
Cryptographic hashes / MACs ====================================
hmac-sha256  1GB        0.680s
blake2b-256  1GB        2.421s
Compression ====================================================
lz4          0.1GB      0.010s
zstd,1       0.1GB      0.027s
zstd,3       0.1GB      0.031s
zlib,0       0.1GB      0.026s
Chunkers =======================================================
buzhash,19,23,21,4095  1GB        1.539s
fixed,1048576          1GB        0.036s
Encryption =====================================================
aes-256-ctr-hmac-sha256 1GB        1.143s
aes-256-ctr-blake2b    1GB        2.883s
aes-256-ocb            1GB        0.949s
```

**Comment by FabioPedretti** [comment]
Great!
Rather than using a fixed size of 1GB what about running every test for a fixed amount of time?
It would provide better precision for tests using a very small amount of time.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti Guess it was easier like that. :-)

**Comment by ThomasWaldmann** [comment]
Just want to add an EPYC benchmark result:
```
aes-256-ocb              1GB        0.185s          ==     >5GB/s!
chacha20-poly1305        1GB        0.434s
```

**Pull request merged**
