### PR TITLE
borg mount: support exclusion group options and paths, fixes #2138

### LINKED ISSUE #2138: borg mount only a selected PATH (as in extract)
Given the fairly amount of CPU power needed for the "versions" option (which I found utterly useful), I'd like to ask for restrict the mount to just a specific PATH. IMO, the use of the versions option typically means you are looking for the versions of a (some) specific (set of) file(s).

E.g. OMG! Someone, at some time, modified "Documents/Important/analysis.odt". I need to recover the previous version (whenever it was). I don't want to mount all the (potentially huge) directory tree with all the versions. Just that file/directory.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/41830614-borg-mount-only-a-selected-path-as-in-extract)

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
borg mount [options] repo_or_archive mountpoint path [paths...]

paths: you can just give some "root paths" (like for borg extract) to
only partially populate the FUSE filesystem.

Similar for these exclusion group options:
--exclude
--exclude-from
--pattern
--patterns-from
--strip-components

### CODE REVIEW

**Comment by alejandro-perez** [comment]
This is beautiful!
I tested it, and the results are amazing. Just mounted my Dropbox folder (yes I backup that one too, trust none), which has 2GB and 5650 files, and it took 1m22s and only 92m RAM, as opposed to the 4m1s and 1100m RAM of mounting the whole thing. And all that in less than 30 lines of code, astonishing.

**Comment by alejandro-perez** [comment]
Another example. Mounting my LXC repository takes 10 minutes and 4,6GB RAM, but if I just select one container, it takes only 3m:30s and just 200MB RAM.
Savings in time are good, but savings in memory can be really huge, from making it unusable (if you have a really big repository and not that much RAM) to make it completely usable. So thanks again.

**Comment by ThomasWaldmann** [comment]
rebased on master, resolved conflicts. ^^^

**Comment by ThomasWaldmann** [comment]
Updated again, now it should work correctly for hardlinks, even if the hardlink master (first hardlink) is excluded.

**Comment by ThomasWaldmann** [comment]
rebased again, minor cosmetic fixes.

if someone wants to try / review, feel free.

**Comment by ThomasWaldmann** [comment]
I'll do some manual testing now, then merge and backport to 1.1 ...

**Pull request merged**
