### PR TITLE
update CHANGES (1.0)

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by enkore** [comment]
1.0.11(rc1) should be delayed until we figure the include patterns stuff out (cmdline parsing fix, include semantics etc.); but for the 1.1 beta this is not a blocking issue.

**Comment by ThomasWaldmann** [comment]
@enkore yes, see the 1.0.11rc1 milestone. if there is something missing, add tickets.

**Comment by ThomasWaldmann** [comment]
as this might take a while, we could have a CHANGES update now nevertheless.
we need to do that more frequently.

**Comment by ThomasWaldmann** [comment]
so, merge or any changes/additions?

**Comment by enkore** [comment]
We can merge it now and update it when we fix the other stuff mentioned above.

**Pull request merged**
