### PR TITLE
Document why we use faked debug mode

### PR DESCRIPTION
**Pull request by PlasmaPower**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
thanks!

**Comment by ThomasWaldmann** [comment]
Seems like EISDIR is back.

**Comment by PlasmaPower** [comment]
Hmm, guess so. I'm not sure I can reassign the bounty, we might need to create a new issue.

**Comment by ThomasWaldmann** [comment]
Keep the bounty for all the work you have done on this up to now and just open a new issue.

**Comment by PlasmaPower** [comment]
Thanks! I'm on mobile now, but I'll create the issue soon.

**Comment by enkore** [comment]
(Obsolete)

**Pull request closed without merging**
