### PR TITLE
2 back ports

### PR DESCRIPTION
**Pull request by shawnl**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/4497/files please check this again, it seems you have not backported the lower part.

also please check that in all possible code paths it will call "simple" once and "ext" once.

**Comment by shawnl** [comment]
the lower part did nothing,and shouldn't have been in a patch to be backported.
```
                md = self.metadata_collector.stat_attrs(st, path, fd=fd)
                item.update(md)
```
```
                item.update(self.metadata_collector.stat_ext_attrs(st, path, fd=fd))
```
Also it isn't applicable, as there is no metadata collector in the old code.

**Comment by ThomasWaldmann** [comment]
Look again, the lower part of the master patch was the main thing.

**Comment by shawnl** [comment]
oh wow! yeah, and ext and simple are both called for every code path (it all goes to `return status`, and those are both at the same code level.)

**Comment by ThomasWaldmann** [comment]
ok, looks good now! thanks for helping!

**Pull request merged**
