### PR TITLE
Remove trailing whitespace

### LINKED ISSUE #1382: Trailing whitespace
`grep -I -l -- $'[ \t]$' $(git ls-files .)` gives a list of files with trailing whitespace:

```
CHANGES.rst
README.rst
docs/changes.rst
docs/deployment.rst
docs/installation.rst
docs/internals.rst
docs/misc/internals-picture.txt
docs/misc/prune-example.txt
src/borg/platform/posix.pyx
tox.ini
```

I'd sort them into four different categories:

- Code
- Configuration
- Documentation
- Documentation diagrams

I'd say we should remove all but the diagrams. Opinions? (I'll make a PR once we decide which to remove)

### PR DESCRIPTION
**Pull request by PlasmaPower**
One note - there's trailing whitespace in `src/borg/platform/posix.pyx` which is on master but not 1.0-maint.

Fixes #1382

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
The docs/usage/*.rst.inc files are autogenerated from python code and should not be in this changeset.

**Comment by PlasmaPower** [comment]
@ThomasWaldmann Fixed.

**Comment by ThomasWaldmann** [comment]
thanks! now wait a little until it is merged into master and then we check master again...

**Comment by PlasmaPower** [comment]
@ThomasWaldmann Thanks! #1394

**Pull request merged**
