### PR TITLE
borg help should print <command> list in sorted order, fixes #4471

### LINKED ISSUE #4471: borg help should print <command> list in sorted order
When calling "borg help", in section "required arguments: <command>" it lists the available commands unsorted. They should be sorted alphabetically.

@ThomasWaldmann: I'm not a Python programmer, but I looked into archiver.py and think I can fix that by myself. I consider this issue a good first one for me.

### PR DESCRIPTION
**Pull request by fantasya-pbem**
[TASK] #4471 – borg help should print <command> list in sorted order: Fixed.

- Added a `# borg <command>` line above each subparser.
- Changed order of subparsers to get ordered output.
- Help parser moved to top intentionally.
- Tested `borg help`, all `borg help <command>`, `borg help <additional topic>` and `borg <command> <subcommand> -h` where applicable. They seem to work.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
this is impossible to review on github as it can not nicely display moved code sections in the diff display.

**Comment by ThomasWaldmann** [comment]
as a suggestion for the future: never mix moving around code with other changes, not even trivial ones.

**Comment by fantasya-pbem** [comment]
> as a suggestion for the future: never mix moving around code with other changes, not even trivial ones.

Sorry, I am aware of this rule.

Do you mean this line:
`subparsers = parser.add_subparsers(title='required arguments', metavar='<command>')`

I had to take it out of the mount block in order to move the mount block.

**Comment by ThomasWaldmann** [comment]
I just read your top post, still searching for a tool for being able to review your change...

**Comment by fantasya-pbem** [comment]
I guess there is no such tool that can visualize such a mix of code blocks, sadly...

**Comment by fantasya-pbem** [comment]
If you prefer I could redo the changes I have made in several commits, so you may better follow the changes?

**Comment by ThomasWaldmann** [comment]
@fantasya-pbem i tried meld, but it's not much better / does not give a reviewable output.

can you do 1 move at a time, commit, next one? and do other changes in a commit after all the moving?

sorry about the double work, but i'ld really like to have all changes reviewed.

**Comment by fantasya-pbem** [comment]
OK

**Pull request closed without merging**
