### PR TITLE
Display proper repo URL.

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
you manually tried it for both usecases?

**Comment by skorokithakis** [comment]
I tried it with the variable and without, yes.

**Comment by ThomasWaldmann** [comment]
i meant local and remote.

**Comment by skorokithakis** [comment]
Yes, that also seems to work fine.

**Comment by ThomasWaldmann** [comment]
ok, thanks!

**Pull request merged**
