### PR TITLE
#2800 - Better explanation of the --ignore-inode option relevance

### PR DESCRIPTION
**Pull request by palant**
See #2800 for explanation and discussion.

### CODE REVIEW

**Comment by enkore** [comment]
Please do the editing in src/borg/archiver.py; this file is automatically generated ("
.. IMPORTANT: this file is auto-generated from borg's built-in help, do not edit!")

**Comment by palant** [comment]
I assume that I would still have to run docs generation so that `docs/` directory doesn't get out of sync. Am I stupid if I cannot find the mechanism doing that?

**Comment by enkore** [comment]
That's documented [here](http://borgbackup.readthedocs.io/en/latest/development.html#documentation). It is not required to re-generate these files with every edit, since that's always done as part of the [release preparations](http://borgbackup.readthedocs.io/en/latest/development.html#creating-a-new-release).

**Comment by palant** [comment]
> It is not required to re-generate these files with every edit, since that's always done as part of the release preparations.

Wow, so it's duplicated and outdated content being kept in the repository. Sounds like a footgun.

**Comment by ThomasWaldmann** [comment]
@palant The basic problem you address is known and iirc we tried to do it otherwise, but there was some issue which I do not do remember right now.

**Pull request merged**
