### PR TITLE
remove empty shadowed_segments lists, fixes #5275

### LINKED ISSUE #5275: check empty segments lists in shadow_index
while doing #5263, i tried to remove empty segments lists from the shadow_index, but then tests failed.

as they maybe shouldn't remain in there forever, this needs checking again

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
also:
- add test for removed empty shadowed_segments list
- add some comments
- add repo_dump test debug tool

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@enkore can you please try & review?

**Comment by timmc** [comment]
I notice that `Repository.put` doesn't add to `shadow_index` -- is that intentional? Not sure if there's an impact on this PR.

**Comment by ThomasWaldmann** [comment]
rebased on current master.

**Comment by ThomasWaldmann** [comment]
@timmc good catch! i did a little refactor and added a comment (see 41800bc).

we will have to check whether there is a bug or that has to be like that, not sure yet.

**Comment by ThomasWaldmann** [comment]
@timmc @enkore see discussion above and commits 41800bc and c7f0aac .

**Comment by ThomasWaldmann** [comment]
I'll merge this soon, but it would be good if there was some more independent review.

**Pull request merged**
