### PR TITLE
borg create: fix stats

### LINKED ISSUE #3224: wrong original size in borg create
Hello,
[borg 1.1.1  python 3.4.5 CentOs 6]
I tried 2 times with same command but different files ( oracle dump ) and both times I had
an original size reported twice bigger than the real one.
The file is 109 GB.
I tried even with smaller files but the problem did not appear.

```
# borg create -p --stats /opt/mnt/test.borg::test2 ads_orcl_daily_dmp_5
------------------------------------------------------------------------------
Archive name: test2
Archive fingerprint: ba34d3cb846d521388a14ea5cf1b9a8addb114de386a042738b99fac01e48a42
Time (start): Thu, 2017-10-26 12:33:18
Time (end):   Thu, 2017-10-26 13:33:38
Duration: 1 hours 20.12 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              232.90 GB            205.06 GB            102.53 GB
All archives:              232.90 GB            205.06 GB            102.53 GB

                       Unique chunks         Total chunks
Chunk index:                   44512                89022
------------------------------------------------------------------------------
```
giuseppe

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
master branch only, not present in 1.1-maint.

### CODE REVIEW

**Comment by enkore** [comment]
Wasn't this observed in 1.1, which does this differently?

**Comment by ThomasWaldmann** [comment]
IIRC I tried to reproduce in master and found it broken. Maybe it has other reasons in 1.1, that could be.

**Comment by ThomasWaldmann** [comment]
output of fixed code:
```
(borg-env) tw@tux:~/w/borg$ borg init -e none repo
(borg-env) tw@tux:~/w/borg$ borg create --stats repo::arch src
------------------------------------------------------------------------------
Archive name: arch
Archive fingerprint: 2225d8d8fc2424e179a8c311ff950c936a429c4e598389552212e6777b6b0e7b
Time (start): Thu, 2017-11-02 17:39:43
Time (end):   Thu, 2017-11-02 17:39:45
Duration: 2.13 seconds
Number of files: 471
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              146.66 MB             39.29 MB             36.87 MB
All archives:              146.66 MB             39.29 MB             36.87 MB

                       Unique chunks         Total chunks
Chunk index:                     499                  508
------------------------------------------------------------------------------


(borg-env) tw@tux:~/w/borg$ borg create --stats repo::arch2 src
------------------------------------------------------------------------------
Archive name: arch2
Archive fingerprint: 9b75b27a7e31d8afdf9b05c402bdc9ff80fea5f9d56e54a9a3282ce33aa5d4b0
Time (start): Thu, 2017-11-02 17:40:22
Time (end):   Thu, 2017-11-02 17:40:22
Duration: 0.09 seconds
Number of files: 471
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              146.66 MB             39.29 MB             41.75 kB
All archives:              293.33 MB             78.58 MB             36.91 MB

                       Unique chunks         Total chunks
Chunk index:                     501                 1016
------------------------------------------------------------------------------
```

**Comment by ThomasWaldmann** [comment]
output of master code:
```
(borg-env) tw@tux:~/w/borg$ borg init -e none repo
(borg-env) tw@tux:~/w/borg$ borg create --stats repo::arch src
------------------------------------------------------------------------------
Archive name: arch
Archive fingerprint: 7adea46884c14504608ef2f4cbb54f6e5a8a0607b5d1b4d2e84cabcc2867cf13
Time (start): Thu, 2017-11-02 17:43:44
Time (end):   Thu, 2017-11-02 17:43:46
Duration: 2.50 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              106.12 kB             41.73 kB             41.73 kB
All archives:              146.66 MB             39.29 MB             36.87 MB

                       Unique chunks         Total chunks
Chunk index:                     499                  508
------------------------------------------------------------------------------


(borg-env) tw@tux:~/w/borg$ borg create --stats repo::arch2 src
------------------------------------------------------------------------------
Archive name: arch2
Archive fingerprint: efbfeb5728b5d8f287320b3567b5ae13d2723ea228a7360131a2fb10ed2e36f0
Time (start): Thu, 2017-11-02 17:44:00
Time (end):   Thu, 2017-11-02 17:44:00
Duration: 0.09 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              106.12 kB             41.73 kB             41.73 kB
All archives:              293.33 MB             78.58 MB             36.91 MB

                       Unique chunks         Total chunks
Chunk index:                     501                 1016
------------------------------------------------------------------------------
```
"Number of files" and "This Archive" stats obviously broken.

**Comment by ThomasWaldmann** [comment]
@enkore you're right, this is only in master branch and a different bug than the one I was starting with.

**Comment by ThomasWaldmann** [comment]
@enkore anything else?

**Pull request merged**
