### PR TITLE
add OS X to travis build matrix

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
They do not offer osx workers currently. They said they send me an email if capacity is available again.

**Comment by anarcat** [comment]
so then should we merge this or just close?

**Comment by ThomasWaldmann** [comment]
we can keep it open while I wait for that email.

**Comment by ThomasWaldmann** [comment]
well, still no news from travis-ci. rejecting this one, we can redo it easily as soon as travis-ci is ready for it.

**Pull request closed without merging**
