### PR TITLE
Create and use Brewfile

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Hmm, I am a bit torn about this.

As long as the Brewfile contents is only used by ci.yml, I rather dislike having it in a separate file (and even a file in the already cluttered-too-much toplevel directory).

But I've seen brew bundle can also receive input via a pipe, so maybe that solves this.

**Comment by stephengroat** [comment]
only reason I lean towards including in the repo root is for macos developers, include `brew bundle` in the development instructions tends to make environment setup much easier

**Comment by stephengroat** [comment]
see https://github.com/borgbackup/borg/pull/6052/commits/ba8a36a38d41539bbc2915d95ab04ccad09e21cc

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/docs/installation.rst#macos

guess it rather should move to there?

the normal user install is required for developers also, so we describe common steps there and only the dev specific stuff in the development section.

**Comment by ThomasWaldmann** [comment]
@stephengroat did you see my last comment? also, it seem this branch needs a rebase on current master / conflict resolution.

Sorry, but I had to update github CI for macOS because it recently got broken due to macOS fuse testing issues.

**Comment by ThomasWaldmann** [comment]
Rebased on current master, updated requirements, worked on docs.

**Pull request merged**
