### PR TITLE
support setting the pattern style default in patterns file

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Issue #2279

### CODE REVIEW

**Comment by enkore** [comment]
Hmm, for the frequent cases single-char "commands" make sense, but I think I'd be better to have more verbose commands here.

E.g.

```
    R /
    p sh
    - /home/*/.cache
    - /home/*/Downloads
    + /home/susan
    - /home/*
```

vs.

```
    root /
    pattern-style sh
    - /home/*/.cache
    - /home/*/Downloads
    + /home/susan
    - /home/*
```

**Comment by ThomasWaldmann** [comment]
@enkore yup, I'll add a changeset here. It is not quite in scope of this PR, but just for the sake of easy backporting.

**Comment by ThomasWaldmann** [comment]
so, anything else (besides docs)?

**Comment by ThomasWaldmann** [comment]
Hmm, the changes only deal with a patterns **file**. Do we need this mechanism for cmdline args also?

@leo-b can you review?

**Comment by enkore** [comment]
That would make command line parsing stateful, not just order-dependent... do we really want that?

**Comment by leo-b** [comment]
BTW: Is there really a need to change the default pattern style _inside a file for just a part_ of the file?

If it is sufficient to specify a per file default, I'd propose this commandline syntax:
``--patterns-from re:/etc/borg/mypatterns.conf``
(postfix uses a similar way to specify the [lookup table style](http://www.postfix.org/DATABASE_README.html)

It is intuitive and clearly defines the scope for this default.

**Comment by ThomasWaldmann** [comment]
@leo-b i think it is useful being able to switch in the file.

- people will like to use sh: syntax mostly, but maybe need re: for more complicated matching
- people will like to have only one such patterns file, so that everything is in one place

**Comment by ThomasWaldmann** [comment]
@leo-b concerning warning about fnmatch: guess that's nothing new and could happen before this change also by giving the bad patterns combinations on the commandline. So: separate PR for that (please help, if you like).

**Comment by enkore** [comment]
I think it's better to set the pattern style in the file itself than on the command line, because otherwise pattern style and the patterns and the files are not synchronized - you have to look in two places to know how they are interpreted.

But maybe it's a good idea to say one style per file is enough (i.e. have to set pattern style at most once before any patterns appear in the file)?

**Comment by ThomasWaldmann** [comment]
@enkore see above. if we restrict to 1 style per file, what happens if you first use sh: and then notice that you can't implement some exclude with it, rewrite the whole thing? that sounds like a rather big inconvenience, considering it did not take much code (in fact: likely none) to implement switching as often as one likes.

**Comment by enkore** [comment]
convinced

**Comment by ThomasWaldmann** [comment]
collapsed changesets, will merge after travis.

**Pull request merged**
