### PR TITLE
Ignore generated platform C files

### PR DESCRIPTION
**Pull request by PlasmaPower**
Seems like every time I make a PR I notice some other autogenerated files that aren't gitignored. At least I didn't commit them this time :smile:.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
guess you could just modify these, they just got moved:
```
 platform_darwin.c
 platform_freebsd.c
 platform_linux.c
 platform_posix.c
```

**Comment by PlasmaPower** [comment]
@ThomasWaldmann Are you saying commit those files? Or hard code them?

**Comment by ThomasWaldmann** [comment]
The files platform_*.c got moved to the platform/ directory, so the .gitignore just needs to get fixed.

**Comment by PlasmaPower** [comment]
Oh, I see. Would a more general `src/borg/platform/platform_*.c` check be better?

**Comment by PlasmaPower** [comment]
Actually, nope. It was moved from `platform_*.c` to `src/borg/platform/*.c`

**Comment by PlasmaPower** [comment]
How about this change? I don't see a reason to hard code the OSs.

**Comment by ThomasWaldmann** [comment]
Yes, that will work as long noone adds hand-edited *.c files there.

**Comment by PlasmaPower** [comment]
Okay, I've hard coded them.

**Pull request merged**
