### PR TITLE
hashindex bugfix and refactoring (backport to 1.2-maint)

### PR DESCRIPTION
**Pull request by snsmac**
Backport the commits from #7325

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@snsmac thanks for the backport. did you encounter any merge conflicts or other difficulties or did it apply cleanly?

**Comment by snsmac** [comment]
It applied without any merge conflicts

**Comment by ThomasWaldmann** [comment]
Can you please update your local `1.2-maint` branch from github and then rebase this PR onto that.

The please run the stress test again on your local system.

**Comment by snsmac** [comment]
I rebased it and the stress test passes

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
