### PR TITLE
fix sparse file test, fixes #1170

### LINKED ISSUE #1170: fix the sparse test
as seen in #1150 this test has issues on zfs. and also on xfs as seen in some borg 1.0.3 SuSE build log.

as all these filesystems also exist on linux (or freebsd), disabling by OS is not good enough.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
found out that xfs is doing stuff behind the scenes: it is pre-allocating 16MB
to prevent fragmentation (in my case, value depends on misc factors).

fixed the test so it just checks that the extracted sparse file uses less (not
necessary much less) space than a non-sparse file would use.

another problem showed up when i tried to verify the holes in the sparse file
via SEEK_HOLE, SEEK_DATA:
after the few bytes of real data in the file, there was another 16MB
preallocated space.
So I ended up checking just the hole at the start of the file.

tested on: ext4, xfs, zfs, btrfs

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by enkore** [comment]
Tested this on Solaris (because of #1150), found out that /tmp on Solaris is by default tmpfs-y and that doesn't support sparse files. If you move TMPDIR to an actual ZFS partition on Solaris then the test works (and is rather slow).

**Comment by ThomasWaldmann** [comment]
On Linux, http://linux.die.net/man/2/statfs could be used to skip the test if the fs does not support sparse files.
On IRC it was noted that this might be totally broken on OS X. No idea about other OSes.

**Comment by ThomasWaldmann** [comment]
If nobody objects, I'll merge this as is soon.

The statfs change can be done later, after more research / discussion.

**Pull request merged**
